### ISSUE TITLE
Trace/breakpoint trap on Debian Buster

### ISSUE THREAD

**Issue by stylesuxx** [ExpressLRS/ExpressLRS-Configurator#10]
## Expected Behavior
Configurator should start on Debian Linux (Buster).

## Current Behavior
Configurator immediately exits with the message `Trace/breakpoint trap`

[Stack trace](https://github.com/ExpressLRS/ExpressLRS-Configurator/files/6144396/trace.txt)

## Steps to Reproduce
1. Install configurator v0.4.0
2. Start configurator

## Your Environment
- Operating System and version: Debian Buster
- TX hardware: ---
- RX hardware: ---

**Comment by nightflasher** [comment]
No solution, but closed?

**Comment by stylesuxx** [comment]
It was just temporary for me, I de-installed, re-installed a couple of versions and it started working and I could not reproduce it anymore.
