### ISSUE TITLE
Can not connect to github when build.

### ISSUE THREAD

**Issue by gcrisis** [ExpressLRS/ExpressLRS-Configurator#11]
When build for a while,it will give a error below. 
Error
Error: Error: Cloning into 'C:\Users\10250\AppData\Roaming\ExpressLRS Configurator\firmwares\git'... fatal: unable to access 'https://github.com/ExpressLRS/ExpressLRS/': Failed to connect to github.com port 443: Timed out

position:China
I know it's network problem and i have proxy ,but I dont know how to set up.
Anyone who can give me a hand please？
Thank you very much.
![Image 1](https://user-images.githubusercontent.com/13515569/111322934-67d98800-86a4-11eb-8bb8-df1646e0d9f7.png)

**Comment by DrAlkebsi** [comment]
Hello there, I am facing the same issue. It not loading the configurator parameters as there is no data loaded from the Github repo.

**Comment by DrAlkebsi** [comment]
![image](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/100117482/84135751-fc34-47ed-89c6-5aa3a91d08bc)
