### ISSUE TITLE
When building a branch, WiFi has "ver: unknown"

### ISSUE THREAD

**Issue by pkendall64** [ExpressLRS/ExpressLRS-Configurator#110]
## Expected Behavior

The WiFi page should state the name of the branch and the commit hash

## Current Behavior

Currently displays "ver: unknown" and the hash.

## Steps to Reproduce

1. Build 'master' branch
2. Check WiFi page after build

## Possible Solution (Not obligatory)

https://github.com/ExpressLRS/ExpressLRS-Configurator/blob/eff118a76b86c63836d1cda9c4010bd0c991bc6b/src/api/src/library/FirmwareDownloader/index.ts#L142
should not have `origin/` before the branch so it creates a local ref. With the `origin/` prepended you get a disconnected head and the only information available is the git hash.

**Comment by jurgelenas** [comment]
@pkendall64 is there are other way I could pass branch name to the build process?

**Comment by jurgelenas** [comment]
Probably same thing applies to git tags as well?

**Comment by pkendall64** [comment]
> Probably same thing applies to git tags as well?

Yes, actually the same problem also exists there. I think we might be able to fix this on the firmware side. I'll see what commands we can run there and close this one if I can make it work.

**Comment by pkendall64** [comment]
Can be fixed in the firmware repo. I will work a PR for that tomorrow morning 👍
