### ISSUE TITLE
Fails when trying to run Passthrough script 

### ISSUE THREAD

**Issue by wterreb** [ExpressLRS/ExpressLRS-Configurator#12]
Using Windows 10 PC trying to run DIY_2400_RX_ESP8285_SX1280_via_BetaflightPassthrough
ExpressLRS Configurator v0.4.6 failed with the following error message:
Error: No such command "Configurator\\firmwares\\github\\src/python/BFinitPassthrough.py"
However, the file does indeed exist on my computer in  : C:\Users\werne\AppData\Roaming\ExpressLRS Configurator\firmwares\github\src\python\BFinitPassthrough.py
It is my suspicion the problem is caused by the space in the name "ExpressLRS Configurator".  Windows command line does not like spaces unless you put the whole path in quotes ("")

**Comment by jurgelenas** [comment]
@wterreb what tag / branch you were using? This issue is actually related to the firmware repository itself: https://github.com/ExpressLRS/ExpressLRS

**Comment by wernerterreb** [comment]
Thank you for the reply.   I'm not at same computer at the moment to check the version, but I just chose the latest version that the configurator offered.   I think it was something like 0.1.3 or something.   There was only two options to choose from.

**Comment by jurgelenas** [comment]
> Thank you for the reply. I'm not at same computer at the moment to check the version, but I just chose the latest version that the configurator offered. I think it was something like 0.1.3 or something. There was only two options to choose from.

Were you able to resolve it?

**Comment by wernerterreb** [comment]
Yes, but only after applying a work around.   The original problem still happens.  First I tried using PlatformIO instead of configurator.   But it was also failing because it could not not find some file  to do with passthrough mode.    But I was able to use a work-around by avoiding the passthrough method altogether and instead wiring the receiver to a FTDI board and programming it that way.  I used PlatformIO, but the configurator also works with that method.

**Comment by jurgelenas** [comment]
> Using Windows 10 PC trying to run DIY_2400_RX_ESP8285_SX1280_via_BetaflightPassthrough
> ExpressLRS Configurator v0.4.6 failed with the following error message:
> Error: No such command "Configurator\firmwares\github\src/python/BFinitPassthrough.py"
> However, the file does indeed exist on my computer in : C:\Users\werne\AppData\Roaming\ExpressLRS Configurator\firmwares\github\src\python\BFinitPassthrough.py
> It is my suspicion the problem is caused by the space in the name "ExpressLRS Configurator". Windows command line does not like spaces unless you put the whole path in quotes ("")

This was fixed as well in our firmware repository :) Thanks for reporting!

**Comment by wernerterreb** [comment]
Excellent!
