### ISSUE TITLE
unable to flash with  "HappyModel_TX_ES915TX_via_stock_BL"  

### ISSUE THREAD

**Issue by Anton33455** [ExpressLRS/ExpressLRS-Configurator#13]
## Expected Behavior

  Flash Successful

## Current Behavior

 Error Message

Flash error
Error: Unknown environment names 'HappyModel_TX_ES915TX_via_stock_BL'. Valid names are 'DIY_900_TX_ESP32_SX127x_RFM95_via_UART, DIY_900_RX_ESP8285_SX127x_via_BetaflightPassthrough, DIY_900_TX_TTGO_V2_SX127x_via_UART, DIY_2400_RX_STM32_CCG_Nano_v0_5_via_BetaflightPassthrough, Frsky_TX_R9M_via_WIFI, Frsky_RX_R9SLIMPLUS_OTA_via_BetaflightPassthrough, Frsky_TX_R9M_via_stock_BL, Frsky_TX_R9M_via_STLINK_OLD_BOOTLOADER_DEPRECATED, Frsky_RX_R9SLIMPLUS_OTA_via_STLINK, Frsky_RX_R9MX_via_BetaflightPassthrough, DIY_2400_TX_ESP32_SX1280_LORA1280F27_via_UART, Frsky_TX_R9M_LITE_via_STLINK, Jumper_RX_R900MINI_via_BetaflightPassthrough, Frsky_TX_R9M_LITE_PRO_via_STLINK, DIY_2400_TX_ESP32_SX1280_Mini_via_UART, Frsky_RX_R9MX_via_STLINK, Jumper_RX_R900MINI_via_STLINK, Frsky_TX_R9M_LITE_via_stock_BL, Frsky_RX_R9SLIMPLUS_via_STLINK, GHOST_ATTO_2400_RX_via_BetaflightPassthrough, DIY_900_TX_ESP32_SX127x_E19_via_UART, DIY_2400_RX_ESP8285_SX1280_via_BetaflightPassthrough, Frsky_RX_R9MM_R9MINI_via_BetaflightPassthrough, Frsky_TX_R9M_via_STLINK, DIY_900_TX_TTGO_V1_SX127x_via_UART, DIY_2400_RX_STM32_CCG_Nano_v0_5, DIY_900_RX_ESP8285_SX127x_via_UART, Frsky_RX_R9SLIMPLUS_via_BetaflightPassthrough, GHOST_ATTO_2400_RX_via_STLINK, DIY_2400_TX_ESP32_SX1280_E28_via_UART, DIY_2400_RX_ESP8285_SX1280_via_UART, Frsky_RX_R9MM_R9MINI_via_STLINK'

## Context

 trying to compile bin file to flash Happy Model LRS module using configurator  v0.4.8 Release 0.1.3-RC2  Target  HappyModel_TX_ES915TX_via_stock_BL

 NO

## Your Environment

- Operating System and version:
- TX hardware:
- RX hardware:

**Comment by jurgelenas** [comment]
That target is available in git development branch only at the moment. Please select that as a firmware source and try again. It will work.
