### ISSUE TITLE
Music melody in RTTTL format

### ISSUE THREAD

**Issue by sfjuocekr** [ExpressLRS/ExpressLRS-Configurator#14]
It would be nice to have music notation in the RTTTL format?

There is already a Python library ready made to make conversion easier called RTTTL-parse!

**Comment by sfjuocekr** [comment]
This site for example offers a wealth in RTTTL songs: http://esctunes.com/tunes

But there are many more resources available!

**Comment by sfjuocekr** [comment]
I wrote a little python example on how to convert from RTTTL into a usable melody:

`from rtttl.parser import parse_defaults, parse_data, remove_whitespaces

rtttl_str = 'melody:d=4,o=6,b=100:16e6,16e6,32p6,8e6,16c6,8e6,8g6,8p6'
rtttl_parts = rtttl_str.split(':')

parsed_defaults = parse_defaults(remove_whitespaces(rtttl_parts[1]))
parsed_notes = parse_data(remove_whitespaces(rtttl_parts[2]).lower(), 0)

final_string = ""

for note in parsed_notes:
        if note['duration'] == None:
                note['duration'] = parsed_defaults['duration']
        if note['pitch'] == "p":
                final_string = final_string + note['pitch'].upper() + str(note['duration']) + " "
        else:
                final_string = final_string + note['pitch'].upper() + str(parsed_defaults['octave']) + " " + str(note['duration']) + " "

final_string = final_string[:-1] + "|" + str(parsed_defaults['bpm'])
print(final_string)
`

**Comment by CapnBry** [comment]
This will be handled in ELRS, so the configurator can just pass RTTTL directly to us #641

I'll see if we can get this in to 1.0 and not have to wait until 1.1

**Comment by jurgelenas** [comment]
> This will be handled in ELRS, so the configurator can just pass RTTTL directly to us #641
> [ExpressLRS/ExpressLRS#641](https://github.com/ExpressLRS/ExpressLRS/pull/641)
> 
> I'll see if we can get this in to 1.0 and not have to wait until 1.1

Since this is already merged I will close the issue. I will also add a note about RTTL melodies support in the configurator.
