### ISSUE TITLE
Unnecessary and possibly Confusing Option presented for Betafpv 2400 RX (Diversity??)

### ISSUE THREAD

**Issue by jklong03** [ExpressLRS/ExpressLRS-Configurator#144]
## Expected Behavior

When selecting Betafpv 2.4GHz Category/BETAFPV 2400RX Device, There is an option under Performance Options for Diversity, however Betafpv doesn't currently offer a diversity RX configuration in either 900MHz or 2.4GHz ?

## Current Behavior

Non-functional Performance option is presented to user for 2.4GHz RX, but correctly is omitted for 900MHz may cause confusion?

## Steps to Reproduce

1. Currently, select any version of Firmware available

2. Select Target = "Betafpv 2.4 GHz" Category, then select "BETAFPV 2400 RX" for the Device

3. Observe "USE_DIVERSITY" option presented under Performance options

## Your Environment
Windows Configurator V1.2.5 
- Operating System and version: Windows 11
- TX hardware: Currently OG Happymodel Micro TX 2.4GHz
- RX hardware: Betafpv Nano 2400

![Screenshot 2021-11-26 22-42-47](https://user-images.githubusercontent.com/110277/143669643-8c631699-65e6-4300-83e1-b4f2ad572905.png)

**Comment by jklong03** [comment]
OK, after doing the unmanly thing and finally deciding to RTFM, I see where this is discussed on the website for both release 1.0 and 2.0. Still, it could confuse some who may wonder why some RXs have the option listed and others don't. Would hate to think that some may blindly think that checking this option on their non-diversity RX will actually improve reception?!

**Comment by jurgelenas** [comment]
> 

This is a good point. Will work on improving documentation for it. Maybe displaying some kind of a warning would be good for the users as well.
