### ISSUE TITLE
E28_ESP32_SX1280_E28

### ISSUE THREAD

**Issue by NiklasVoigt** [ExpressLRS/ExpressLRS-Configurator#150]
Wifi upload successful

Wifi upload failed after 100%

## After rebooting the Radio the module is updated 

`Warning! We have just detected `upload_port` as IP address or host name of ESP device. `upload_protocol` is switched to `espota`.
Please specify `upload_protocol = espota` in `platformio.ini` project configuration file.
lib/LED/devLED.cpp:42:17: warning: 'uint16_t flashLED(uint8_t, uint8_t, const uint8_t*, uint8_t)' defined but not used [-Wunused-function]
 static uint16_t flashLED(uint8_t pin, uint8_t pin_inverted, const uint8_t durations[], uint8_t count)
                 ^
C:/Users/NiklasVoigt/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c: In function 'spiTransferBytesNL':
C:/Users/NiklasVoigt/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c:922:39: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                 uint8_t * last_out8 = &result[c_longs-1];
                                       ^
C:/Users/NiklasVoigt/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c:923:40: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                 uint8_t * last_data8 = &last_data;
                                        ^
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  5 1124k    0     0    5 65692      0  32846  0:00:35  0:00:02  0:00:33 28799
  5 1124k    0     0    5 65692      0  21897  0:00:52  0:00:03  0:00:49 19924
  7 1124k    0     0    7 82076      0  20519  0:00:56  0:00:04  0:00:52 17224
  7 1124k    0     0    7 82076      0  16415  0:01:10  0:00:05  0:01:05 14236
  7 1124k    0     0    7 82076      0  13679  0:01:24  0:00:06  0:01:18 14714
  7 1124k    0     0    7 82076      0  11725  0:01:38  0:00:07  0:01:31  2970
  7 1124k    0     0    7 82076      0  10259  0:01:52  0:00:08  0:01:44  2970
  7 1124k    0     0    7 82076      0   9119  0:02:06  0:00:09  0:01:57     0
  7 1124k    0     0    7 82076      0   8207  0:02:20  0:00:10  0:02:10     0
  7 1124k    0     0    7 82076      0   7461  0:02:34  0:00:11  0:02:23     0
  7 1124k    0     0    7 82076      0   6839  0:02:48  0:00:12  0:02:36     0
  7 1124k    0     0    7 82076      0   6313  0:03:02  0:00:13  0:02:49     0
  8 1124k    0     0    8 98460      0   7032  0:02:43  0:00:14  0:02:29  3705
 12 1124k    0     0   12  144k      0   9840  0:01:56  0:00:15  0:01:41 14463
 15 1124k    0     0   15  176k      0  11273  0:01:42  0:00:16  0:01:26 21543
 19 1124k    0     0   19  224k      0  13501  0:01:25  0:00:17  0:01:08 34695
 24 1124k    0     0   24  272k      0  15482  0:01:14  0:00:18  0:00:56 42226
 27 1124k    0     0   27  304k      0  16392  0:01:10  0:00:19  0:00:51 40810
 28 1124k    0     0   28  320k      0  17254  0:01:06  0:00:19  0:00:47 39102
 32 1124k    0     0   32  368k      0  17951  0:01:04  0:00:21  0:00:43 41122
 35 1124k    0     0   35  400k      0  18625  0:01:01  0:00:22  0:00:39 34532
 38 1124k    0     0   38  432k      0  19240  0:00:59  0:00:23  0:00:36 35663
 41 1124k    0     0   41  464k      0  20664  0:00:55  0:00:23  0:00:32 36287
 45 1124k    0     0   45  512k      0  20977  0:00:54  0:00:25  0:00:29 37671
 49 1124k    0     0   49  560k      0  22061  0:00:52  0:00:26  0:00:26 38362
 52 1124k    0     0   52  592k      0  22457  0:00:51  0:00:27  0:00:24 39952
 55 1124k    0     0   55  624k      0  22826  0:00:50  0:00:28  0:00:22 39944
 58 1124k    0     0   58  656k      0  23168  0:00:49  0:00:29  0:00:20 39196
 62 1124k    0     0   62  704k      0  24035  0:00:47  0:00:30  0:00:17 39079
 65 1124k    0     0   65  736k      0  24316  0:00:47  0:00:31  0:00:16 36616
 68 1124k    0     0   68  768k      0  24580  0:00:46  0:00:32  0:00:14 37570
 71 1124k    0     0   71  800k      0  24828  0:00:46  0:00:33  0:00:13 31175
 74 1124k    0     0   74  832k      0  25062  0:00:45  0:00:34  0:00:11 30923
 75 1124k    0     0   75  848k      0  24814  0:00:46  0:00:35  0:00:11 28253
 78 1124k    0     0   78  880k      0  25035  0:00:45  0:00:36  0:00:09 28862
 79 1124k    0     0   79  896k      0  24801  0:00:46  0:00:37  0:00:09 25114
 82 1124k    0     0   82  928k      0  25011  0:00:46  0:00:38  0:00:08 27501
 83 1124k    0     0   83  944k      0  24790  0:00:46  0:00:39  0:00:07 26884
 88 1124k    0     0   88  992k      0  25399  0:00:45  0:00:40  0:00:05 30739
 91 1124k    0     0   91 1024k      0  25578  0:00:44  0:00:41  0:00:03 31353
 95 1124k    0     0   95 1072k      0  26140  0:00:44  0:00:42  0:00:02 35165
 98 1124k    0     0   98 1104k      0  26294  0:00:43  0:00:43 --:--:-- 40618
100 1124k    0     0  100 1124k      0  26159  0:00:44  0:00:44 --:--:-- 31691
100 1124k    0     0  100 1124k      0  25577  0:00:45  0:00:45 --:--:-- 23943
curl: (56) Recv failure: Connection was reset
*** [upload] Exception : WIFI upload FAILED!
Traceback (most recent call last):
  File "C:\Users\NiklasVoigt\.platformio\packages\tool-scons\scons-local-4.2.0\SCons\Action.py", line 1279, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "C:\Users\NiklasVoigt\AppData\Roaming\ExpressLRS Configurator\firmwares\github\ExpressLRS\src\python\upload_via_esp8266_backpack.py", line 70, in on_upload
    raise Exception("WIFI upload FAILED!")
Exception: WIFI upload FAILED!
========================= [FAILED] Took 192.94 seconds =========================
Environment                            Status    Duration
-------------------------------------  --------  ------------
DIY_2400_TX_ESP32_SX1280_E28_via_WIFI  FAILED    00:03:12.945
==================== 1 failed, 0 succeeded in 00:03:12.945 ====================`

1.

2.

3.

4.

## Possible Solution (Not obligatory)

The radio stops wifi after the update, so the configurator thinks the connection is lost. Maybe the radio can send an "ok" after 100% and the configurator recognizes that the data is 100% transferred.

## Context

Example from one of my EP receivers:

` 72  374k    0     0   72  272k      0  55736  0:00:06  0:00:05  0:00:01 40936
 81  374k    0     0   81  304k      0  51908  0:00:07  0:00:06  0:00:01 49309
 94  374k    0     0   94  352k      0  51514  0:00:07  0:00:07 --:--:-- 44115
100  374k    0     0  100  374k      0  47889  0:00:08  0:00:08 --:--:-- 42122
100  374k  100   110  100  374k     13  47895  0:00:08  0:00:08 --:--:-- 32156
{"status": "ok", "msg": "Update complete. Please wait for LED to resume blinking before disconnecting power."}
** UPLOAD SUCCESS. Flashing in progress.
** Please wait for LED to resume blinking before disconnecting power
========================= [SUCCESS] Took 25.12 seconds =========================

Environment                     Status    Duration
------------------------------  --------  ------------
HappyModel_EP_2400_RX_via_WIFI  SUCCESS   00:00:25.118
========================= 1 succeeded in 00:00:25.118 =======================`

## Your Environment

- Operating System and version:
- TX hardware:
- RX hardware:

**Comment by pkendall64** [comment]
What version were you updating from and what version were you updating to.

**Comment by NiklasVoigt** [comment]
From 2.0.0-RC2 to 2.0.0-RC3

**Comment by pkendall64** [comment]
The module is sending an "ok" before closing the connection, and then waits 200ms before rebooting.
The WiFi code is common between the TX module and the RX.

**Comment by NiklasVoigt** [comment]
I will still flash from rc3 to rc4 and report if it happens again

**Comment by NiklasVoigt** [comment]
99 1123k    0     0   99 1123k      0  54783  0:00:21  0:00:21 --:--:-- 47607
100 1123k    0     0  100 1123k      0  52295  0:00:22  0:00:22 --:--:-- 37321
100 1123k  100   110  100 1123k      4  50022  0:00:27  0:00:23  0:00:04 28540
{"status": "ok", "msg": "Update complete. Please wait for LED to resume blinking before disconnecting power."}
** UPLOAD SUCCESS. Flashing in progress.
** Please wait for LED to resume blinking before disconnecting power
======================== [SUCCESS] Took 131.94 seconds ========================

Environment                            Status    Duration
-------------------------------------  --------  ------------
DIY_2400_TX_ESP32_SX1280_E28_via_WIFI  SUCCESS   00:02:11.936
========================= 1 succeeded in 00:02:11.936 =========================


Strange... but i think this can be closed.
