### ISSUE TITLE
Configurator selecting wrong serialport

### ISSUE THREAD

**Issue by sweebee** [ExpressLRS/ExpressLRS-Configurator#16]
## Expected Behavior

Option to select a serialport

## Current Behavior

Always selecting the first serialport which is wrong in my case

## Steps to Reproduce

a computer with multiple serialports :)

## Possible Solution (Not obligatory)

Option to select a serialport

## Context

Cant flash my tx

## Your Environment

- Operating System and version: Mac OS
- TX hardware: ESP32
- RX hardware:

**Comment by sfjuocekr** [comment]
You can flash it manually over serial with UARTupload.py in the python folder.

I would like there to be a generic serial port selection, I don't really need passthrough from BF anyway as I can just use a STLink or generic serial adapter (I use a Teensy 3.2) to upload new firmware.

**Comment by sweebee** [comment]
Looks like this is implemented :)

**Comment by jurgelenas** [comment]
> Looks like this is implemented :)

Indeed! :) Thanks for closing the issue.
