### ISSUE TITLE
ELRS v2, Build fail

### ISSUE THREAD

**Issue by LoakAudio** [ExpressLRS/ExpressLRS-Configurator#163]
## Expected Behavior

Using ExpressLRS-configurator v 1.3.2, build should end in the same way with ELRS versions 1.2.1 and 2, with Success

## Current Behavior

Using ExpressLRS-configurator v1.3.2, build is **succesful**l for ELRS v1.2.1, but **failed** for ELRS v2.0.0

1.Build error
AttributeError: module 'gzip' has no attribute '_COMPRESS_LEVEL_BEST':
  File "/home/loak/.platformio/penv/lib/python3.7/site-packages/platformio/builder/main.py", line 178:
    env.SConscript(item, exports="env")
  File "/home/loak/.platformio/packages/tool-scons/scons-local-4.2.0/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/loak/.platformio/packages/tool-scons/scons-local-4.2.0/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/loak/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 61:
    build_common(env, "tx_index.html")
  File "/home/loak/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 47:
    build_html(mainfile, "INDEX_HTML", out, env)
  File "/home/loak/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 39:
    out.write(','.join("0x{:02x}".format(c) for c in compress(data.encode('utf-8'))))
  File "/home/loak/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 25:
    with gzip.GzipFile(fileobj=buf, mode='wb', compresslevel=gzip._COMPRESS_LEVEL_BEST, mtime=0.0) as f:
========================== [FAILED] Took 1.03 seconds ==========================
Environment                         Status    Duration
----------------------------------  --------  ------------
HappyModel_ES24TX_2400_TX_via_WIFI  FAILED    00:00:01.030
==================== 1 failed, 0 succeeded in 00:00:01.030 ====================

## Your Environment

- Operating System and version: Debian 10 (Buster)
- TX hardware: Happymodel ES24TX
- RX hardware:

**Comment by brandonrc** [comment]
@LoakAudio you need to update your python. Python 3.6 and python 3.7 did not have the `_COMPRESS_LEVEL_BEST`. Try to install python 3.9 and then run it again. Let me know. 

I can run a vm for testing but I have run into this problem before.

**Comment by jurgelenas** [comment]
Thanks for reporting this @LoakAudio. Closing this in favor of https://github.com/ExpressLRS/ExpressLRS-Configurator/issues/164.

**Comment by brandonrc** [comment]
@LoakAudio you have two options, you can update python to python39 or you can flash with that pr PR right now. It is basically the 2.0.0 official gold with that one modification. Not changes to the actually firmware :)

![image](https://user-images.githubusercontent.com/25802530/145687818-fb0c020b-e7fa-4908-b7f9-4a748f9c72d2.png)

Hope that helps.

**Comment by jurgelenas** [comment]
@LoakAudio you can flash this PR https://github.com/ExpressLRS/ExpressLRS/pull/1173 and it will work fine for you :) Or you can wait for 2.0.1 release.

**Comment by jurgelenas** [comment]
@brandonrc at the same time :D

**Comment by LoakAudio** [comment]
@jurgelenas, Thank you for your efficiency, the Pull Request does not appear in the list with me. But no worries, I can wait for version 2.0.1

**Comment by jurgelenas** [comment]
> @jurgelenas, Thank you for your efficiency, the Pull Request does not appear in the list with me. But no worries, I can wait for version 2.0.1
> The last one that appears is # 1171

It was merged to 2.0 maintenance branch. Check the branches tab and you should be able to find a branch named just like. It should work for you :)

**Comment by LoakAudio** [comment]
@jurgelenas , Works by the "Git Branch" tab / 2.0.x-maintenance.
Thank you very much !

**Comment by jurgelenas** [comment]
> @jurgelenas , Works by the "Git Branch" tab / 2.0.x-maintenance.
> Thank you very much !

Glad to hear that. Just for your information, that 2.x-maintenance branch will be used for 2.0.1 release, so you can use that firmware safely on your gear :)

**Comment by jmcdrone** [comment]
Always clean the mother fucker little elrs receiver module. If you already tried hard, really tried everything possible. Try now to clean it using isopropyl alcohol. That will surprise you🤩
