### ISSUE TITLE
HOME_WIFI_PASSWORD -> ********

### ISSUE THREAD

**Issue by NiklasVoigt** [ExpressLRS/ExpressLRS-Configurator#169]
It would be useful to hide the password of the wifi connection. On the right a button which makes the password visible.

Idea:
![Screenshot 2021-12-15 123632](https://user-images.githubusercontent.com/18678779/146180214-4b39717f-ebdd-4f06-9f21-5db5c254cbd7.png)

**Comment by NiklasVoigt** [comment]
i think the idea was already there
https://github.com/ExpressLRS/ExpressLRS-Configurator/commit/a946724f1cc0ca252d7fa0888749083bce63e236

**Comment by jurgelenas** [comment]
> i think the idea was already there
> [a946724](https://github.com/ExpressLRS/ExpressLRS-Configurator/commit/a946724f1cc0ca252d7fa0888749083bce63e236)

It is just for the log files :) but yeah, that might be useful as well. Will implement this in next configurator release

**Comment by NiklasVoigt** [comment]
Great!

**Comment by jurgelenas** [comment]
![image](https://user-images.githubusercontent.com/1081265/146640311-3883c24e-9738-45e8-b075-78da9ebfd370.png)

@NiklasVoigt this will be released soon :)
