### ISSUE TITLE
Open explorer window to ELRS.lua

### ISSUE THREAD

**Issue by CapnBry** [ExpressLRS/ExpressLRS-Configurator#17]
After the build process completes, it would be great to have some way of guiding the user to the ELRS.lua that matches with the firmware they just flashed. This would prevent the user from having to go to github to update their LUA, and prevent any chance they would download the HTML instead of the LUA. The file needed is in the source that is downloaded to do the build so they've already downloaded it (`src/lua/ELRS.lua`)

I'm not sure what the best way to present this to the user is. I would find it annoying if the configurator popped open a bunch of windows at the end of the build, so perhaps a button somewhere? That would be easy to miss but be pretty unobtrusive to the flow of using the configurator.

We discussed this in discord but just wanted to make sure this idea didn't get lost.

**Comment by jurgelenas** [comment]
That is a good idea. I promise to release this in the next release! :)

**Comment by jurgelenas** [comment]
Solved in 0.4.12 release. Thanks @CapnBry. Closing.
