### ISSUE TITLE
Build Error on Linux Happy model 2.4

### ISSUE THREAD

**Issue by jaapf4fs** [ExpressLRS/ExpressLRS-Configurator#170]
Hi,
I have no clue if this is a bug or my fault so I thought put it over here..
Tried to build the version 2 in the configurator v 1.3.2 for the HAPPYMODEL_EP_2400_RX and HappyModel_ES24TX_2400_TX on a Linux PC. 
And got the messages:

TX

---------------------------------------------------------------------
Processing HappyModel_ES24TX_2400_TX_via_WIFI (platform: espressif32@3.3.2; board: esp32dev; framework: arduino)
--------------------------------------------------------------------------------
Platform Manager: Installing espressif32 @ 3.3.2
Downloading
Unpacking
Platform Manager: espressif32 @ 3.3.2 has been installed!
The platform 'espressif32@3.3.2' has been successfully installed!
The rest of the packages will be installed later depending on your build environment.
Tool Manager: Installing platformio/tool-esptoolpy @ ~1.30100.0
Downloading
Unpacking
Tool Manager: tool-esptoolpy @ 1.30100.210531 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
UID bytes: 192,238,128,119,235,42

build flags: ['-D PLATFORM_ESP32=1', '-D CONFIG_TCPIP_LWIP=1', '-D BEARSSL_SSL_BASIC', '-DTARGET_TX=1 -Wall -Iinclude', '-DRADIO_2400=1', '-include target/HappyModel_ES24TX_2400_TX.h', '-D VTABLES_IN_FLASH=1', '-O2', '-DMY_BINDING_PHRASE="PASSW"', '-DMY_UID=192,238,128,119,235,42', '-DFEATURE_OPENTX_SYNC', '-DUART_INVERTED', '-DAUTO_WIFI_ON_INTERVAL="20"', '-DFAST_SYNC', '-DLATEST_COMMIT=53,99,52,56,48,56', '-DLATEST_VERSION=50,46,48,46,48', '-DTARGET_NAME=HAPPYMODEL_ES24TX_2400_TX']

Building for ESP32 Platform
AttributeError: module 'gzip' has no attribute '_COMPRESS_LEVEL_BEST':
  File "/home/disk/.platformio/penv/lib/python3.6/site-packages/platformio/builder/main.py", line 179:
    env.SConscript(item, exports="env")
  File "/home/disk/.platformio/packages/tool-scons/scons-local-4.3.0/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/disk/.platformio/packages/tool-scons/scons-local-4.3.0/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/disk/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 61:
    build_common(env, "tx_index.html")
  File "/home/disk/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 47:
    build_html(mainfile, "INDEX_HTML", out, env)
  File "/home/disk/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 39:
    out.write(','.join("0x{:02x}".format(c) for c in compress(data.encode('utf-8'))))
  File "/home/disk/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 25:
    with gzip.GzipFile(fileobj=buf, mode='wb', compresslevel=gzip._COMPRESS_LEVEL_BEST, mtime=0.0) as f:
========================== [FAILED] Took 9.73 seconds ==========================

Environment                         Status    Duration
----------------------------------  --------  ------------
HappyModel_ES24TX_2400_TX_via_WIFI  FAILED    00:00:09.726
==================== 1 failed, 0 succeeded in 00:00:09.726 ====================

RX

Processing HappyModel_EP_2400_RX_via_WIFI (platform: espressif8266@3.2.0; board: esp8285-8285; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
UID bytes: 192,238,128,119,235,42

build flags: ['-D PLATFORM_ESP8266=1', '-D VTABLES_IN_FLASH=1', '-D PIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48', '-D CONFIG_TCPIP_LWIP=1', '-D BEARSSL_SSL_BASIC', '-O2', '-DTARGET_RX=1 -Wall -Iinclude', '-DRADIO_2400=1', '-include target/DIY_2400_RX_ESP8285_SX1280.h', '-DMY_BINDING_PHRASE="PASSWD"', '-DMY_UID=192,238,128,119,235,42', '-DLOCK_ON_FIRST_CONNECTION', '-DAUTO_WIFI_ON_INTERVAL="20"', '-DFAST_SYNC', '-DLATEST_COMMIT=53,99,52,56,48,56', '-DLATEST_VERSION=50,46,48,46,48', '-DTARGET_NAME=HAPPYMODEL_EP_2400_RX']

Building for ESP8266/ESP8285 Platform
AUTO_WIFI_ON_INTERVAL = ON
AttributeError: module 'gzip' has no attribute '_COMPRESS_LEVEL_BEST':
  File "/home/disk/.platformio/penv/lib/python3.6/site-packages/platformio/builder/main.py", line 179:
    env.SConscript(item, exports="env")
  File "/home/disk/.platformio/packages/tool-scons/scons-local-4.3.0/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/disk/.platformio/packages/tool-scons/scons-local-4.3.0/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/disk/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 59:
    build_common(env, "rx_index.html")
  File "/home/disk/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 47:
    build_html(mainfile, "INDEX_HTML", out, env)
  File "/home/disk/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 39:
    out.write(','.join("0x{:02x}".format(c) for c in compress(data.encode('utf-8'))))
  File "/home/disk/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 25:
    with gzip.GzipFile(fileobj=buf, mode='wb', compresslevel=gzip._COMPRESS_LEVEL_BEST, mtime=0.0) as f:
========================== [FAILED] Took 0.99 seconds ==========================

Environment                     Status    Duration
------------------------------  --------  ------------
HappyModel_EP_2400_RX_via_WIFI  FAILED    00:00:00.986
==================== 1 failed, 0 succeeded in 00:00:00.986 ====================

Hope someone can help me..
best rgds,
Jaap

**Comment by jurgelenas** [comment]
Hey @jaapf4fs, try flashing 2.x-maintenance branch. This issue is fixed there. Another option is to upgrade your Python version to 3.8.

**Comment by jaapf4fs** [comment]
python3.8 --version
Python 3.8.12
Didn't work either..

**Comment by jaapf4fs** [comment]
Just testing,
Target 2.0.0-RC1 and Target 2.0.0-RC2 are getting build just fine.
Target 2.0.0-RC3 and 2.0.0-RC4 are showing the error above like 2.0.0 does

**Comment by jurgelenas** [comment]
> Just testing,
> Target 2.0.0-RC1 and Target 2.0.0-RC2 are getting build just fine.
> Target 2.0.0-RC3 and 2.0.0-RC4 are showing the error above like 2.0.0 does

Use 2.x-maintenance branch.

**Comment by jaapf4fs** [comment]
How do I use the  2.x-maintenance branch?
Novice - sorry

**Comment by jaapf4fs** [comment]
I tried the 2.x-maintenance branch didn't work either...

**Comment by jaapf4fs** [comment]
What I tried so far
- Deleted the configurator
- checked the dependencies
- Updated to Python 3.8.12
- fresh install configurator
- Cleared the platformio dependencies
- Cleared the firmware files
- tried the 2.x-maintenance branch
Still the same error on RC3 RC4 and 2.0.0 :-(
rgds,
Jaap

**Comment by jurgelenas** [comment]
> What I tried so far
> 
> * Deleted the configurator
> * checked the dependencies
> * Updated to Python 3.8.12
> * fresh install configurator
> * Cleared the platformio dependencies
> * Cleared the firmware files
> * tried the 2.x-maintenance branch
>   Still the same error on RC3 RC4 and 2.0.0 :-(
>   rgds,
>   Jaap

What error message do you receive when flashing from 2.0 maintenance branch?

**Comment by jaapf4fs** [comment]
Build error
AttributeError: module 'gzip' has no attribute 'GzipFile':
  File "/home/disk/.platformio/penv/lib/python3.6/site-packages/platformio/builder/main.py", line 179:
    env.SConscript(item, exports="env")
  File "/home/disk/.platformio/packages/tool-scons/scons-local-4.3.0/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/disk/.platformio/packages/tool-scons/scons-local-4.3.0/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/disk/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 59:
    build_common(env, "rx_index.html")
  File "/home/disk/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 47:
    build_html(mainfile, "INDEX_HTML", out, env)
  File "/home/disk/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 39:
    out.write(','.join("0x{:02x}".format(c) for c in compress(data.encode('utf-8'))))
  File "/home/disk/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 25:
    with gzip.GzipFile(fileobj=buf, mode='wb', compresslevel=9, mtime=0.0) as f:
========================== [FAILED] Took 1.01 seconds ==========================
Environment                     Status    Duration
------------------------------  --------  ------------
HappyModel_EP_2400_RX_via_WIFI  FAILED    00:00:01.008
==================== 1 failed, 0 succeeded in 00:00:01.008 ====================

In the past there was something in python with fileobject instead of filename I can remember that gave the same problem, but that is a long time ago..

**Comment by jaapf4fs** [comment]
It's working on 2.x-maintenance branch, 
also on Target 2.0.0 when I change "compresslevel=gzip._COMPRESS_LEVEL_BEST" to "compresslevel=9" in the build_html.py file..
