### ISSUE TITLE
UNC paths are not supported.  Defaulting to Windows directory.

### ISSUE THREAD

**Issue by flyturbo** [ExpressLRS/ExpressLRS-Configurator#179]
Build error
'\\TS453mini\DataVol2\Drone Stuff\ExpressLRS\ExpressLRS-ELRS1.1.0_V1.0.1\src'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

Any way we can get it to build using UNC path? The network resource is mapped in windows (Z:\Drone Stuff\ExpressLRS\ExpressLRS-ELRS1.1.0_V1.0.1) not sure why it's giving those errors.

**Comment by jurgelenas** [comment]
Does build fail with this error message only?

```
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported. Defaulting to Windows directory.
```

**Comment by flyturbo** [comment]
Yes it fails only when building when files are placed on my NAS. If local, example C or D drive, it works like a charm!

**Comment by jurgelenas** [comment]
> Yes it fails only when building when files are placed on my NAS. If local, example C or D drive, it works like a charm!

Unlikely to be resolved. Please use regular storage when using ExpressLRS Configurator.
