### ISSUE TITLE
Add USE_DIVERSITY define

### ISSUE THREAD

**Issue by CapnBry** [ExpressLRS/ExpressLRS-Configurator#18]
ExpressLRS 1.0.0RC1 supports diversity receivers. I know the SIYI FM30 Mini RX does it, and there must be others because I didn't write the implementation. Targets appearing to support it:
* FM30_RX_MINI
* Frsky_RX_R9SLIMPLUS
* DIY_2400_RX_ESP8285_SX1280 (if the pad isn't used for a button?)

The define is `-DUSE_DIVERSITY`.  I'm not sure what the help text would be, maybe just "Enables receiver antenna switching diversity"?

This isn't a big deal that it isn't there, I wouldn't push a new release for it or anything, but it should be there for 1.0 final. Let me know if you need more information from me.

**Comment by sfjuocekr** [comment]
https://github.com/sfjuocekr/ExpressLRS-Configurator/commit/cf57157da98e330673450c11cd2d93b58af24bc9

I've added it, not sure if it belongs under performance options and if it should be enabled by default yes or no.

**Comment by jurgelenas** [comment]
> [sfjuocekr@cf57157](https://github.com/sfjuocekr/ExpressLRS-Configurator/commit/cf57157da98e330673450c11cd2d93b58af24bc9)
> 
> I've added it, not sure if it belongs under performance options and if it should be enabled by default yes or no.

I think it looks good. Can you submit a pull request for it?

**Comment by jurgelenas** [comment]
Fixed in https://github.com/ExpressLRS/ExpressLRS-Configurator/releases/tag/v0.4.14
