### ISSUE TITLE
DIY 900MHz ESP32 - Wifi flashing

### ISSUE THREAD

**Issue by FireflySoul** [ExpressLRS/ExpressLRS-Configurator#183]
I only see UART method available for flashing and was wondering, since the same ESP32 module is used as in 2.4GHz version, why can't flashing be done via wifi for 900MHz also?

**Comment by jurgelenas** [comment]
I have created an issue on the firmware repo for this: https://github.com/ExpressLRS/ExpressLRS/issues/1207

Once implemented there, will release support in the configurator :) Thanks for reporting this, @FireflySoul!
