### ISSUE TITLE
Build options not shown when reselecting target

### ISSUE THREAD

**Issue by FireflySoul** [ExpressLRS/ExpressLRS-Configurator#192]
## Expected Behavior

After target selection all applicable build options are shown.
## Current Behavior

When a device is selected twice in a row from the dropdown list most build options disappear.
## Steps to Reproduce

1. Choose a device from the dropdown list

2. Reopen the list and select the same device again

3. Most build options are not shown anymore (only flashing method still available)

## Your Environment

- Operating System and version: Win 10 
- TX hardware:
- RX hardware:

**Comment by jurgelenas** [comment]
Was able to confirm this bug. Thanks for reporting @FireflySoul!
