### ISSUE TITLE
Platformio error during compilation:  "The system cannot find the path specified."

### ISSUE THREAD

**Issue by spreck** [ExpressLRS/ExpressLRS-Configurator#199]
## Expected Behavior

.elrs file compiled

## Current Behavior

platformio error:

"The system cannot find the path specified."

build fails

## Steps to Reproduce

Install conda and then run ExpressLRS-Configurator

## Possible Solution (Not obligatory)
Solved by the following:

Delete AutoRun keys in your registry in:

Computer\HKEY_CURRENT_USER\Software\Microsoft\Command Processor
or
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor

per instructions here (https://www.tenforums.com/general-support/122582-cmd-terminal-starts-system-cannot-find-path-specified.html) found referenced here (https://github.com/platformio/platformio-vscode-ide/issues/69).

## Context

Solved issue but wanted to put it here in case anyone else has the same issue.

## Your Environment

Windows 10 with previous conda installation

- Operating System and version:
- TX hardware: FrSky R9
- RX hardware: FrSky R9

**Comment by jurgelenas** [comment]
Closing, since issues like this are going to be solved after migration to pre-built binaries.
