### ISSUE TITLE
FetchError: failed to get targets from ref: x.x.x

### ISSUE THREAD

**Issue by CodingPoeta** [ExpressLRS/ExpressLRS-Configurator#215]
## Expected Behavior

Get targets successfully 

## Current Behavior

Got FetchError, and only getTargets got FetchError.
<img width="1512" alt="Screenshot 2022-01-16 at 11 19 06 AM" src="https://user-images.githubusercontent.com/24382556/149645969-1b5c0d8c-271f-4826-b07e-f4abebe0c194.png">

I've already tried 1.3.3 and 1.3.2, this error exists both in these 2 versions.

## Steps to Reproduce

None

## Your Environment

curl the url seems fine
<img width="1440" alt="Screenshot 2022-01-16 at 11 22 11 AM" src="https://user-images.githubusercontent.com/24382556/149646024-abc660dc-41cb-4ffa-baa8-2b4d3cd2531f.png">

- Operating System and version: 
<img width="698" alt="Screenshot 2022-01-16 at 11 31 53 AM" src="https://user-images.githubusercontent.com/24382556/149646228-fdeaac85-d6cc-44b1-8de9-6a41eac63b64.png">

**Comment by LoakAudio** [comment]
@CodingPoeta , the web was weird and slow last night and several websites were unreachable (Betaflight and ELRS github were).
Now it seems OK, maybe you can have a new try.

**Comment by CodingPoeta** [comment]
![Screenshot 2022-01-16 at 5 47 33 PM](https://user-images.githubusercontent.com/24382556/149654939-b7970018-8d87-4187-8b84-acc195e50ca7.png)


> @CodingPoeta , the web was weird and slow last night and several websites were unreachable (Betaflight and ELRS github were). Now it seems OK, maybe you can have a new try.

Have tried lots of time but still got this error.

I've even run it in debug mode with the master src code.

It looks like stuck in async function `fetch`.

So I tried to fetch the same url with a simple nodejs code to avoid environment problems, nothing went wrong.

BTW, since 4 or 5 days ago when I first time tried to use it, the Error bothers me very very often( actually It only behaves normally twice )

**Comment by LoakAudio** [comment]
Ok, it is better to wait for an administrator to answer you since everything is back to normal for me.
 Good luck

**Comment by justinlampley** [comment]
There was another person having a very similar issues with network timeouts, https://github.com/ExpressLRS/ExpressLRS-Configurator/issues/120#issuecomment-965219118.  Since it is a network issue, there isn't much we can currently do about it.  

One way to work around it is to download the ExpressLRS source code and use the Local firmware source option in the configurator, while not the most convenient, it will work.  Something else you may try is a VPN.

**Comment by CodingPoeta** [comment]
> There was another person having a very similar issues with network timeouts, [#120 (comment)](https://github.com/ExpressLRS/ExpressLRS-Configurator/issues/120#issuecomment-965219118). Since it is a network issue, there isn't much we can currently do about it.
> 
> One way to work around it is to download the ExpressLRS source code and use the Local firmware source option in the configurator, while not the most convenient, it will work. Something else you may try is a VPN.
> 
> Edit: I just noticed you were in China, if you are behind the great firewall, there is nothing we can do about that right now since the configurator relies on accesses to GitHub. See the whole discussion here: #120

yes, I have my VPN

The problem is that: 
- I can `curl ***` successfully 
- I've wrote a small program in ts to fetch the `platformio.ini`, and also successfully

Since only in elrs-configurator I will get this problem, I think there must be some problem in it.
I have tried to find out the cause, but I don't know much about nodejs and ts, so...

**Comment by jurgelenas** [comment]
It is network issue for sure.

New way of fetching targets using git instead of http might fix your issue if #231  gets merged :)

**Comment by CodingPoeta** [comment]
> It is network issue for sure.
> 
> New way of fetching targets using git instead of http might fix your issue if #231 gets merged :)

nice

**Comment by jurgelenas** [comment]
@CodingPoeta can you please try this nightly release? https://github.com/ExpressLRS/ExpressLRS-Configurator-Nightlies/releases/tag/v20220204.67723.0

I have made some changes that might help you.

**Comment by CodingPoeta** [comment]
> @CodingPoeta can you please try this nightly release? https://github.com/ExpressLRS/ExpressLRS-Configurator-Nightlies/releases/tag/v20220204.67723.0
> 
> I have made some changes that might help you.

It works fine now, thanks!
