### ISSUE TITLE
Missing R9 Slim targets

### ISSUE THREAD

**Issue by CapnBry** [ExpressLRS/ExpressLRS-Configurator#22]
More of a feature than a bug report I guess, but the R9 Slim targets aren't available in the configurator. The environment names are:
* Frsky_RX_R9SLIM_via_STLINK
* Frsky_RX_R9SLIM_via_BetaflightPassthrough

**Comment by jurgelenas** [comment]
Fixed in 0.5.1. Thanks @CapnBry for reporting this! :)

**Comment by CapnBry** [comment]
You're the best, thanks!
