### ISSUE TITLE
Bind phrase is NOT a secret

### ISSUE THREAD

**Issue by CapnBry** [ExpressLRS/ExpressLRS-Configurator#227]
I've noticed that in the latest Configurator, the Bind Phrase is in a password hidden field. "Implement sensitive device options support" #171

# The binding phrase is not a secret

Binding phrase is used as a seed to prevent your ELRS from colliding with someone else's ELRS, **NOT** as a security feature. Please see our documentation [FAQ: Is my binding phrase a secret?](https://www.expresslrs.org/2.0/faq/#is-my-binding-phrase-a-secret). 

Making this a password-type field perpetuates the myth that this is some sort of security when it provides **zero** security. Your binding phrase hash is trivially reversible from OTA in under a second. This is not security, it is to prevent collisions with others and therefore should be considered public information.

The wifi SSID and password of course is sensitive information. The binding phrase is not.

**Comment by jurgelenas** [comment]
This is a feature requested by the community. There is an option to turn off the binding phrase hiding which is persistent across app launches.

**Comment by CapnBry** [comment]
The community needs to become educated that binding phrase is not a secret, which is why they requested it be hidden. We must not hide it, because hiding it only perpetuates this myth.

### What's the harm?
If it is hidden, when a user submits a screenshot of their settings for support, if the binding phrase is hidden we can not tell if maybe they set it to 1234 or ELRS and therefore could have had a collision with another pilot. We also can't tell if the bind phrase generates a problem with our build process that somehow causes the UID to not be set properly.

It is really important that users understand that bind phrase is not sensitive information, so I feel strongly that treating it as sensitive information must be stopped.

**Comment by brandonrc** [comment]
Dammit that is a good point @CapnBry

**Comment by CapnBry** [comment]
After a discussion on discord, I agree that there is merit to being able to hide the binding phrase, especially for youtubers who do instructional videos and may later run into someone who used the same bind phrase as in their video.

Instead I've asked for the tooltip to be changed to indicate that the binding phrase does not provide security at all. Thanks for talking it out with me @jurgelenas
