### ISSUE TITLE
Jumper Aion unit doesn’t flashed with WiFi

### ISSUE THREAD

**Issue by SunjunKim** [ExpressLRS/ExpressLRS-Configurator#246]
## Expected Behavior
When upload by WiFi -> Build&Flash an Aion TX unit, when the message says `Success!`, it should be flashed.

## Current Behavior
When upload by WiFi -> Build&Flash an Aion TX unit (possibly Aion RX as well), the message says `Success!` but it's actually not.

## Steps to Reproduce

1. You'll need a stock Jumper Aion firmware (fresh unit from the new package)
2. Flash with 2.2 Jumper Aion target
3. `Success!` message is shown, with the following error message in the log
```
...
 83 1149k    0     0   83  960k      0  63014  0:00:18  0:00:15  0:00:03 62266
 89 1149k    0     0   89 1024k      0  62948  0:00:18  0:00:16  0:00:02 62045
 94 1149k    0     0   94 1088k      0  62978  0:00:18  0:00:17  0:00:01 62370
100 1149k    0     0  100 1149k      0  62807  0:00:18  0:00:18 --:--:-- 49922
100 1149k    0     0  100 1149k      0  59599  0:00:19  0:00:19 --:--:-- 49855
100 1149k  100   206  100 1149k     10  59285  0:00:20  0:00:19  0:00:01 45635
{"status": "mismatch", "msg": "<b>Current target:</b> DIY_2400_TX_ESP32_SX1280_E28.<br><b>Uploaded image:</b> JUMPER_AION_NANO_2400_TX.<br/><br/>Flashing the wrong firmware may lock or damage your device."}
** UPLOAD SUCCESS. Flashing in progress.
** Please wait for LED to resume blinking before disconnecting power
======================== [SUCCESS] Took 125.61 seconds ========================

Environment                        Status    Duration
---------------------------------  --------  ------------
Jumper_AION_NANO_2400_TX_via_WIFI  SUCCESS   00:02:05.614
========================= 1 succeeded in 00:02:05.614 =========================
```

## Possible Solution (Not obligatory)
As Jumper Aion units were initially shipped with DIY targets, the new Aion target will spit out a "firmware mismatch" error.
Within the WebUpdater interface, there will be a popup window for `Flash Anyway` however it's omitted in Configurator, and just says `Success!` which is misleading a user.

When this message appears, the Configurator also has to give an option like "force flash the firmware".

## Context
This will confuse Jumper Aion users when they try ELRS flashing for the first time.

## Your Environment

- TX hardware: Jumper Aion TX

**Comment by CapnBry** [comment]
Yeah I dunno how they can do it, but it would be nice if it detected the error message and gave the user the nice choice like the webui does. I can change the build process so the HTTP result is saved to a file in the output directory (`firmware-output.json`)
```
{"status": "ok", "msg": "Update complete. Please wait for LED to resume blinking before disconnecting power."}
```
And the Configurator can parse the JSON to do the same thing as the webui?

**Comment by CapnBry** [comment]
![image](https://user-images.githubusercontent.com/677183/151592668-0578d57a-f2c1-48ad-9b9a-5006d4cbed70.png)

This is what our output will look like, but the JSON will be in a file as well. Will this work for you guys, @jurgelenas and @justinlampley ? The other statuses are "mismatch" (with a HTML-formatted message) and "error"

**Comment by jurgelenas** [comment]
> ![image](https://user-images.githubusercontent.com/677183/151592668-0578d57a-f2c1-48ad-9b9a-5006d4cbed70.png)
> 
> This is what our output will look like, but the JSON will be in a file as well. Will this work for you guys, @jurgelenas and @justinlampley ? The other statuses are "mismatch" (with a HTML-formatted message) and "error"

I don’t like the idea of this file based integration approach. I think firmware build process should detect if shell is interactive or not and on target mismatch it should fail with -1 exit code.

Then we could add some way to ignore mismatched targets on the configurator side :)

**Comment by CapnBry** [comment]
Well I mean it is always just going to fail, but I thought it would be a lot more useful to have the actual status in a formatted file as a JSON object instead of just having the user read the log window.

Doesn't the Configurator already ignore mismatched targets without making any changes? Is that the joke? 😆

**Comment by CapnBry** [comment]
Yeah the current code doesn't inspect the return value from the web server, it only checks the return value from curl which indicates success. I've changed it so anything other than status==ok in the JSON throws the upload failed message and return code, just like if it couldn't even connect. Is that all you guys need?

I'll still put out the file as well, since maybe there's some other integration possible you might discover. I don't know if the Configurator needs to actually do the upload (since the PIO process will also flash bootloaders and stuff too if asked to), but that would certainly give you more control over the progress and return value and be able to retry. I'm not sure it would be easy to add a force option to the PIO upload since it is just calling the default "upload" function to perform the action, and there's no parameters other than the environment.

**Comment by justinlampley** [comment]
Yes, exiting with a non-zero value will make the configurator show Failure instead of Success.

Does the PIO process flash the bootloaders over WIFI or does that only occur when flashing via UART?

**Comment by CapnBry** [comment]
The wifi upload process can optionally upload a bootloader, but those are only used for STM32 targets when flashing through the backpack.

I've created a PR that will return an error code if the process fails at the application layer, -1 for those, or the non-zero error code returned by curl if the upload itself fails. I'm also dropping a file with the JSON returned if there was any, in case anyone cares to do anything with that.
https://github.com/ExpressLRS/ExpressLRS/pull/1371

**Comment by CapnBry** [comment]
I just realized that this will be a problem on the Zoro Target too since it runs DupleTX and there's an actual zorro target that might be used and will have the same issue as the Aion

**Comment by jurgelenas** [comment]
Thanks @SunjunKim. Primary issue of display success when it actually failed is resolved in master now. Will continue work on this in https://github.com/ExpressLRS/ExpressLRS-Configurator/issues/250
