### ISSUE TITLE
platformi server down

### ISSUE THREAD

**Issue by haberflave** [ExpressLRS/ExpressLRS-Configurator#247]
Getting an error while trying to flash. 
Error: HTTPSConnectionPool(host='api.registry.ns1.platformio.org', port=443): Max retries exceeded with url: /v3/search?query=type%3A%22platform%22+name%3A%22espressif32%22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10f380190>, 'Connection to api.registry.ns1.platformio.org timed out. (connect timeout=10)'))

Is this simply due to platformio server issues?

**Comment by jurgelenas** [comment]
Yes. Temporal issues.
