### ISSUE TITLE
Target for FrSky Vantac 900mHz tx module

### ISSUE THREAD

**Issue by pfreundl** [ExpressLRS/ExpressLRS-Configurator#249]
Hi,

i'd like to flash my newly aquired FrSky Vantac 900mHz module, and i cant find a target for it. It seems like it is just a r9m lite, but im not sure and dont want to brick it.

Thank you :)

banggood link:

https://www.banggood.com/FrSky-VANTAC-ExpressLRS-ELRS-2_4GHz-915MHz-or-868MHz-Long-Range-Micro-TX-Module-for-RC-Drone-p-1925149.html?cur_warehouse=CN&ID=6310754

**Comment by pfreundl** [comment]
nevermind, i just saw that the housing is different from the product pictures, i think they just sent me an r9 mini with elrs flashed. this is going to be a fun discussion.

**Comment by jurgelenas** [comment]
I am not aware about Vantac 915/868 MHz modules. Only the 2.4 GHz ones: https://github.com/ExpressLRS/ExpressLRS/blob/master/src/targets/vantac_2400.ini

**Comment by jurgelenas** [comment]
@pfreundl I will close the issue for now since this appears like an error in banggood.com product listing.
