### ISSUE TITLE
Add ESP Backpack Target

### ISSUE THREAD

**Issue by techfixpros** [ExpressLRS/ExpressLRS-Configurator#25]
Please add the ESP backpack as a target.

**Comment by CapnBry** [comment]
why?

**Comment by techfixpros** [comment]
So there is no need to use vscode at all to build firmware. In my case, something is wrong with vs code and I can no longer build the backpack sources, but can build any of the rx/tx sources without issue. Removing the git directory and starting with a fresh clone, updating vscode/pio, reinstalling vscode/pio are not resolving.

Isn't the configurator supposed to eliminate the need for a user to set up the build environment in vscode/pio...?

**Comment by CapnBry** [comment]
But the only purpose of the ESP backpack is to flash firmware to the actual device, and every device has a way of flashing the firmware already and comes with the ESP backpack already flashed (unfortunately). There's zero purpose for changing it unless you're developing new software for the backpack, in which case you'd be flashing it with PIO.

**Comment by techfixpros** [comment]
You're right, although no one responded on discord to my request for info if they are having problems building firmware for the backpack. My use case is I already flashed one esp12f a while back, and now have another that I wanted to flash as well and now am unable to.

Thanks for the response.
