### ISSUE TITLE
Add support for uploadforce param when flashing

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/ExpressLRS-Configurator#250]
See: https://github.com/ExpressLRS/ExpressLRS/pull/1371/files

I was thinking it might be possible to use [Split button](https://mui.com/components/button-group/#split-button) component to replace existing "BUILD & FLASH" button or we could just simply add "Force upload" checkbox nearby.

**Comment by justinlampley** [comment]
For reference: https://github.com/ExpressLRS/ExpressLRS/pull/1371
