### ISSUE TITLE
Add frsky vantac 915/868 targets

### ISSUE THREAD

**Issue by trzeciuzytkownik** [ExpressLRS/ExpressLRS-Configurator#258]
For frysky vantac receivers 915/868MHz

**Comment by pkendall64** [comment]
As far as the devs are aware, there is no 900Mhz version of the ELRS devices.

**Comment by trzeciuzytkownik** [comment]
![IMG_20220203_094750](https://user-images.githubusercontent.com/98913871/152309910-f2f372b6-9173-4357-9b9e-36c94e296224.jpg)
![IMG_20220203_094516](https://user-images.githubusercontent.com/98913871/152309966-ccdab6c5-0aaf-4b31-8913-2eac04934957.jpg)

Those are the ones. Looks similar to r9mm.

**Comment by jurgelenas** [comment]
Closing, since these are just another brand name for existing hardware.
