### ISSUE TITLE
Ubuntu 18.04 does not run ExpressLRS Configurator v0.5.1

### ISSUE THREAD

**Issue by mdj36** [ExpressLRS/ExpressLRS-Configurator#26]
On ubuntu 18.04 does not starts ExpressLRS Configurator v0.5.1.
Please fix it.

**Comment by jurgelenas** [comment]
@mdj36 can you run `expresslrs-configurator` in your terminal and post the output? I am using Ubuntu while developing it so it is surprising that it does not work for you

**Comment by mdj36** [comment]
expresslrs-configurator 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.e0Fee2)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/opt/ExpressLRS Configurator/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/ExpressLRS Configurator/resources/app.asar/node_modules/@serialport/bindings/lib/linux.js:2:36)
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)

**Comment by mdj36** [comment]
maybe it will help...

**Comment by mdj36** [comment]
0.4.14 works fine but newer versions does not start.

**Comment by pitts-mo** [comment]
I can confirm v0.5.1 does not run on lubuntu 18.04.5

detail:
fresh install with all updates including held back.
sudo apt-get install git gconf2 gconf-service
sudo dpkg -i expresslrs-configurator_0.5.1_amd64.deb

After my run attempt reported error on glibc6 I checked "ls -l /lib/x86_64-linux-gnu/libc.so.6" to find libc-2.27.so.

I was unable to find a libc6 >= 2.28 from a trust-able source that would install without error.

My next thought is update your OS?

Sorry that I could not find a simple trustworthy fix.
-p

**Comment by jurgelenas** [comment]
Will try building it with support for older glib versions today / tomorrow :) Stay tuned.

**Comment by jurgelenas** [comment]
The most likely solution will be downgrading ubuntu version in expresslrs configurator [ci environment](https://github.com/ExpressLRS/ExpressLRS-Configurator/blob/09dbfe911efa9f4e5383cb632d4a5f3746a09751/.github/workflows/publish.yml#L13).

**Comment by mdj36** [comment]
Would be great to have working configurator before next stable or rc realease of Express lrs :)

**Comment by mdj36** [comment]
Anyway really great job @jurgelenas for user friendly configurator.

**Comment by jurgelenas** [comment]
@mdj36, @pitts-mo please test https://github.com/ExpressLRS/ExpressLRS-Configurator/releases/tag/v0.5.2

I am pretty sure it will work for you. If all is good please let me know and close the issue :)

**Comment by pitts-mo** [comment]
So @jurgelenas 
The expresslrs-configurator v0.5.2 can now be launched in lubuntu 18.04.5. However, The configurator appears unhappy with the installed python 3.6.9. 

{
  context: {
    stderr: 'Error: The Python 3.6.9 (/usr/bin/python3) interpreter is not compatible.\n' +
      'Reason: Could not find distutils module\n',
    stdout: ''
  },
  stack: [ undefined ],
  level: 'error',
  message: 'python dependency check error'
}

Python 3.6.9 is the installed version and the brief impression When attempting to update python3 or python in various ways it appeared that getting updated versions of python or libc6 running in 18.04 is not trivial.

I personally do not need 10 run the configurator in 18.04 and do not really wish to re-install 18.04 again.

But I will keep an eye on this issue.
-p

**Comment by mdj36** [comment]
Thanks works fine on Ubuntu 18.04.5. Great job!

**Comment by pitts-mo** [comment]
I have made a new attempt on a fresh lubuntu 18.04.5 install. However, it seems I am still missing a git related dependency and my attempts to build for R9M TX fail with the error below.  For now I am adding my notes here. Will take another look later.
-p

lubuntu 18.04.5 with all updates.
sudo apt-get install git gconf2 gconf-service
sudo dpkg -i expresslrs-configurator_0.5.2_amd64.deb 
sudo apt-get install python3-distutils

  context: {
    err: n [Error]: git: 'sparse-checkout' is not a git command. See 'git --help'.
    
        at Object.action (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2489346)
        at t.PluginStore.exec (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2490310)
        at /opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2502006
        at new Promise (<anonymous>)
        at t.GitExecutorChain.handleTaskData (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2501892)
        at t.GitExecutorChain.<anonymous> (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2501469)
        at Generator.next (<anonymous>)
        at a (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2499822)
        at processTicksAndRejections (internal/process/task_queues.js:93:5) {
      task: {
        commands: [ 'sparse-checkout', 'set', 'src' ],
        format: 'utf-8',
        parser: [Function: parser]
      }
    }
  },
  stack: [ undefined ],
  level: 'error',
  message: 'generic error'
}

**Comment by jurgelenas** [comment]
I will experiment if I can specify required Python & Git versions during install.

**Comment by jurgelenas** [comment]
> I have made a new attempt on a fresh lubuntu 18.04.5 install. However, it seems I am still missing a git related dependency and my attempts to build for R9M TX fail with the error below. For now I am adding my notes here. Will take another look later.
> -p
> 
> lubuntu 18.04.5 with all updates.
> sudo apt-get install git gconf2 gconf-service
> sudo dpkg -i expresslrs-configurator_0.5.2_amd64.deb
> sudo apt-get install python3-distutils
> 
> context: {
> err: n [Error]: git: 'sparse-checkout' is not a git command. See 'git --help'.
> 
> ```
>     at Object.action (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2489346)
>     at t.PluginStore.exec (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2490310)
>     at /opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2502006
>     at new Promise (<anonymous>)
>     at t.GitExecutorChain.handleTaskData (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2501892)
>     at t.GitExecutorChain.<anonymous> (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2501469)
>     at Generator.next (<anonymous>)
>     at a (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2499822)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
>   task: {
>     commands: [ 'sparse-checkout', 'set', 'src' ],
>     format: 'utf-8',
>     parser: [Function: parser]
>   }
> }
> ```
> 
> },
> stack: [ undefined ],
> level: 'error',
> message: 'generic error'
> }

Basically git version is just too old that is available with Ubuntu 18.04. I can't really specify that from electron.js deb build config.

To install newer git you have to:

```
sudo add-apt-repository ppa:git-core/ppa
sudo apt update
sudo apt install git
```

**Comment by jurgelenas** [comment]
> I have made a new attempt on a fresh lubuntu 18.04.5 install. However, it seems I am still missing a git related dependency and my attempts to build for R9M TX fail with the error below. For now I am adding my notes here. Will take another look later.
> -p
> 
> lubuntu 18.04.5 with all updates.
> sudo apt-get install git gconf2 gconf-service
> sudo dpkg -i expresslrs-configurator_0.5.2_amd64.deb
> sudo apt-get install python3-distutils
> 
> context: {
> err: n [Error]: git: 'sparse-checkout' is not a git command. See 'git --help'.
> 
> ```
>     at Object.action (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2489346)
>     at t.PluginStore.exec (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2490310)
>     at /opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2502006
>     at new Promise (<anonymous>)
>     at t.GitExecutorChain.handleTaskData (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2501892)
>     at t.GitExecutorChain.<anonymous> (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2501469)
>     at Generator.next (<anonymous>)
>     at a (/opt/ExpressLRS Configurator/resources/app.asar/main.prod.js:14:2499822)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
>   task: {
>     commands: [ 'sparse-checkout', 'set', 'src' ],
>     format: 'utf-8',
>     parser: [Function: parser]
>   }
> }
> ```
> 
> },
> stack: [ undefined ],
> level: 'error',
> message: 'generic error'
> }

@pitts-mo let me know if my git fix from above combined with manually installing python distuils results in working configurator app:

```
sudo add-apt-repository ppa:git-core/ppa
sudo apt update
sudo apt install git
sudo apt-get install python3-distutils
```

**Comment by pitts-mo** [comment]
Yes @jurgelenas , installing git from that ppa did allow me to build R9M TX in lubuntu 18.04.5 without error :-)
Thank you,
-p

To summarize my lubuntu 18.04.5 test history shows these major actions:
-make sure 18.04.5 is up to date

-satisfy the dependency warnings of expresslrs-configurator_0.5.2_amd64.deb with: 
sudo apt-get install git gconf2 gconf-service

sudo apt-get install python3-distutils

sudo add-apt-repository ppa:git-core/ppa
sudo apt update
sudo apt install git

**Comment by jurgelenas** [comment]
Thanks @pitts-mo.

I have added your notes in [https://github.com/ExpressLRS/ExpressLRS-Configurator/commit/1a446f8191a697eeda310f3effda6d5757b6f0df](https://github.com/ExpressLRS/ExpressLRS-Configurator/commit/1a446f8191a697eeda310f3effda6d5757b6f0df).

Will close the issue.
