### ISSUE TITLE
ExpressLRS configurator v1.3.6 - Usage: platformio [OPTIONS] COMMAND [ARGS]... Try 'platformio -h' for help. Error: No such command "run"

### ISSUE THREAD

**Issue by RCPOINT** [ExpressLRS/ExpressLRS-Configurator#267]
## Expected Behavior
I am using the ExpressLRS configurator
Version 1.3.4 - OK
Version 1.3.5 - OK
I upgraded to version 1.3.6 and have a problem creating firmware -
Usage: platformio [OPTIONS] COMMAND [ARGS]...
Try 'platformio -h' for help.
Error: No such command "run"
I can't find the answer on the forum. This error is for the ExpressLRS module and for the ExpressLRS receiver.
Versions 1.3.4 and 1.3.5 did not have this problem. I tried to rollback to version 1.3.5. It didn't work!

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- Operating System and version: WIN 7 64bit
![1](https://user-images.githubusercontent.com/98458289/152741461-3c31eea9-5ca8-4fe2-b4ea-6c2ef989ce08.png)

- TX hardware: NamimnoRC FLASH 2400 OLED TX
- RX hardware: ep24

**Comment by jurgelenas** [comment]
Thanks for reporting this @RCPOINT, but Windows 7 is not supported by Microsoft anymore. Same policy for ExpressLRS Configurator.

I am going to close the issue.
