### ISSUE TITLE
Please add GEPRC 2.4GHz/900MHz RX

### ISSUE THREAD

**Issue by x4FF3** [ExpressLRS/ExpressLRS-Configurator#272]
Hello,

i was approached by GEPRC to add their two RXs to the configurator. Talked to CapnBry on discord about it. I will tell GEPRC to provide samples for devs. 

Shop-Link: https://geprc.com/product/geprc-elrs-nano-receiver/

i added this for testing locally: 
```
{
        "category": "GEPRC 2.4 GHz",
        "name": "GEPRC ELRS Nano 2.4 RX",
        "wikiUrl": "",
        "abbreviatedName": "GEPRC RX24",
        "verifiedHardware": false
}
```
and
```
{
        "category": "GEPRC 900 MHz",
        "name": "GEPRC ELRS Nano 900 RX",
        "wikiUrl": "",
        "abbreviatedName": "GEPRC RX900",
        "verifiedHardware": false
}
```

thanks in advance

KR
David

**Comment by jurgelenas** [comment]
Added in #327
