### ISSUE TITLE
ExpressLRS Configurator fails to build Version 2.2

### ISSUE THREAD

**Issue by Bambusgott** [ExpressLRS/ExpressLRS-Configurator#276]
## Expected Behavior

Version 2.2 builds automatically like Version 2.1.

## Current Behavior

I expirience a build error with the current Configurator 1.3.7 if i try to build any Tx or Rx target in Version 2.2. 
The build error states:
>>>  WARNING: The wheel package is not available.
>>> error: subprocess-exited-with-error
>>>  python setup.py bdist_wheel did not run successfully.
>>> ...
>>> invalid command 'bdist_wheel'

I attached my full log file to provide the full output.

Version 2.1 builds fine as usual.

## Steps to Reproduce

1. Select any target for Version 2.2
2. Press build
3.  Build error occurs after about 8 seconds

## Possible Solution (Not obligatory)

I am only a user. So I have no idea unfortunately.
I reinstall the configurator - that didn't help.

## Context

Just downloaded the windows version 'ExpressLRS-Configurator-Setup-1.3.7.exe' and installed it.

## Your Environment

- Operating System and version: Windows 10 Pro
- TX hardware: NamimnoRC FLASH 2400 TX and Jumper AION T-Pro 2400 TX
- RX hardware: many different

## Log-file
[expressslrs-configurator.log](https://github.com/ExpressLRS/ExpressLRS-Configurator/files/8055195/expressslrs-configurator.log)

## Thank you for your help
:-)

**Comment by L1cardo** [comment]
Same here, I tried  Configurator 1.3.7 and 1.3.8, can not build 2.2 either.
And 1.3.6 is fine.
[expressslrs-configurator-log.zip](https://github.com/ExpressLRS/ExpressLRS-Configurator/files/8058405/expressslrs-configurator-log.zip)

**Comment by Bambusgott** [comment]
Fixed in Version 1.3.8.
Probably correlated to [#370](https://github.com/ExpressLRS/ExpressLRS-Configurator/pull/277)

**Comment by jurgelenas** [comment]
Awesome!
