### ISSUE TITLE
[Solved] Can not build any TX firmwares on macOS 12.3

### ISSUE THREAD

**Issue by L1cardo** [ExpressLRS/ExpressLRS-Configurator#278]
## Summary
Hi. I was able to build any RX and TX firmwares on my M1 Mac mini a couple days ago, but I can't build any TX targets today, while all RX targets are good.
I don't know what happened to my Mac.
The error log says something about `tried: '/opt/osxcross/target/bin/../x86_64-apple-darwin12/lib/libstdc++.6.dylib' (no such file)`, but I don't event have the directory `tried: '/opt/osxcross`

The only thing I can think of is, is this because I am running a macOS beta version?

Configurator: 1.3.8
Mac: Mac mini (M1, 2020)
OS: 12.3 Beta(21E5206e)

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/33802186/153818312-37fae834-b441-4587-8e90-8a6c9f35f357.png">

[expressslrs-configurator-log.zip](https://github.com/ExpressLRS/ExpressLRS-Configurator/files/8058709/expressslrs-configurator-log.zip)

Help me to find what is wrong with my environment.

**Comment by L1cardo** [comment]
Solved！
This is a macOS issue, I downgraded to macOS 12.2, and this problem solved.

**Comment by jurgelenas** [comment]
> 

Thanks!
