### ISSUE TITLE
A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header

### ISSUE THREAD

**Issue by kolole** [ExpressLRS/ExpressLRS-Configurator#282]
## Expected Behavior

Flashing completes, after udev settings as recommended in the build guide

## Current Behavior

Flashing fails with this target:
HappyModel_ES24TX_Pro_Series_2400_TX_via_UART 

The title describes the error message

## Steps to Reproduce
Follow guide for Linux flashing/installation, and it fails

1.

2.

3.

4.

## Your Environment

- Operating System and version: Ubuntu 20.05
- TX hardware: Happymodel 2.4 Slim Pro (ES24TX SLIM PRO)
- RX hardware:

**Comment by jurgelenas** [comment]
Please post this issue in ExpressLRS discord #help-and-support channel.
