### ISSUE TITLE
cant update via USB with configurator. 

### ISSUE THREAD

**Issue by stavi58** [ExpressLRS/ExpressLRS-Configurator#286]
## Summary

 when I try to update my Express LRS with the configurator I keep getting this error message. I've selected serial debug, downloaded appropriate drivers and make sure I've selected EdgeTX passthrough for flashing method. 
![Screenshot (1)](https://user-images.githubusercontent.com/78782030/155628219-5d1465e8-3dbe-4a03-b1c5-2592e6aa811b.png)

**Comment by jurgelenas** [comment]
Please seek help in ExpressLRS Discord #help-and-support channel.
