### ISSUE TITLE
After build, give "firmware.bin" a meaningful filename

### ISSUE THREAD

**Issue by richardbulger** [ExpressLRS/ExpressLRS-Configurator#29]
The only useful artifact to the end user after building the firmware in the firmware.bin file.
It seems, the first thing to do when the firmware is built is rename the bin file to something meaningful, such as HappyModel_EP_2400_RX_via_WIFI.bin, and move it to another folder for safe keeping. All the instructional youtube videos I have seen seem to do the same thing.

It would be good if:
1. File was named according to target (eg HappyModel_EP_2400_RX_via_WIFI.bin)
2. A "save file" prompt was shown after build so user could choose file location (alternatively this could be a field in the build config GUI)

**Comment by jurgelenas** [comment]
That is a good idea, will add this in future releases :)

**Comment by jurgelenas** [comment]
Fixed by @justinlampley in https://github.com/ExpressLRS/ExpressLRS-Configurator/pull/36
