### ISSUE TITLE
skip esp flashing

### ISSUE THREAD

**Issue by hosein-gh** [ExpressLRS/ExpressLRS-Configurator#295]
## Summary

im trying to flash a diy 20x20 900mhz rx and i don't want to solder an esp01f on it so is there any way to tell configurator to skip esp flashing ? because im getting error while flashing without esp01f soldered on pcb

**Comment by jurgelenas** [comment]
There is nothing else left to flash on your receiver if you do not solder esp. That esp module is what runs the expresslrs code.
