### ISSUE TITLE
Happymodel AIO 2G4 FC: only 500Hz works

### ISSUE THREAD

**Issue by nablabla** [ExpressLRS/ExpressLRS-Configurator#31]
## Expected Behavior

I want to use slower packet rates to get more range. With the EP1/2 you can just change the Packet rate on the radio and it works like a charm, receiveivers go along.

## Current Behavior
It all works perfectly if I select 500Hz on the transmitter. But when I switch to any other choice ther are no control inputs. I read somewhere that you need to set it to 500Hz to bind it. But then it is stuck at that Frequency. It is indeed not possible to bind in any sub500Hz mode.

## Steps to Reproduce
Bind to your AIO Happymodel AIO 2G4 FC
Select 250Hz on your radio -> no link
OR: Try to bind in 250Hz -> no success

## Context
lower packet rates give better range

## Your Environment

I am using Taranis QX7 with Happymodel 2G4 ELRS board
and the 2G4 ELRS AIO FC V1.0

**Comment by JyeSmith** [comment]
With the stock firmware you will need to change it in the cli using expresslrs_rate_index.

Updating to the hex in the PR means it will now cycle on power up and connect to any RF mode.

https://github.com/betaflight/betaflight/pull/10788

**Comment by nablabla** [comment]
what is PR?
"Updating to the hex in the PR " <- i want to do that, but i don't understand

**Comment by JyeSmith** [comment]
Don't update if you don't know how to.

set expresslrs_rate_index = 1
save

This is for 250hz.

**Comment by nablabla** [comment]
It would be better if it was switchable.
The article you linked also talks about PRs, what does PR stand for?
Is there anyway to find out how to pudate? a forum entry or instructions? I would like to learn

**Comment by tmolteno** [comment]
A PR is a "Pull Request". It refers to a group of code changes that have been contributed by someone (usually for some specific feature - in this case ExpressLRS support). On github, pull-requests are referred to by numbers. You can view all the current pull requests by  clicking on the "Pull Requests" tab. The ExpressLRS PR is (https://github.com/betaflight/betaflight/pull/10788)

**Comment by nablabla** [comment]
I know what a pull request is, just abbreviations are hell. Thank you very much! Looking >> to the next release

**Comment by jurgelenas** [comment]
Thanks for reporting that, but will close the issue since it is not directly related to the configurator application. I hope this will be tracked on  betaflight/betaflight#10788.
