### ISSUE TITLE
ES868Mhz

### ISSUE THREAD

**Issue by chemata** [ExpressLRS/ExpressLRS-Configurator#32]
Hi, I'm new to this world, very good job.
Is it very difficult to separate the 868mHz frequency from 915mHz or 900mHz? Every day it gets more complicated. I think it would be good to differentiate it.
Thank you so much

**Comment by jurgelenas** [comment]
Could you please elaborate on what do you mean "separating 868mhz / 915mhz frequencies"? Where it is complicating? Choosing correct device target? Select correct operating frequency for your 868/915 mhz hardware?

**Comment by chemata** [comment]
No, it is not a real problem. But according to Happymodel, the hardware is the same for 915mHz, 900mHz and 868mHz. He says he only changes the Software and the antenna.
As you have now differentiated 915mHz and 900mHz, I was wondering why you have not also separated the 868mHz.
But it's not a problem, you do a very good job, I appreciate it.

**Comment by jurgelenas** [comment]
We do not really separate 915mhz/900mhz/868mhz/866mhz since as you said TX/RX hardware is the same, the only difference is in the antennas and software configuration when flashing.
