### ISSUE TITLE
Targets for SPI based receivers pointing to the documentation on SPI receivers

### ISSUE THREAD

**Issue by commanderguy3001** [ExpressLRS/ExpressLRS-Configurator#323]
As the Title already states, I'd love to have targets for SPI based receivers.

Many People still are confused by SPI receivers and don't understand what target to take for them in the configurator (none, update betaflight !), and so they come to the discord and complain there.

This is an issue that could be mitigated relatively easily by having targets for every SPI based elrs receiver board, and instead of showing the normal configuration options it just references to https://www.expresslrs.org/2.0/hardware/spi-receivers/ to let the people know what to really do.

I also think this would possibly remove quite a bit of confusion, and workload on the people in the discord.

**Comment by jurgelenas** [comment]
I think it would be hard to make this discoverable easily for clueless users. To add SPI receivers would require us to track releases of every flight controller with SPI based receiver and add it to the configurator. That would add an unnecessary burden of maintenance, in my opinion.
