### ISSUE TITLE
WikiURL Updates

### ISSUE THREAD

**Issue by deadbytefpv** [ExpressLRS/ExpressLRS-Configurator#326]
With the PR [#197](https://github.com/ExpressLRS/Docs/pull/197) on the Docs Repo, we'll need to update a bunch of WikiURL properties.
I can get it done and make the PR here should that PR gets merged in.

**Comment by maybenikhil** [comment]
[#197](https://github.com/ExpressLRS/Docs/pull/197) on docs is merged, so this is now top priority

**Comment by deadbytefpv** [comment]
> 

I'll PR the changes.. thanks!
