### ISSUE TITLE
Can't build any Backpack on MacOS

### ISSUE THREAD

**Issue by f4b0** [ExpressLRS/ExpressLRS-Configurator#338]
## Current Behavior
Hi, i am trying to build the Frsky TX Backpack or Zorro TX Backpack on my Mac with the settings below.

<img width="1792" alt="Bildschirmfoto 2022-05-17 um 08 50 08" src="https://user-images.githubusercontent.com/42566295/168747317-7a1efda6-2b99-45a4-b4d4-8217bb009231.png">

But i get the following error:
I tried it also with the latest master branch without success

`Failed to find Platformio on your computer. Trying to install it automatically...Installer version: 1.1.0
Platform: macOS-10.16
Python version: 3.8.4 (default, Jul 14 2020, 15:19:59) 
[Clang 10.0.0 (clang-1000.10.44.4)]
Python path: /Applications/ExpressLRS Configurator.app/Contents/dependencies/darwin_amd64/python-portable-darwin-3.8.4/bin/python3
Creating a virtual environment at /Users/f4b0/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Using cached platformio-6.0.0-py3-none-any.whl
Collecting marshmallow==3.*
  Using cached marshmallow-3.15.0-py3-none-any.whl (47 kB)
Collecting aiofiles==0.8.*
  Using cached aiofiles-0.8.0-py3-none-any.whl (13 kB)
Collecting wsproto==1.1.*
  Using cached wsproto-1.1.0-py3-none-any.whl (24 kB)
Collecting click<9,>=8.0.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting ajsonrpc==1.*
  Using cached ajsonrpc-1.2.0-py3-none-any.whl (22 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting uvicorn==0.17.*
  Using cached uvicorn-0.17.6-py3-none-any.whl (53 kB)
Collecting requests==2.*
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting bottle==0.12.*
  Using cached bottle-0.12.19-py3-none-any.whl (89 kB)
Collecting tabulate==0.8.*
  Using cached tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting semantic-version==2.9.*
  Using cached semantic_version-2.9.0-py2.py3-none-any.whl (15 kB)
Collecting starlette==0.20.*
  Using cached starlette-0.20.0-py3-none-any.whl (61 kB)
Collecting zeroconf<1
  Using cached zeroconf-0.38.6-py3-none-any.whl (106 kB)
Collecting pyelftools<1,>=0.27
  Using cached pyelftools-0.28-py2.py3-none-any.whl (155 kB)
Collecting pyserial==3.*
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting typing-extensions>=3.10.0
  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting anyio<5,>=3.4.0
  Using cached anyio-3.6.1-py3-none-any.whl (80 kB)
Collecting asgiref>=3.4.0
  Downloading asgiref-3.5.2-py3-none-any.whl (22 kB)
Collecting h11>=0.8
  Using cached h11-0.13.0-py3-none-any.whl (58 kB)
Collecting ifaddr>=0.1.7
  Using cached ifaddr-0.1.7-py2.py3-none-any.whl (10 kB)
Collecting sniffio>=1.1
  Using cached sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Installing collected packages: tabulate, pyserial, pyelftools, ifaddr, certifi, bottle, zeroconf, urllib3, typing-extensions, sniffio, semantic-version, pyparsing, idna, h11, colorama, click, charset-normalizer, asgiref, ajsonrpc, aiofiles, wsproto, uvicorn, requests, packaging, anyio, starlette, marshmallow, platformio
Successfully installed aiofiles-0.8.0 ajsonrpc-1.2.0 anyio-3.6.1 asgiref-3.5.2 bottle-0.12.19 certifi-2021.10.8 charset-normalizer-2.0.12 click-8.1.3 colorama-0.4.4 h11-0.13.0 idna-3.3 ifaddr-0.1.7 marshmallow-3.15.0 packaging-21.3 platformio-6.0.0 pyelftools-0.28 pyparsing-3.0.9 pyserial-3.5 requests-2.27.1 semantic-version-2.9.0 sniffio-1.2.0 starlette-0.20.0 tabulate-0.8.9 typing-extensions-4.2.0 urllib3-1.26.9 uvicorn-0.17.6 wsproto-1.1.0 zeroconf-0.38.6

PlatformIO Core has been successfully installed into an isolated environment `/Users/f4b0/.platformio/penv`!

The full path to `platformio.exe` is `/Users/f4b0/.platformio/penv/bin/platformio`

If you need an access to `platformio.exe` from other applications, please install Shell Commands
(add PlatformIO Core binary directory `/Users/f4b0/.platformio/penv/bin` to the system environment PATH variable):

See https://docs.platformio.org/page/installation.html#install-shell-commands

********************************************************************************
If you like PlatformIO, please:
- follow us on Twitter to stay up-to-date on the latest project news > https://twitter.com/PlatformIO_Org
- star it on GitHub > https://github.com/platformio/platformio
- try PlatformIO IDE for embedded development > https://platformio.org/platformio-ide
********************************************************************************

Processing Radiomaster_Zorro_TX_Backpack_via_ETX (board: esp8285; platform: espressif8266@3.2.0; framework: arduino)
--------------------------------------------------------------------------------
Platform Manager: Installing espressif8266 @ 3.2.0
Downloading
Unpacking
Platform Manager: espressif8266@3.2.0 has been installed!
Tool Manager: Installing platformio/toolchain-xtensa @ ~2.100300.0
Downloading
Unpacking
Tool Manager: toolchain-xtensa@2.100300.210717 has been installed!
Tool Manager: Installing platformio/framework-arduinoespressif8266 @ ~3.30002.0
Downloading
Unpacking
Tool Manager: framework-arduinoespressif8266@3.30002.0 has been installed!
Tool Manager: Installing platformio/tool-esptool @ <2
Downloading
Unpacking
Tool Manager: tool-esptool@1.413.0 has been installed!
Tool Manager: Installing platformio/tool-esptoolpy @ ~1.30000.0
Downloading
Unpacking
Tool Manager: tool-esptoolpy@1.30000.201119 has been installed!
Library Manager: Installing ottowinter/ESPAsyncWebServer-esphome @ ^2.0.1
Downloading
Unpacking
Library Manager: ESPAsyncWebServer-esphome@2.1.0 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing ottowinter/ESPAsyncTCP-esphome
Downloading
Unpacking
Library Manager: ESPAsyncTCP-esphome@1.2.3 has been installed!
Library Manager: Installing esphome/AsyncTCP-esphome
Downloading
Unpacking
Library Manager: AsyncTCP-esphome@1.2.2 has been installed!
Tool Manager: Installing platformio/tool-scons @ ~4.40300.0
Downloading
Unpacking
Tool Manager: tool-scons@4.40300.1 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
UID bytes: 219,165,243,45,156,23
***
Building for ESP8266/ESP8285 Platform
AUTO_WIFI_ON_INTERVAL = OFF
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp8285.html
PLATFORM: Espressif 8266 (3.2.0) > Generic ESP8285 Module
HARDWARE: ESP8266 160MHz, 80KB RAM, 1MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 @ 3.30002.0 (3.0.2) 
 - tool-esptool @ 1.413.0 (4.13) 
 - tool-esptoolpy @ 1.30000.201119 (3.0.0) 
 - toolchain-xtensa @ 2.100300.210717 (10.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 48 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- config
|   |-- EEPROM
|   |   |-- logging
|   |   |-- EEPROM @ 1.0
|   |   |-- Wire @ 1.0
|   |-- logging
|-- BUTTON
|   |-- DEVICE
|   |-- logging
|-- LED
|   |-- DEVICE
|-- WIFI
|   |-- DEVICE
|   |-- STM32UPDATE
|   |   |-- logging
|   |-- config
|   |   |-- EEPROM
|   |   |   |-- logging
|   |   |   |-- EEPROM @ 1.0
|   |   |   |-- Wire @ 1.0
|   |   |-- logging
|   |-- logging
|   |-- DNSServer @ 1.1.1
|   |   |-- ESP8266WiFi @ 1.0
|   |-- ESP8266WiFi @ 1.0
|   |-- ESP8266mDNS @ 1.2
|   |   |-- ESP8266WiFi @ 1.0
|   |-- ESPAsyncWebServer-esphome @ 2.1.0
|   |   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |   |-- Hash @ 1.0
|   |   |-- ESP8266WiFi @ 1.0
|-- DEVICE
|-- logging
|-- MSP
|   |-- logging
|-- ESP8266WiFi @ 1.0
|-- CRC
|-- CrsfProtocol
|-- SPI @ 1.0
Building in release mode
PLATFORM : 'espressif8266'
BUILD ENV: 'RADIOMASTER_ZORRO_TX_BACKPACK_VIA_ETX'
Compiling .pio/build/Radiomaster_Zorro_TX_Backpack_via_ETX/src/Tx_main.cpp.o
Compiling .pio/build/Radiomaster_Zorro_TX_Backpack_via_ETX/src/Vrx_main.cpp.o
Compiling .pio/build/Radiomaster_Zorro_TX_Backpack_via_ETX/src/fusion.cpp.o
Compiling .pio/build/Radiomaster_Zorro_TX_Backpack_via_ETX/src/hdzero.cpp.o
Compiling .pio/build/Radiomaster_Zorro_TX_Backpack_via_ETX/src/options.cpp.o
Compiling .pio/build/Radiomaster_Zorro_TX_Backpack_via_ETX/src/rapidfire.cpp.o
src/Vrx_main.cpp:89:1: error: 'VrxBackpackConfig' does not name a type; did you mean 'TxBackpackConfig'?
   89 | VrxBackpackConfig config;
      | ^~~~~~~~~~~~~~~~~
      | TxBackpackConfig
src/Vrx_main.cpp: In function 'void RebootIntoWifi()':
src/Vrx_main.cpp:116:10: error: 'class TxBackpackConfig' has no member named 'SetBootCount'
  116 |   config.SetBootCount(0);
      |          ^~~~~~~~~~~~
src/Vrx_main.cpp: In function 'void resetBootCounter()':
src/Vrx_main.cpp:309:10: error: 'class TxBackpackConfig' has no member named 'SetBootCount'
  309 |   config.SetBootCount(0);
      |          ^~~~~~~~~~~~
src/Vrx_main.cpp: In function 'void checkIfInBindingMode()':
src/Vrx_main.cpp:315:32: error: 'class TxBackpackConfig' has no member named 'GetBootCount'
  315 |   uint8_t bootCounter = config.GetBootCount();
      |                                ^~~~~~~~~~~~
src/Vrx_main.cpp:330:12: error: 'class TxBackpackConfig' has no member named 'SetBootCount'
  330 |     config.SetBootCount(bootCounter);
      |            ^~~~~~~~~~~~
src/Vrx_main.cpp: In function 'void setup()':
src/Vrx_main.cpp:396:3: error: 'vrxModule' was not declared in this scope
  396 |   vrxModule.Init();
      |   ^~~~~~~~~
src/Vrx_main.cpp: In function 'void loop()':
src/Vrx_main.cpp:430:5: error: 'vrxModule' was not declared in this scope
  430 |     vrxModule.SendIndexCmd(cachedIndex);
      |     ^~~~~~~~~
src/Vrx_main.cpp:442:39: error: 'class TxBackpackConfig' has no member named 'GetBootCount'
  442 |   if (now > BINDING_TIMEOUT && config.GetBootCount() > 0)
      |                                       ^~~~~~~~~~~~
*** [.pio/build/Radiomaster_Zorro_TX_Backpack_via_ETX/src/Vrx_main.cpp.o] Error 1
src/rapidfire.cpp: In member function 'void Rapidfire::Init()':
src/rapidfire.cpp:12:13: error: 'PIN_MOSI' was not declared in this scope
   12 |     pinMode(PIN_MOSI, INPUT);
      |             ^~~~~~~~
src/rapidfire.cpp:13:13: error: 'PIN_CLK' was not declared in this scope
   13 |     pinMode(PIN_CLK, INPUT);
      |             ^~~~~~~
src/rapidfire.cpp:14:13: error: 'PIN_CS' was not declared in this scope; did you mean 'PIN_A0'?
   14 |     pinMode(PIN_CS, INPUT);
      |             ^~~~~~
      |             PIN_A0
src/rapidfire.cpp: In member function 'void Rapidfire::EnableSPIMode()':
src/rapidfire.cpp:23:13: error: 'PIN_MOSI' was not declared in this scope
   23 |     pinMode(PIN_MOSI, OUTPUT);
      |             ^~~~~~~~
src/rapidfire.cpp:24:13: error: 'PIN_CLK' was not declared in this scope
   24 |     pinMode(PIN_CLK, OUTPUT);
      |             ^~~~~~~
src/rapidfire.cpp:25:13: error: 'PIN_CS' was not declared in this scope; did you mean 'PIN_A0'?
   25 |     pinMode(PIN_CS, OUTPUT);
      |             ^~~~~~
      |             PIN_A0
src/rapidfire.cpp: In member function 'void Rapidfire::SendSPI(uint8_t*, uint8_t)':
src/rapidfire.cpp:167:13: error: 'PIN_MOSI' was not declared in this scope
  167 |     pinMode(PIN_MOSI, OUTPUT);
      |             ^~~~~~~~
src/rapidfire.cpp:168:13: error: 'PIN_CLK' was not declared in this scope
  168 |     pinMode(PIN_CLK, OUTPUT);
      |             ^~~~~~~
src/rapidfire.cpp:169:13: error: 'PIN_CS' was not declared in this scope; did you mean 'PIN_A0'?
  169 |     pinMode(PIN_CS, OUTPUT);
      |             ^~~~~~
      |             PIN_A0
*** [.pio/build/Radiomaster_Zorro_TX_Backpack_via_ETX/src/rapidfire.cpp.o] Error 1
========================= [FAILED] Took 56.59 seconds =========================

Environment                            Status    Duration
-------------------------------------  --------  ------------
Radiomaster_Zorro_TX_Backpack_via_ETX  FAILED    00:00:56.586
==================== 1 failed, 0 succeeded in 00:00:56.586 ====================
`

## Steps to Reproduce

1. Select "Backpack" in ELRS Configurator
2. Select Target Type "TX" and Device "Frsky Tx Backpack"
3.  Press "Build" button

## Your Environment
OS: MacOS 12.4
ELRS Configurator v1.4.1

**Comment by pkendall64** [comment]
Platformio have done a release today and have broken a whole load of projects that use it!

**Comment by f4b0** [comment]
ohh thats bad, please let me know if i can or should test something. 
Thanks!

**Comment by f4b0** [comment]
that was the solution for the problem 

https://github.com/ExpressLRS/Backpack/pull/69

Thanks a lot, i was able to build again!

**Comment by GutoFleury** [comment]
I cant build for my Jumper T-pro.

Logs:

Please wait while upgrading PlatformIO...
Error: Traceback (most recent call last):
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\click\core.py", line 1654, in invoke
    super().invoke(ctx)
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gutof\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python-3.11.0a4.amd64\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\click\core.py", line 101, in augment_usage_errors
    yield
    ^^^^^
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\platformio\__main__.py", line 56, in cli
    maintenance.on_platformio_start(ctx, force, caller)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\platformio\maintenance.py", line 43, in on_platformio_start
    after_upgrade(ctx)
    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\platformio\maintenance.py", line 155, in after_upgrade
    cleanup_content_cache("http")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\platformio\cache.py", line 164, in cleanup_content_cache
    with ContentCache(namespace) as cc:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\platformio\cache.py", line 36, in __enter__
    self.delete()
    ^^^^^^^^^^^^^
  File "C:\Users\gutof\.platformio\penv\Lib\site-packages\platformio\cache.py", line 132, in delete
    with open(self._db_path, mode="w", encoding="utf8") as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\gutof\\.platformio\\.cache\\http\\db.data'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

===========================================================
