### ISSUE TITLE
AttributeError: module 'pypandoc' has no attribute 'convert'

### ISSUE THREAD

**Issue by szyrin** [ExpressLRS/ExpressLRS-Configurator#339]
## Expected Behavior

Successful build.

## Current Behavior

Currently build fails, seems like due to changes in PyPandoc v1.8 library, which removed the deprecated `convert` method.
There are multiple references in the build logs:

>       '        File "/private/var/folders/c3/4qqvl38n4ns52bvy7j_5tycr0000gn/T/pip-install-3vtj8soj/streamexpect_7f8945ed1ab04db387175bd1bb4cd272/.eggs/setuptools_markdown-0.4.1->py3.8.egg/setuptools_markdown.py", line 43, in long_description_markdown_filename\n' +
>     "          output = pypandoc.convert(markdown_filename, 'rst', format='md')\n" +
>      "      AttributeError: module 'pypandoc' has no attribute 'convert'\n" +
>      '      [end of output]\n' +

Comment from PyPandoc maintainer: https://github.com/man-group/pytest-plugins/issues/87#issuecomment-1123830409

## Steps to Reproduce

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/15380439/168879763-ac180fc6-a1d4-425d-8ce2-8851ef3ce925.png">

[expressslrs-configurator.log](https://github.com/ExpressLRS/ExpressLRS-Configurator/files/8710563/expressslrs-configurator.log)

## Possible Solution (Not obligatory)

I guess a possible solution would be to force the usage of PyPandoc v1.7.0

## Your Environment

MacOS 10.13

**Comment by justinlampley** [comment]
This has already been addressed in PR https://github.com/ExpressLRS/ExpressLRS/pull/1564.
