### ISSUE TITLE
Flashing a known target results in the target changing to DIY

### ISSUE THREAD

**Issue by PhilippMolitor** [ExpressLRS/ExpressLRS-Configurator#342]
## Expected Behavior

Flashing a device with a known and defined target results in the firmware including the correct target definition.

## Current Behavior

 I am flashing a `BETAFPV Lite 2400 RX` target, but I was already warned that the `DIY_2400_RX_ESP8285_SX1280` target is different from the currently flashed `BETAFPV Lite 2400 RX` that was on there from the factory.
After flashing, everything is working (as i selected the correct target), but the DIY target is now in place, giving me a hard time remembering which firmware target i have to compile when updating next time.

## Steps to Reproduce

Standard flashing procedure. Is applicable to UART, WiFi and BF Passthrough (I tested each).

**Comment by justinlampley** [comment]
The BETAFPV Lite 2400 RX is an alias of DIY_2400_RX_ESP8285_SX1280, they are exactly the same firmware.  You can either flash DIY 2400 RX ESP8285 SX1280 (DIY_2400_RX_ESP8285_SX1280) target directly or the alias, BETAFPV Lite 2400 RX, both will work exactly the same.

**Comment by PhilippMolitor** [comment]
Hmm okay, I see. I still find it a bit inconvenient even as a software dev myself, because now the configurator handles this in a very weird way, e.g. when i flash it, the CLI prompt "targets do not match, do you still want to flash (y/n): " of course accepts no input - i think this issue is not done yet, or has other small issues relating to it.

**Comment by justinlampley** [comment]
The configurator is just a wrapper around platform IO commands, it doesn't do any of the compiling/flashing itself, so it has no control over how the flashing is done besides what options it can pass to Platform IO, all the logic resides in the firmware repository.  The use of aliases was a decision was made by the firmware developers to avoid the need to create new targets for every new device if it has the same features and pinouts as an existing device, but it does unfortunately come with some added confusion for the end user.

Regarding the target mismatch, there is a Force Flash option in the configurator that tells PIO to flash even if there is a target mismatch.  The (y/n) prompt should not occur if it is not an interactive prompt, the script should just exit with an error code, I will ask the firmware developers about that.

![image](https://user-images.githubusercontent.com/38869875/172445486-f1fb4036-3dd3-4030-b98a-db423366d29d.png)

With version 3.0 of the firmware and the introduction of the unified ESP firmware, this is all going to change as all ESP devices are going to be running the same firmware.
