### ISSUE TITLE
Build Error in Release 2.5.0 for Frsky R9 FRsky TX R9M

### ISSUE THREAD

**Issue by lumesw** [ExpressLRS/ExpressLRS-Configurator#343]
## Expected Behavior

Finished build.

## Current Behavior

Error Message:
![image](https://user-images.githubusercontent.com/107065936/172437844-487df10e-2c5a-487a-89fd-ab2b9bacdb46.png)

## Steps to Reproduce

1. Set configuration to the following:
![image](https://user-images.githubusercontent.com/107065936/172438113-349fd4c3-c7cd-45f1-a44e-23898cd0b21a.png)
![image](https://user-images.githubusercontent.com/107065936/172438284-9c4dfcd6-0bb9-4c5c-9a78-29b6a6665479.png)

2. Click build

## Context

Log-File:
[ExpressLRSBuildLog_20220607165150469.txt](https://github.com/ExpressLRS/ExpressLRS-Configurator/files/8855082/ExpressLRSBuildLog_20220607165150469.txt)
## Your Environment

Windows 10 Home

- Operating System and version:
- TX hardware:
- RX hardware:

**Comment by justinlampley** [comment]
If MY_STARTUP_MELODY is selected, you have to provide a valid melody.  If you don't want to provide a melody, unselect that option.

**Comment by lumesw** [comment]
Thanks for the quick response. May one could add a message that reminds the user, that the file is not attached.
