### ISSUE TITLE
Serial Monitor display garbled string when use CP2102N instead of CP2102

### ISSUE THREAD

**Issue by jonesfu** [ExpressLRS/ExpressLRS-Configurator#35]
Base on ESP32-DevKitM-1, we only change CP2102 chip to CP2102N chip(because we cannot buy CP2102 now),  it can be flashed and reset. But Serial Monitor display garbled string as below picture:
![image](https://user-images.githubusercontent.com/3425654/126976617-2717f46d-9f3c-403a-b48f-bba951a40aa6.png)

It is very stranger, could you please help us?

**Comment by JyeSmith** [comment]
You need to change the serial baud to be the same as what is set on the esp32.  You can see what I had to do in the link below.

The n version must be a little tighter on its timings or something.

https://github.com/ExpressLRS/ExpressLRS/pull/723/commits/4074f0d220a731ab405a79ec4c7250ad0d7606cc

**Comment by jonesfu** [comment]
Hi JyeSmith. There is still display garbled string after I set "monitor_speed = 460800" in ExpressLRF project, any other possible?

**Comment by jonesfu** [comment]
> You need to change the serial baud to be the same as what is set on the esp32. You can see what I had to do in the link below.
> 
> The n version must be a little tighter on its timings or something.
> 
> [ExpressLRS/ExpressLRS@4074f0d](https://github.com/ExpressLRS/ExpressLRS/commit/4074f0d220a731ab405a79ec4c7250ad0d7606cc)

Hi JyeSmith. There is still display garbled string after I set "monitor_speed = 460800" in ExpressLRF project, any other possible?

**Comment by JyeSmith** [comment]
Not off the top of my head.  That was the immediate fix for when I tested the n version.

**Comment by jonesfu** [comment]
> Not off the top of my head. That was the immediate fix for when I tested the n version.

Thanks JyeSmith, another what is your facebook account, we need discuss to you for new project.

**Comment by JyeSmith** [comment]
@jonesfu best place to chat is on discord.

**Comment by jurgelenas** [comment]
I think that is not the configurator issue. Closing.
