### ISSUE TITLE
Correct Skystars SS24D 2400 RX

### ISSUE THREAD

**Issue by JyeSmith** [ExpressLRS/ExpressLRS-Configurator#357]
"Skystars SS24D 2400 RX"  is diversity and needs to be moved to be an alias of the "Matek 2400 RX R24D"

I started to do it but yarn decided to complain about an error with loader.js ☹️ 

Move this... 
https://github.com/ExpressLRS/ExpressLRS-Configurator/blob/a2167cf0e89bfcab94720d24149a8d53c57dcd68/devices/matek-2400.json#L39

To here...
https://github.com/ExpressLRS/ExpressLRS-Configurator/blob/a2167cf0e89bfcab94720d24149a8d53c57dcd68/devices/matek-2400.json#L112

**Comment by jurgelenas** [comment]
Fixed in 50063b5edb73ff7944b7748bc121bfe6fbe41a0b
