### ISSUE TITLE
Configurator v1.4.2 / ELRS V3.0.0 RC1: Flashing Skystars SS24D 2400 RX pops up Matek messages!

### ISSUE THREAD

**Issue by Pairan** [ExpressLRS/ExpressLRS-Configurator#359]
Just build the Skystars SS24D 2400 RX Diversity RX firmware and wanted to flash the RX via wifi. After uploading the Firmware to the RX it reports that the MATEK firmware is not matching to the uploaded one! :)

## Expected Behavior
It should know its a Skystars RX and not say anything like MATEK - that'll confuse people

## Current Behavior
<img width="938" alt="Bildschirmfoto 2022-07-07 um 18 10 05" src="https://user-images.githubusercontent.com/8381714/177822163-8e2d0099-90dc-45a7-90dd-a1aefc75908c.png">

## Steps to Reproduce
Simply build the firmware for the Skystars RX (V3.0.0 RC1) and upload it to the RX via browser

After hitting `flash anyway` it flashes the firmware and runs as expected.

## Environment
MAC - running Configurator v1.4.2 

## final thoughts
cant we compile the "alias" into the RX so this will be gone or does it have to stay as "MATEK" for technical reasons?

**Comment by jurgelenas** [comment]
This is a fundamental issue with ExpressLRS. We have a plan to fix this in later firmware releases. There is not much we can do from the configurator app side.
