### ISSUE TITLE
Python 3.11: ImportError: cannot import name 'getargspec' from 'inspect'

### ISSUE THREAD

**Issue by ivankravets** [ExpressLRS/ExpressLRS-Configurator#363]
See https://github.com/platformio/platformio-vscode-ide/issues/3252

> ExpressLRS Configurator\dependencies\windows_amd64\python-3.11.0a4.amd64

Could we ask you to install the latest stable Python 3.9? We have a lot of Python packages that still do not support Python 3.10, not saying 3.11 Beta. Also, it is not a good practice to install the alpha version of the Python interpreter.

# Related issues

- https://github.com/bottlepy/bottle/issues/1387

**Comment by jurgelenas** [comment]
Fixed in #367
