### ISSUE TITLE
I can't compile firmware that has version below 2.5. This problem occurs for every target choice. But version>2.5 works perfectly fine.

### ISSUE THREAD

**Issue by zuozuoxiong** [ExpressLRS/ExpressLRS-Configurator#368]
Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  �� python setup.py egg_info did not run successfully.
  �� exit code: 1
  �t��> [28 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\32887\AppData\Local\Temp\pip-install-ku34_0ew\streamexpect_60c04b8aff1d466e8453eee924389f16\setup.py", line 20, in <module>
          setup(
          ^^^^^^
        File "C:\Users\32887\.platformio\penv\Lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\32887\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python-3.11.0a4.amd64\Lib\distutils\core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "C:\Users\32887\.platformio\penv\Lib\site-packages\setuptools\dist.py", line 453, in __init__
          _Distribution.__init__(
          ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\32887\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python-3.11.0a4.amd64\Lib\distutils\dist.py", line 292, in __init__
          self.finalize_options()
          ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\32887\.platformio\penv\Lib\site-packages\setuptools\dist.py", line 831, in finalize_options
          ep(self)
          ^^^^^^^^
        File "C:\Users\32887\.platformio\penv\Lib\site-packages\setuptools\dist.py", line 852, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "c:\users\32887\appdata\local\temp\pip-install-ku34_0ew\streamexpect_60c04b8aff1d466e8453eee924389f16\.eggs\setuptools_markdown-0.4.1-py3.11.egg\setuptools_markdown.py", line 43, in long_description_markdown_filename
          output = pypandoc.convert(markdown_filename, 'rst', format='md')
                   ^^^^^^^^^^^^^^^^
      AttributeError: module 'pypandoc' has no attribute 'convert'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

�� Encountered error while generating package metadata.
�t��> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.1.2 -> 22.2
[notice] To update, run: python.exe -m pip install --upgrade pip
CalledProcessError: Command '['C:\\Users\\32887\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', 'streamexpect']' returned non-zero exit status 1.:
  File "C:\Users\32887\.platformio\penv\Lib\site-packages\platformio\builder\main.py", line 196:
    env.SConscript(item, exports="env")
  File "C:\Users\32887\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Script\SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\32887\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Script\SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\Users\32887\AppData\Roaming\ExpressLRS Configurator\firmwares\github\ExpressLRS\src\python\build_env_setup.py", line 7:
    import ETXinitPassthrough
  File "C:\Users\32887\AppData\Roaming\ExpressLRS Configurator\firmwares\github\ExpressLRS\src\python\ETXinitPassthrough.py", line 14:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "streamexpect"])
  File "C:\Users\32887\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python-3.11.0a4.amd64\Lib\subprocess.py", line 369:
    raise CalledProcessError(retcode, cmd)
========================= [FAILED] Took 16.50 seconds =========================

Environment                        Status    Duration
---------------------------------  --------  ------------
Jumper_AION_NANO_2400_TX_via_UART  FAILED    00:00:16.505
==================== 1 failed, 0 succeeded in 00:00:16.505 ====================

**Comment by justinlampley** [comment]
Try clearing your Platform IO dependencies, Support -> Clear Platform IO Dependencies and then try again.  

There was an issue related to this in the firmware repo, https://github.com/ExpressLRS/ExpressLRS/pull/1564.

**Comment by krisdover** [comment]
In case anyone else is struggling with this, ELRS is backwards compatible across minor versions for the same major version (e.g. all v2.x) so a v2.4.0 TX will work fine with a v2.5.1 RX. I was trying to upgrade an RX from v1.1.0 to v2.4.0 to match my TX when I encountered this build issue. Following the advice here I just skipped forward to v2.5.1 and it worked fine.

**Comment by jurgelenas** [comment]
Try using 1.5.0 configurator release.

**Comment by wizardrnd** [comment]
Unfortunately, the problem is still relevant. I tried to build the firmware using the 1.5.0 and 1.5.1 configurator, but I still get an error when building firmware 2.4.0 and below.

**Comment by jurgelenas** [comment]
> Unfortunately, the problem is still relevant. I tried to build the firmware using the 1.5.0 and 1.5.1 configurator, but I still get an error when building firmware 2.4.0 and below.

Just migrate to the latest stable release. It is so so much better :)

**Comment by wizardrnd** [comment]
> Just migrate to the latest stable release. It is so so much better :)

I cannot agree with you with your advice: 
1) wifi-flasher is broken in version 2.5.0 (ExpressLRS/ExpressLRS#1580, ExpressLRS/ExpressLRS#1600)
2) BLE-joystick turns off spontaneously in version 2.5.1 (ExpressLRS/ExpressLRS#1779)
Thus 2.4.0 is the most stable of the 2.x.

As for version 3.x - it was released recently and has not been tested enough by a large number of users. I will try to use it no earlier than 2 months - after most of bugfixes, for example ELRSv3.lua, which works very unstable and sometimes leads to unstable TX work until I reset the power.

P.S. I found a way to build firmware 2.0-2.4. To do this, I replace the file src/python/ETXinitPassthrough.py by the same file from version 2.5.x and add to the source two files - src/python/external/six.py and src/python/external/streamexpect.py from version 2.5.x before starting the build (ExpressLRS/ExpressLRS#1564).

**Comment by jurgelenas** [comment]
> > Just migrate to the latest stable release. It is so so much better :)
> 
> I cannot agree with you with your advice:
> 
>     1. wifi-flasher is broken in version 2.5.0 ([[2.x] Restore HTTP upload functionality ExpressLRS#1580](https://github.com/ExpressLRS/ExpressLRS/pull/1580), [[2.x] Fix WiFi force flash ExpressLRS#1600](https://github.com/ExpressLRS/ExpressLRS/pull/1600))
> 
>     2. BLE-joystick turns off spontaneously in version 2.5.1 ([BLE Joystick mode auto exits after few seconds. ExpressLRS#1779](https://github.com/ExpressLRS/ExpressLRS/issues/1779))
> 
> 
> Thus 2.4.0 is the most stable of the 2.x.
> 
> As for version 3.x - it was released recently and has not been tested enough by a large number of users. I will try to use it no earlier than 2 months - after most of bugfixes, for example ELRSv3.lua, which works very unstable and sometimes leads to unstable TX work until I reset the power.
> 
> P.S. I found a way to build firmware 2.0-2.4. To do this, I replace the file src/python/ETXinitPassthrough.py by the same file from version 2.5.x and add to the source two files - src/python/external/six.py and src/python/external/streamexpect.py from version 2.5.x before starting the build ([ExpressLRS/ExpressLRS#1564](https://github.com/ExpressLRS/ExpressLRS/pull/1564)).

I could not disagree to your comments about 3.0 release. The vast majority of ExpressLRS community is using 3.0 now. My suggestion is just to try it.

**Comment by wizardrnd** [comment]
> My suggestion is just to try it.
This will not happen until you fix the bugs in ELRSv3.lua. For example, this one: ExpressLRS/ExpressLRS#1843
