### ISSUE TITLE
On compiling firmware for R9M module it shows faile to fetch

### ISSUE THREAD

**Issue by prasanthsoman86** [ExpressLRS/ExpressLRS-Configurator#37]

**Comment by prasanthsoman86** [comment]
Tool Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts

**Comment by prasanthsoman86** [comment]
Processing Frsky_TX_R9M_via_stock_BL (platform: ststm32@8.0.0; board: bluepill_f103c8; framework: arduino)
--------------------------------------------------------------------------------
Tool Manager: Installing toolchain-gccarmnoneeabi @ ~1.90201.0
Tool Manager: Warning! More than one package has been found by toolchain-gccarmnoneeabi @ ~1.90201.0 requirements:
 - platformio/toolchain-gccarmnoneeabi @ 1.50401.210715
 - maxgerhardt/toolchain-gccarmnoneeabi @ 1.40903.0
Tool Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts

**Comment by prasanthsoman86** [comment]
Above shown are the total log details and it shows failed to fetch!  Can some one help me?

**Comment by jurgelenas** [comment]
This step requires network connection, if your network is really slow I recommend waiting up to 30 mins. There is not much I can do about that.

This step can also have some issues if you are based in China, but typically users are failing much earlier in the compilation process when that is the case.
