### ISSUE TITLE
link to user_defines

### ISSUE THREAD

**Issue by P-I-Engineer** [ExpressLRS/ExpressLRS-Configurator#370]
can you add a link to the user_ defines in the configurator. When switching to manual mode, the user_defines in the configurator are empty. I had to go hunting to grab them.

even cooler, if possible, have the user_defines from from standard mode populate the manual mode window

**Comment by DennyRoadman** [comment]
The same problem, i'm updating configurator today to try 3.0 pre-reliese and spend a lot of time to search my configuration in logs((( Manual mode is emty((

**Comment by jurgelenas** [comment]
This was done on purpose in order not to store any secrets in the log (binding phrase,  wifi credentials).
