### ISSUE TITLE
Question: NamimnoRC Flash 2400 OLED TX  no 10mW mode

### ISSUE THREAD

**Issue by HazzaHFPV** [ExpressLRS/ExpressLRS-Configurator#371]
This is just a quick question and I cant seem to find the answer online.
My Namimno Flash OLED 2.4GHz Module is flashed with ELRS 3.0 RC1.
The minimum output-power selecable is 25mW. I understood that I could go down to 10mW, but that option is not there.
When flashing with the REGULATORY_DOMAIN_EU_CE_2400 selected it still does not go down to 10mW as stated in the configurator.
25mW remains the minimum and I can still go up to 100mW.
I guess it goes up to 100mW  because now LBT is implemented? But why can't I go down to 10mW?
Thank you for your help.

**Comment by pkendall64** [comment]
It can't go down to 10mW because it's a limitation of the hardware used in that design.

**Comment by HazzaHFPV** [comment]
Oh okay. It is selectable in ELRS v2.5.1. That's why I became confused when the option was gone in v3.0.0-RC1
