### ISSUE TITLE
Unable to build firmware on macOS

### ISSUE THREAD

**Issue by C0br4** [ExpressLRS/ExpressLRS-Configurator#372]
## Expected Behavior

Successful build of firmware

## Current Behavior

Building the firmware with the configurator results in a Build Error

## Steps to Reproduce

**Stack trace:**

Processing Frsky_TX_R9M_via_stock_BL (platform: ststm32@15.1.0; board: bluepill_f103c8; framework: arduino)
Tool Manager: Installing platformio/tool-stm32duino @ ~1.0.1
Downloading
Unpacking
Tool Manager: tool-stm32duino @ 1.0.1 has been installed!
Tool Manager: Installing platformio/tool-openocd @ ~2.1100.0
Downloading
Unpacking
Tool Manager: tool-openocd @ 2.1100.211028 has been installed!
Tool Manager: Installing platformio/tool-dfuutil @ ~1.9.190708
Downloading
Unpacking
Tool Manager: tool-dfuutil @ 1.9.200310 has been installed!
Tool Manager: Installing platformio/tool-scons @ ~4.40200.0
Error: Could not find the package with 'platformio/tool-scons @ ~4.40200.0' requirements for your system 'darwin_x86_64'

## Your Environment

- Operating System and version:
 macOS 10.15.7
- TX hardware:
R9M
- RX hardware:
- Configurator Version
1.4.2

**Comment by ibtoaster** [comment]
Similar problem? Mac OS 12.5 and ExpressLRS Configurator installs but then has a error in the target section so no radios can be selected. Going to support to clear PlatformIO deficiencies results in another error.

**Comment by C0br4** [comment]
Updating pip and all python packages on my system fixed the issue
