### ISSUE TITLE
Installing and using Configurator in parallel with PlatformIO IDE/VS Code

### ISSUE THREAD

**Issue by fiechr** [ExpressLRS/ExpressLRS-Configurator#373]
I'm running Manjaro Linux.

I'm using PlatformIO IDE (the plugin) for Visual Studio Code for development of different platforms, like ESP8266/ESP32 and RP2040 with the Arduino framework.

![screenshot_20220809_100352](https://user-images.githubusercontent.com/12040376/183597509-e153f4ae-8635-4964-a1c9-ba3ca52d72a8.png)

I've also ExpressLRS Configurator 1.4.2 installed to build firmware for different RXs and TXs using the following AUR package:
https://aur.archlinux.org/packages/expresslrs-configurator
(This version is outdated, but I updated the [PKGBUILD file](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=expresslrs-configurator) manually to 1.4.2.)
```
$ which expresslrs-configurator
/usr/bin/expresslrs-configurator
```
![screenshot_20220809_102145](https://user-images.githubusercontent.com/12040376/183600862-ec9a982d-56fc-428c-8505-308e37ad47c2.png)

The problem is, that these both applications somehow(TM) influence each other. I've tried to figure this out by myself, but just don't get my head around how it actually works.

Inside VS Code and PlatformIO IDE, I've selected the builtin Python and builtin PlatformIO. So I was thinking this should prevent any influence from the "outside", but it doesn't. Both apps seem to use the same virtual environment in ~/.platformio.

![screenshot_20220809_015541](https://user-images.githubusercontent.com/12040376/183595166-761d2d7b-0d5a-49b7-bb4c-3d12ff42bca3.png)

If I click on "Clear PlatformIO Dependencies" inside the Configurator, all my platforms in PlatformIO IDE are gone, too. Although, I could swear that I did that a few months with a different result. Also, I get warning messages of missing compilers inside PlatformIO IDE or messages that there is another outdated core installed and I should remove it.

After that most of the platforms got automatically reinstalled because of the platformio.ini files. But, for example, a ESC32-C3 board didn't worked and PlatformIO IDE said, it wasn't supported by the Arduino framework (which is wrong, it worked perfectly fine last week). I then started up the ExpressLRS Configuration, built the firmware for a random ESP32 RXs (which worked), went back to PlatformIO IDE and then suddenly the ESC32-C3 worked again, too. So something is going on here I don't understand.

I wonder, how to solve this? I guess I need to figure out which app uses which PlatformIO and then I need to decide either to use one core for both or separate them in a way they don't influence each other anymore.

There seems to be an installation of PlatformIO in my local python environment:
```
$ python --version
Python 3.10.5
$ which python
/usr/bin/python
$ pip list | grep platformio
platformio             6.1.3
$ which platformio
/home/cf/.local/bin/platformio
$ platformio --version
PlatformIO Core, version 6.1.3
```

(I get the exact same results inside the Visual Studio Code Terminal, so this seems to be the Python and PlatformIO Core used, although I checked the "user builtin..." options.)

Any ideas how to figure this out?

**Comment by jurgelenas** [comment]
This will be fixed in 1.4.4 release.

See details in https://github.com/ExpressLRS/ExpressLRS-Configurator/pull/362 and https://github.com/ExpressLRS/ExpressLRS-Configurator/pull/367
