### ISSUE TITLE
Can't use it...

### ISSUE THREAD

**Issue by chucky-whiskers** [ExpressLRS/ExpressLRS-Configurator#374]
## Expected Behavior
cannot find Platformio

program should have been able to build
## Current Behavior
does not build

dont know
## Steps to Reproduce
not sure

Failed to find Platformio on your computer. Trying to install it automatically...Installer version: 1.1.0
Platform: Windows-10
Python version: 3.11.0a4 (main, Jan 17 2022, 13:12:23) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Program Files\ExpressLRS Configurator\dependencies\windows_amd64\python-3.11.0a4.amd64\python3.exe
Creating a virtual environment at C:\Users\charl\.platformio\penv
Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues

1.

2.

3.

4.

## Possible Solution (Not obligatory)
My computer is running Windows 11

I may have closed the original window during first build
## Your Environment

- Operating System and version:
- TX hardware: TX16S/HappyModel ES900TX
- RX hardware: HappyModel ES900RX

**Comment by justinlampley** [comment]
If the build was abruptly stopped, the PlatformIO dependencies could be corrupted, clear the PlatformIO dependencies as well as the Firmware Files and try building again.

Support -> Clear PlatformIO Dependencies
Support -> Clear Firmware Files

If this doesn't solve the problem, post a message in the help-and-support channel on discord https://discord.com/channels/596350022191415318/798006228450017290
