### ISSUE TITLE
> Wi-Fi Device Select Error

### ISSUE THREAD

**Issue by malinhiles** [ExpressLRS/ExpressLRS-Configurator#384]
> If you are able to flash via FTDI, then perhaps try a full erase flash before flashing the latest firmware. We have seen issues before, and a full flash erase has fixed it before. If you would like you could try a new we-based flasher I'm working on https://pkendall64.github.io/elrs-web-flasher/ It has the option to select "Erase flash first" at the final step.

I had some time today to try this and probe around at this issue, and we are getting closer to tackling the issue, but we aren't completely there.  

![elrs1](https://user-images.githubusercontent.com/93371446/189211351-cde5c9d3-aa8d-496e-a4a8-e24e8b0cdfad.png)
I can't select the receiver as the WIFI device for flashing using the blue "SELECT" button in the bottom right. It gives the above shown error when I try to. If I then manually paste the receiver's IP into the "Wi-Fi Device Selection" box, I can proceed through to the flashing page where it attempts to upload and flash the firmware to the receiver, but the flash fails due to a target mis-match, even though I am using what I believe to be the correct target, according to the receivers documentation. 
![elrs2](https://user-images.githubusercontent.com/93371446/189210514-3494a152-a1ad-4bf1-ae72-8a1bb509886e.png)

Force Flash option didnt help here either

Any thoughts on this? I feel I'm starting to see light at the end of the tunnel lol

_Originally posted by @malinhiles in https://github.com/ExpressLRS/ExpressLRS/issues/1768#issuecomment-1241151461_

**Comment by justinlampley** [comment]
The web flasher and the configurator do not use the exact same target names in all instances, so when you are trying to select the WIFI device in the configurator after flashing via the elrs web flasher it does not recognize the target name and therefore cannot select the correct device.  You will need to manually select the device, as you have done.

Force flashing from the configurator should work, but if it isn't, a workaround is to build the firmware and then upload it using the devices web page.  You can get to the devices web page by either clicking on the DNS or IP address in the configurator.
