### ISSUE TITLE
Configurator v1.4.2 / ELRS V3.0.0 final: Flashing Matek R24-D error "Wrong target selected"

### ISSUE THREAD

**Issue by blockfeed** [ExpressLRS/ExpressLRS-Configurator#385]
## Expected Behavior

Flash Matek R24-D using Configurator 1.4.2, using Betaflight Passthrough.

## Current Behavior

Flash fails with:
```

======== PASSTHROUGH INIT ========
  Trying to initialize /dev/ttyACM0 @ 420000

Attempting to detect FC UART configuration...
    ** Serial RX config detected: 'serial 7 64 115200 57600 0 115200'
Enabling serial passthrough...
  CMD: 'serialpassthrough 7 420000'
======== PASSTHROUGH DONE ========
======== RESET TO BOOTLOADER ========
  * Using full duplex (CRSF)
Wrong target selected your RX is 'MATEK_2400_RX', trying to flash 'MATEK_2400_RX_R24D'

*** [upload] Error 254
```

## Steps to Reproduce

1. Connect quad with R24-D, configure for Passthrough flashing. 

2. Configure and compile as usual.

3. Flash using USB

## Possible Solution (Not obligatory)

If the flash is retried using the Retry button, or via `Cannot detect RX target, blindly flashing!`, the receiver accepts the binary and the flash succeeds. The TX and quad respond normally after flashing.

## Context

I am upgrading from 2.5.1 using Betaflight Passthrough. Previously, the receivers were flashed with Diversity disabled (only using one antenna).

## Your Environment

- Operating System and version: Linux / arch
- TX hardware: TX16S, EdgeTX 2.7, ELRS 3.0.0, Configurator 1.4.2
- RX hardware: Matek R24-D (only one antenna is connected in port 2)
- 
I have 3 quads with identical hardware configuration. Two have responded in this way and I have a third that is available for testing. 

This appears to be similar to #359.

The issue also appears in the Nightly builds (v20220907.31504.0).

Thanks for your assistance!

**Comment by justinlampley** [comment]
When switching between targets, MATEK_2400_RX -> MATEK_2400_RX_R24D, it is expected that you will receive a target mismatch error.  The firmware flashing tools only know what the current firmware target is and that you are trying to flash something different than what is currently on the device.  If you know the firmware is correct for the device, use the force flash option to ignore the mismatch error.

**Comment by blockfeed** [comment]
The target did not change, and this is a new install. So previously the non-diversity firmware was flashed, it seems.

**Comment by jurgelenas** [comment]
Just force flash the correct target to your receiver @blockfeed. Thanks for reporting this thought! We will try to improve documentation regarding this.
