### ISSUE TITLE
Add hash and GPG signature

### ISSUE THREAD

**Issue by Markus40** [ExpressLRS/ExpressLRS-Configurator#387]
I always feel a bit uneasy about downloading software that is not signed. Granted, it's not that big a problem when it comes to a site like github versus self-hosted websites, but it would still create another layer of security to make sure you're not downloading malware.

**Comment by jurgelenas** [comment]
Hey @Markus40!

I want to address adding artifact hashes and application binary signing separately.

#### Artifact hashes

I agree that this might be useful. But I have failed to find a way how to collect SHA256 for each artifact and add it to the GitHub release page. I have no interest in doing this process manually.

#### Application binary signing 

You are downloading application binaries through a secure connection from github.com. Nobody is going to intercept your network connection unless your device already trusts the malicous CA root.

Application signing is a different process for each operating system/package type that we support. You can read it more about it here: https://www.electron.build/code-signing.html#how-to-disable-code-signing-during-the-build-process-on-macos.

At this time, I prefer to focus our small team efforts elsewhere.

**Comment by Markus40** [comment]
I use the .deb package, and as long as there are no automatic updates, I have to download each new version manually. If malware has been uploaded and no one has noticed it yet, I can get it that way. It would also be difficult to inform people who downloaded the application during that period.

Malware is often uploaded from the owner's account because session tokens or emails have been compromised. A signature would prevent automated attacks quite well (as long as users verify the signature) and make manual ones a lot more difficult.

I can understand that you have to allocate limited development resources and focus on other things. I hope it will be reconsidered in the future when more time is available.
