### ISSUE TITLE
Upstream udev rule

### ISSUE THREAD

**Issue by razzeee** [ExpressLRS/ExpressLRS-Configurator#392]
Hey as far as I understood the right thing to do with those udev rules would be to upstream them. So they wouldn't be needed here anymore.

The correct way to do that seems to be to add the devices to this [systemd/systemd@main/hwdb.d](https://github.com/systemd/systemd/tree/main/hwdb.d?rgh-link-date=2022-07-27T07%3A56%3A57Z)

I'm not sure if it fits in one of those files. Otherwise you would need to add a new one, here's an example PR how to do that. https://github.com/systemd/systemd/pull/22730

**Comment by jurgelenas** [comment]
Thanks @razzeee. This looks like an excellent suggestion. I have forwarded it to the platformio organization: https://github.com/platformio/platformio-core/issues/4438
