### ISSUE TITLE
remove old/existing .pio folders before building this

### ISSUE THREAD

**Issue by sercona** [ExpressLRS/ExpressLRS-Configurator#396]
## Expected Behavior

building on linux should work, but it fails if you have an old .pio folder 

## Current Behavior

huge stack trace, pointing to lots of issues; but tldr: moving old $HOME/.pio to some other name (to move it out of the way) allows a full download/config/build to work.

## Steps to Reproduce

I had an older .pio in my home from when I was building 3d printer (ender 3) firmware.  my system is mint 20.3 una, and I have latest kernel and userland installed.

run the configurator and it will complain as:

    data: 'Error: Traceback (most recent call last):\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/__main__.py", line 102, in main\n' +
      '    cli()  # pylint: disable=no-value-for-parameter\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__\n' +
      '    return self.main(*args, **kwargs)\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/click/core.py", line 1055, in main\n' +
      '    rv = self.invoke(ctx)\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/cli.py", line 71, in invoke\n' +
      '    return super().invoke(ctx)\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke\n' +
      '    return _process_result(sub_ctx.command.invoke(sub_ctx))\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke\n' +
      '    return ctx.invoke(self.callback, **ctx.params)\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/click/core.py", line 760, in invoke\n' +
      '    return __callback(*args, **kwargs)\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func\n' +
      '    return f(get_current_context(), *args, **kwargs)\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/run/cli.py", line 144, in cli\n' +
      '    process_env(\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/run/cli.py", line 201, in process_env\n' +
      '    result = {"env": name, "duration": time(), "succeeded": ep.process()}\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/run/processor.py", line 83, in process\n' +
      '    install_project_env_dependencies(\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/package/commands/install.py", line 132, in install_project_env_dependencies\n' +
      '    _install_project_env_libraries(project_env, options),\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/package/commands/install.py", line 247, in _install_project_env_libraries\n' +
      '    env_lm.install(\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/_install.py", line 48, in install\n' +
      '    pkg = self._install(spec, skip_dependencies=skip_dependencies, force=force)\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/_install.py", line 92, in _install\n' +
      '    self.install_dependencies(pkg, print_header=False)\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/_install.py", line 140, in install_dependencies\n' +
      '    self.install_dependency(dependency)\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/library.py", line 89, in install_dependency\n' +
      '    not_builtin_conds.append(not self.is_builtin_lib(spec.name))\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/library.py", line 120, in is_builtin_lib\n' +
      '    for storage in cls.get_builtin_libs():\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/util.py", line 56, in wrapper\n' +
      '    self.cache[key] = (time.time(), func(*args, **kwargs))\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/library.py", line 105, in get_builtin_libs\n' +
      '    for storage in p.get_lib_storages():\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/platform/base.py", line 216, in get_lib_storages\n' +
      '    pkg = self.get_package(opts["package"])\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/platform/_packages.py", line 29, in get_package\n' +
      '    return self.pm.get_package(spec or self.get_package_spec(name))\n' +
      '  File "/home/bryan/.platformio/penv/lib/python3.8/site-packages/platformio/platform/_packages.py", line 21, in get_package_spec\n' +
      '    owner=self.packages[name].get("owner"),\n' +
      "KeyError: 'framework-stm32cube'\n" +
      '\n' +
      '============================================================\n' +
      '\n' +
      'An unexpected error occurred. Further steps:\n' +
      '\n' +
      '* Verify that you have the latest version of PlatformIO using\n' +
      '  `pip install -U platformio` command\n' +
      '\n' +
      '* Try to find answer in FAQ Troubleshooting section\n' +
      '  https://docs.platformio.org/page/faq/index.html\n' +
      '\n' +
      '* Report this problem to the developers\n' +
      '  https://github.com/platformio/platformio-core/issues\n' +
      '\n' +
      '============================================================\n' +
      '\n'

## Possible Solution (Not obligatory)

the way I worked around it was to move $HOME/.pio to $HOME/.pio-old and then re-run the config and all worked after that.

## Context

first time user trying to create a set of fw's for the transmitter and receiver.

## Your Environment

building for jumper transmitter, but it does not matter what target you pick; the issue seemed to be an existing .pio from another unrelated project.

**Comment by sercona** [comment]
![elrs-tx](https://user-images.githubusercontent.com/11081206/195478583-cbf6930a-3d0c-4098-b158-e9989ab49317.jpeg)

once I moved $HOME/.platformio to something else, I was able to build and flash and took my first elrs miniquad flight today.

seeing the web browser come up was also really nice.

good job, guys, overall (both for this project and the firmware for the radios).

**Comment by jurgelenas** [comment]
Thanks for the report @sercona. I am glad that you are enjoying ExpressLRS.

I believe that removing platformio files before the installation is a bit too intrusive. I think it is platformio responsibility to maintain backward compatibility with previous versions.

Happy Flying!

**Comment by sercona** [comment]
perhaps just document this, then?  it will save people a LOT of time if they know that this could happen.

I agree that moving old pio out of the way via script is wrong.  the user should have that decision.  but perhaps a check to see if one exists and a message to the user to say that they MIGHT want to move old pio's out of the way, first?

better to fix it, too; I agree, but in the meantime, a documentation fix could be enough.  goal is to save people trying to 'debug' this and spending days or longer when its just a conflict and those happen enough in the real world but part-time sw guys might not realize this.

its searchable here, at least, so at least we have that.  just wanted to save people time on something that might stop them from using this great tool.
