### ISSUE TITLE
ModuleNotFoundError: No module named 'serial'

### ISSUE THREAD

**Issue by PSi86** [ExpressLRS/ExpressLRS-Configurator#400]
## Expected Behavior

Flashing a Firmware to an ELRS RX (EP2) should work using BFPassthrough.

## Current Behavior

When the flashing is about to start the process returns with:
```
Traceback (most recent call last):
  File "C:\Users\Peter\AppData\Roaming\ExpressLRS Configurator\firmwares\github\ExpressLRS\src\python\BFinitPassthrough.py", line 1, in <module>
    import serial, time, sys, re
ModuleNotFoundError: No module named 'serial'
*** [upload] Error 1
```

## Steps to Reproduce

Select any ELRS RX device connected to a BF FC, build a firmware and try flashing using BFPassthrough.

## Possible Solution (Not obligatory)

Check / install correct version of pyserial if that could be the cause.

## Context
The older configurator 1.4.2 works fine.

## Your Environment

- Operating System and version: Windows 10 Pro 21H2
- ELRS Configurator Version 1.5.0
- TX hardware: RM Zorro
- RX hardware: HM EP2

**Comment by deadbytefpv** [comment]
Is the ExpressLRS Configurator installed for "Current User" or "All Users"?
It shouldn't matter that much technically, but users had much more success when I advice them to reinstall with the option "Current User" instead of "All Users".

Unplug-replug USB from PC/FC before each attempt.

**Comment by PSi86** [comment]
It is istalled for the current user only.
I now installed for all users and the error remains the same.

**Comment by jurgelenas** [comment]
@PSi86 can you upload your application logs over here?

Another way of sharing them would be sending logs privately to me over discord.

**Comment by PSi86** [comment]
Thank you! Check your Inbox :)

**Comment by PSi86** [comment]
@jurgelenas Thanks for your work. Will test tomorrow but looking at the PRs I am very confident!
