### ISSUE TITLE
JHEMCU 915MHz

### ISSUE THREAD

**Issue by santersa** [ExpressLRS/ExpressLRS-Configurator#414]
## Summary
We have support JHEMCU2.4GHz only. When the JHEMCU 915MHz support will be able?
Thank you.

**Comment by jurgelenas** [comment]
> ## Summary
> 
> We have support JHEMCU2.4GHz only. When the JHEMCU 915MHz support will be able? Thank you.

We have zero communication with JHEMCU about any 915MHz TX modules or receivers. That is all I know for now.
