### ISSUE TITLE
Betafpv SuperD device not shown on target page

### ISSUE THREAD

**Issue by mkostner** [ExpressLRS/ExpressLRS-Configurator#434]
on v1.5.2 BetaFPV SuperD 2.4Ghz is not shown but  in v1.5.1 is working correctly. i deleted the json files and keep only BetaFpv but it also not shown.

 i deleted the json files and keep only BetaFpv but it also not work

**Comment by jurgelenas** [comment]
Please use `3.x-maintenance` branch. In 1.5.1 BetaFPV SuperD was not configured correctly on the configurator side.

This will be fully fixed once ExpressLRS 3.1.1 is released. At the moment we plan to release this firmware version this Friday (Dec 9th).
