### ISSUE TITLE
Add 'erase before flashing' option in configurator

### ISSUE THREAD

**Issue by ELongRange** [ExpressLRS/ExpressLRS-Configurator#436]
There can be a problem with the LUA script loading/executing when updating ELRS from 2.5.1 to 3.0 plus;
[elrs issue #1952](https://github.com/ExpressLRS/ExpressLRS/issues/1952)

Problem can be fixed with PKendall's web flasher using 'erase flash first?' option, I would very much like to see this option in configurator.
[pkendall64 web flasher](https://pkendall64.github.io/elrs-web-flasher/)

![erase elrs](https://user-images.githubusercontent.com/118563673/206140584-c87c57a5-ae00-42a5-8ae1-5f55495bf094.PNG)

**Comment by jurgelenas** [comment]
Closing in favor of https://github.com/ExpressLRS/ExpressLRS-Configurator/issues/513

**Comment by ELongRange** [comment]
Thank you
