### ISSUE TITLE
Versions prior to 2.5 cannot be built

### ISSUE THREAD

**Issue by qvasic** [ExpressLRS/ExpressLRS-Configurator#437]
## Expected Behavior

Versions like 2.4 and prior are successfully built using ELRS Configurator.

## Current Behavior

Version 2.4 cannot be built.

## Steps to Reproduce

1. Launch ELRS Configurator.

2. Select version 2.4.

3. Select appropriate target hardware, build parameters.

4. Start the build.

5. Wait for the build to finish.

## Possible Solution (Not obligatory)

Remove versions that cannot be built from Configurator.
Or at least mark them as "OBSOLETE", "CANNOT BE BUILT", etc.

## Context

Clean, freshly updated official installation of ELRS Configurator - version 1.5.3.

## Your Environment

- Operating System and version:
- TX hardware: BetaFPV micro 2.4 TX.
- RX hardware: iFlight 2.4 RX.

**Comment by jurgelenas** [comment]
ExpressLRS 2.X is no longer supported. Please migrate to 3.X.
