### ISSUE TITLE
Can I mix R9 hardware?

### ISSUE THREAD

**Issue by aowi7280** [ExpressLRS/ExpressLRS-Configurator#442]
## Summary

I have a R9 ACCST module, but my receiver may be dead. I can't find another. Can I use a ACCESS or other type receiver like Happymodel?

**Comment by jurgelenas** [comment]
Yes you can mix between 900MHz transmitters and receivers and between 2.4GHz transmitters and receivers. But you can not mix 900MHz hardware with 2.4GHz hardware.
