### ISSUE TITLE
Unsupported versions should be marked as OBSOLETE in the Configurator

### ISSUE THREAD

**Issue by qvasic** [ExpressLRS/ExpressLRS-Configurator#443]
## Expected Behavior

Per https://github.com/ExpressLRS/ExpressLRS-Configurator/issues/437 versions before 3.0 are no longer supported. Those versions should be marked as OBSOLETE or even removed from the Configurator.

## Current Behavior

Trying to build earlier versions is possible, but fails with unclear messages.

## Steps to Reproduce

1. Launch Configurator.

2. Select version 2.4 or earlier.

3. Select appropriate hardware target, build parameters. Start the build.

4. Build fails with unclear messages.

## Possible Solution (Not obligatory)

Versions that cannot be built should be marked as OBSOLETE or even removed from the list, so people don't waste their time trying to build unbuildable versions and then trying to figure out why the build failed.

## Context

I wasted 30-60 minutes of my time trying to figure out why firmware aren't building right. This tiny fix could save some time for the people.

## Your Environment

- Operating System and version: Windows 11, ELRS Configurator - version 1.5.3
- TX hardware: BetaFPV micro 2.4 500mw
- RX hardware: iFlight 2.4 RX

**Comment by jurgelenas** [comment]
This was fixed in https://github.com/ExpressLRS/ExpressLRS-Configurator/commit/e08fbdda1d659558e6d645c42289f9008a532553.
