### ISSUE TITLE
Cannot compile 3.1.1 for HappyModel ES24TX Slim Pro module

### ISSUE THREAD

**Issue by cynfewl** [ExpressLRS/ExpressLRS-Configurator#449]
## Expected Behavior

Compiling 3.1.1 for HappyModel ES24TX Slim Pro

## Current Behavior

Compiling .pio\build\HappyModel_ES24TX_Pro_Series_2400_TX_via_UART\lib52b\NimBLE-Arduino@1.4.0\nimble\porting\npl\freertos\src\npl_os_freertos.c.o
.pio/libdeps/HappyModel_ES24TX_Pro_Series_2400_TX_via_UART/NimBLE-Arduino@1.4.0/src/nimble/porting/nimble/src/nimble_port.c:29:10: fatal error: ../../npl/freertos/include/nimble/nimble_port_freertos.h: No such file or directory
 #include "../../npl/freertos/include/nimble/nimble_port_freertos.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pio\build\HappyModel_ES24TX_Pro_Series_2400_TX_via_UART\lib14a\ESP32-BLE-Gamepad\BleConnectionStatus.cpp.o
Compiling .pio\build\HappyModel_ES24TX_Pro_Series_2400_TX_via_UART\lib14a\ESP32-BLE-Gamepad\BleGamepad.cpp.o
*** [.pio\build\HappyModel_ES24TX_Pro_Series_2400_TX_via_UART\lib52b\NimBLE-Arduino@1.4.0\nimble\porting\nimble\src\nimble_port.c.o] Error 1
========================= [FAILED] Took 52.33 seconds =========================

Environment                                    Status    Duration
---------------------------------------------  --------  ------------
HappyModel_ES24TX_Pro_Series_2400_TX_via_UART  FAILED    00:00:52.326
==================== 1 failed, 0 succeeded in 00:00:52.326 ====================

## Steps to Reproduce

Install ExpressLRS Configurator v1.5.3.
Attempt to build 3.1.1 firmware for HappyModel ES24TX Slim Pro module.

## Possible Solution (Not obligatory)

Not sure of the fix.

## Your Environment

- Operating System and version: Windows 11 Pro
- TX hardware: HappyModel ES24TX Slim Pro
- RX hardware: HappyModel EP1/2 and AIO whoop boards

**Comment by jurgelenas** [comment]
Hey @cynfewl,

It looks like your platformio dependencies got corrupted. Can you please try clearing all files through "Support" menu?

For the future of this issue please join our discord:

https://github.com/ExpressLRS/ExpressLRS-Configurator#need-help-confused-join-the-community
