### ISSUE TITLE
Add localization to the Configurator

### ISSUE THREAD

**Issue by McGiverGim** [ExpressLRS/ExpressLRS-Configurator#463]
I think it will be interesting, for non English users to localize the Configurator.

The first step is move all the strings to a file. I think is a good moment now that the Configurator is not too big.
After that, we can add some Actions to upload and download translations to a localization portal. I'm a developer of Betaflight 
and we use Crowdin for our localizations for example.

I'm pretty sure the users will help to localize it. For example I will localize it to Spanish without problem.

**Comment by L1cardo** [comment]
Agreed!
ELRS is now really popular in China, I am always asked some basic translation issues by other pilots. 
I can help with Chinese localization.

**Comment by jurgelenas** [comment]
For anyone looking into this, it looks like https://formatjs.io/ is the best option with their `react-intl` library.
