### ISSUE TITLE
Configurator will not download

### ISSUE THREAD

**Issue by Smitty83** [ExpressLRS/ExpressLRS-Configurator#465]
## Summary

I can not get the configurator to download no matter what I do. And I found an answer to download CP210x drivers but that will not work either.

**Comment by Smitty83** [comment]
> ## Summary
> I can not get the configurator to download no matter what I do. And I found an answer to download CP210x drivers but that will not work either.

I have Windows 11

**Comment by jurgelenas** [comment]
Please use our discord server https://discord.gg/dS6ReFY for generic questions.
