### ISSUE TITLE
Configurator putting files in `C:\` on Windows

### ISSUE THREAD

**Issue by chakflying** [ExpressLRS/ExpressLRS-Configurator#468]
## Expected Behavior

The configurator should use `%appdata%` or at least the user profile folder to store its working files.

## Current Behavior

A folder `.expresslrs-configurator` is created directly under `C:\`
I was using older versions (around `1.5`) and it didn't seem to do this.

![image](https://user-images.githubusercontent.com/3271800/210642232-66d4266a-14ad-4ea6-8393-99e70a7a9c9b.png)

## Steps to Reproduce

1. Install latest configurator on Windows using the `.exe`
2. Start configurator
3. Notice folder created in `C:\`

## Possible Solution (Not obligatory)

Place folder in a more reasonable location.

## Your Environment

- Operating System and version: Windows 11 22H2
- TX hardware:
- RX hardware:

**Comment by jurgelenas** [comment]
https://github.com/ExpressLRS/ExpressLRS-Configurator/pull/430

This was done on purpose in this PR. Some platformio build tools were facing issues with file paths that contains cp946 encoded characters. It was causing build failures for ExpressLRS users in Asian countries.

One of the examples:

```
for example, an error message `strxtensa-esp32-elf-g++: error: C:\Users\\xbc\xb1\xc1\xd8\AppData\Roaming\ExpressLRS Configurator\firmwares\github\ExpressLRS\src\.pio\build\HappyModel_EP_Dual_2400_RX_via_BetaflightPassthrough\tmpp7qtlun_.tmp: No such file or directory`

`BC B1 C1 D8` is 선준 (my username) in cp949 encoding, but if the location is converted as utf-8 in some part of the compile chain then it could only be accessible by `EC 84 A0 EC A4 80` (선준 in utf8)... complicated.
```

We have no fast way (or maybe even no way at all) to fix this upstream, so the decision was made to work around this issue. 

As a less offensive solution we could use `c\.expresslrs-configurator` path only if appdata path contains offending characters. Let me know if you would be willing to contribute this.

**Comment by chakflying** [comment]
`main.dev.ts:65`
```js
function isASCII(str: string) {
  return /^[\x00-\x7F]*$/.test(str);
};

const isWindows = process.platform.startsWith('win');
const isMacOS = process.platform.startsWith('darwin');
let userDataDirectory = app.getPath('userData');

if (isWindows) {
  const dirtyUserDataDirectory = app.isPackaged
    ? path.join('c:', `.${packageJson.name}`)
    : path.join('c:', `.${packageJson.name}-dev`);
  try {
    if (!isASCII(userDataDirectory)) {
      mkdirp.sync(dirtyUserDataDirectory);
      userDataDirectory = dirtyUserDataDirectory;
      logger.log(
        `Non-ASCII path detected, using ${dirtyUserDataDirectory} directory for firmware storage`
      );
    } else {
      logger.log(`appdata path ${userDataDirectory} should be safe to use`)
    }
  } catch (err) {
    logger.error(
      'failed to create c:/.expresslrs directory, will use usual path',
      undefined,
      {
        err,
      }
    );
  }
}
```
source: [stackoverflow](https://stackoverflow.com/a/14313213)

tested this works on your Korean example.
