### ISSUE TITLE
Select expresslrs-configurator.log file when opening logs folder from the UI

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/ExpressLRS-Configurator#47]

**Comment by jurgelenas** [comment]
It looks like it is [already implement](https://github.com/ExpressLRS/ExpressLRS-Configurator/blob/f3120b8a363249d1ce69ef5efed6a743f6e4d0ba/src/main.dev.ts#L388), but at least on my computer it does not behave properly. It select `logs` folder instead of `expresslrs-configurator.log` when calling `shell.showItemInFolder(logsPath)`

**Comment by justinlampley** [comment]
The issue seems to be that shell.showItemInFolder should be being passed logsLocation, which is the logsPath + logsFilename, instead of logsPath which is just the path to the logs folder.  I will submit a pull request to fix the issue.
