### ISSUE TITLE
ExpressLRS configurator 1.5.5 on fedora Silverblue

### ISSUE THREAD

**Issue by zandorsp** [ExpressLRS/ExpressLRS-Configurator#470]
## Expected Behavior

ExpressLRS can compile ESP targets on Fedora Silverblue

## Current Behavior

It show error on Python:
`Processing DIY_2400_TX_ESP32_SX1280_E28_via_UART (platform: espressif32@5.2.0; board: esp32dev; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
UID bytes: 65,137,124,13,11,60
***Building for ESP32 Platform
ValueError: AST node column range (0, 22) for line range (-1, 252) is not valid:
  File "/var/home/zandor/.platformio/penv/lib64/python3.11/site-packages/platformio/builder/main.py", line 186:
    env.SConscript(item, exports="env")
  File "/var/home/zandor/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/var/home/zandor/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/var/home/zandor/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 72:
    build_common(env, "index.html", not '_RX_' in target_name)
  File "/var/home/zandor/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 57:
    build_html(mainfile, "INDEX_HTML", out, env, isTX)
  File "/var/home/zandor/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_html.py", line 35:
    template = engine.get_template(mainfile)
  File "/var/home/zandor/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/external/wheezy/template/engine.py", line 57:
    self.compile_template(name)
  File "/var/home/zandor/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/external/wheezy/template/engine.py", line 110:
    render_template = self.compiler.compile_source(
  File "/var/home/zandor/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/external/wheezy/template/compiler.py", line 27:
    compiled = compile(node, name, "exec")
========================== [FAILED] Took 1.24 seconds ==========================
Environment                            Status    Duration
-------------------------------------  --------  ------------
DIY_2400_TX_ESP32_SX1280_E28_via_UART  FAILED    00:00:01.239
==================== 1 failed, 0 succeeded in 00:00:01.239 ====================`

## Steps to Reproduce

1. Install Fedora Silverblue on a virtual machine or fedora toolbx container on any linux https://containertoolbx.org/

2. Install expresslrs-configurator-1.5.5.zip on any folder

3. Try to compile any ESP target

## Possible Solution (Not obligatory)

On a arch linux container (https://wiki.archlinux.org/title/Toolbox) the compile was a successful . 

## Context

I was trying to update my NamimnoRC FLASH 2400 ESP RX and Happymodel EP2 both unsuccessful 

I tried the R9 too and was sucessuful 

## Your Environment

- Operating System and version:
Fedora Silverblue 37 and Fedora Linux 37 (Container Image) x86_64 (same error)
- TX hardware:
Happy model pro series 2.4Ghz
Frsky R9 Lite Pro
- RX hardware:
NamimnoRC FLASH 2400 ESP RX 
Happymodel EP2
FrSky R9mm mini

**Comment by jurgelenas** [comment]
Have you tried python 3.10?

**Comment by zandorsp** [comment]
Works with this somewhat ugly workaround:

`$toolbox enter fedora-toolbox-37`
`$sudo dnf install python3.10 `
`$cd Apps/expresslrs-configurator-1.5.5/ ` installation path
`$sudo python3.10 -m venv appenv`  make a Python 3.10 venv
`$source appenv/bin/activate`
`(appenv) $./expresslrs-configurator`

On support pane clear platformio dependences and select any esp target and build one.

On the next compilation as the expresslrs-configurator's virtual env is the correct one isn't necessary to enter the venv again.

**Comment by zandorsp** [comment]
Or simply ...
`$toolbox create --release 36`
`$toolbox enter fedora-toolbox-36`
 and be happy as `$python3 --version`
Python 3.10.9

**Comment by zandorsp** [comment]
The flatpak version works very well too:
flatpak install io.github.betaflight.BetaflightConfigurator

Please devs, consider an official recommendation and support of the flatpak version of the configurator

**Comment by jurgelenas** [comment]
> Please devs, consider an official recommendation and support of the flatpak version of the configurator

Added to our releases page. Thanks.

**Comment by zandorsp** [comment]
The command is wrong. The link is for the Betaflight configuration and not the é ExpressLRS configurator 

The correct one is:
flatpak install flathub org.expresslrs.ExpressLRSConfigurator

Sorry, my fault.
