### ISSUE TITLE
Configurator doesn't show new targets from PR

### ISSUE THREAD

**Issue by lesharodin** [ExpressLRS/ExpressLRS-Configurator#473]
## Expected Behavior

Configurator must see new targets from PR

## Current Behavior

Doesn't show targets from PR https://github.com/ExpressLRS/ExpressLRS/pull/2042
![image](https://user-images.githubusercontent.com/12091173/213622920-9d7e2939-1b20-468b-8591-3df2dc79360c.png)

## Steps to Reproduce

1. Pick PR https://github.com/ExpressLRS/ExpressLRS/pull/2042

2. Search for new target

## Possible Solution (Not obligatory)

Some time ago it was working fine

## Your Environment

- Operating System and version: Win 10, ExpressLRS Configurator 1.5.5

**Comment by jurgelenas** [comment]
These targets need to be added to the configurator app separately :) Once https://github.com/ExpressLRS/ExpressLRS-Configurator/pull/429 is merged it will be fully automatic.
