### ISSUE TITLE
Tooltips for Regulatory Domain links point to different locations

### ISSUE THREAD

**Issue by n4t3y** [ExpressLRS/ExpressLRS-Configurator#477]
When hovering over the tooltip for each of the 2400 regulatory domains the links point to different locations:

- ISM: https://www.expresslrs.org/2.0/software/user-defines/#regulatory-domain
- EU_CE: https://www.expresslrs.org/release/software/user-defines/#regulatory-domain **(not a valid link)**

It would make sense for them to both point to the following link instead:
https://www.expresslrs.org/3.0/quick-start/firmware-options/#regulatory-domains

**Comment by jurgelenas** [comment]
Thank you @n4t3y! This will be fixed once #415 is merged.
