### ISSUE TITLE
Add button to retry Upload without recompiling

### ISSUE THREAD

**Issue by kolins-cz** [ExpressLRS/ExpressLRS-Configurator#485]
When flashing receiver over UART, it never works on the first try. Boot button/jumper was not held right during power on, wrong COM selected,  RX/TX cables gets reversed, disconnected... I usually do this with some temporary, unreliable connection.

Waiting for recompilation is driving me mad. Even I have decent PC, it still takes 20-30s. And it is absolutely unnecessary to recompile.

And if not a button, could there be full command for running esptool in the log? When I face same problem with Arduino, I can copy the upload command, paste it to cmd.exe and re-run upload as many times as I need in rapid succession without recompiling.

Thanks

**Comment by jurgelenas** [comment]
Thanks for the idea. We are going to solve it in a different way - cached builds from the cloud will be used, so there will be no compile step at all :)

Please check our work in progress: https://github.com/ExpressLRS/ExpressLRS-Configurator/pull/429
