### ISSUE TITLE
Using express LRS configurator on linux

### ISSUE THREAD

**Issue by albfan** [ExpressLRS/ExpressLRS-Configurator#486]
## Summary

I use R9M TX
build works correctly on linux, but after that flash fails.

Now there's STMCubeProgrammer for linux, I use it to disable read out protection, but I need to run in with sudo.

I tried to rename firmware to .bin and flash directly on STMCubeProgrammer but nothing happens

I tried express LRS configurator in windows version and flash works, I see device blinking red and green.

- running express LRS configurator in --sandbox mode will help with access device?
- any chmod or group to join to access as normal user the ST-Link? Probably this is offtopic for express LRS configurator, but as it does everything would be great to understand why flash fails

**Comment by jurgelenas** [comment]
Have you tried these? https://github.com/ExpressLRS/ExpressLRS-Configurator#linux

**Comment by jurgelenas** [comment]
Try asking this question in our [Discord server](https://discord.gg/dS6ReFY). You are more likely to get help there.

**Comment by albfan** [comment]
Thanks a lot!
