### ISSUE TITLE
Building Backpack firmware fails due to invalid environment name

### ISSUE THREAD

**Issue by jduerr** [ExpressLRS/ExpressLRS-Configurator#504]
## Expected Behavior

After selecting target device category (i.e. TX), proper Device (i.e. Radiomaster Zorro TX Backpack), selecting flashing method (i.E. EdgeTxPassthrough) and selecting serial device - Hitting the build button should start the build process and finish building the firmware successfully. 

## Current Behavior

Starting the build process by hitting the build button yields an error with following message:
`Error: Invalid environment name 'HDZero_RX5.1_ESP32_Backpack_via_UART'. The name can contain alphanumeric, underscore, and hyphen characters (a-z, 0-9, -, _)`

## Steps to Reproduce

1. Open ExpressLRS Configurator

2. Select "Backpack" in the left hand side bar

3. Choose Release 1.2.0, Target TX, Device RadioMaster Zorro TX Backpack and Flashing Method "EdgeTxPassthrough

4. Select your serial device from pull down menu 

5. Click on "build" button. 

## Context

I was trying to build the backpack firmware for my Radiomaster ELRS Transmitters (Zorro and TX16S) so I can make use of my HDZero Goggles Backpack functionality. But I fail trying to build the firmware like described above.

I did not change anything on the boilerplate code after downloading the configurator. Even did a fresh install of elrs configurator on another machine to verify but immediately experienced the exact same behavior.

## Your Environment

- Operating System and version: 
-- Apple Studio M1 running macOS 13.3.1
-- Samsung Galaxy Book running Windows 11
- ExpressLRS Configurator versions tested:
-- V1.5.7
-- V1.5.9
-- Nightly 20230511.4148.0 
- TX hardware: Radiomaster Zorro ELRS

<img width="1385" alt="Bildschirmfoto 2023-05-17 um 07 30 18" src="https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/1424072/9e26c2ca-9e70-4662-a1be-a36cabde2e83">
<img width="1386" alt="Bildschirmfoto 2023-05-17 um 07 30 34" src="https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/1424072/87384da8-0e92-4839-8671-e25ef7ef9558">

**Comment by justinlampley** [comment]
See https://github.com/ExpressLRS/ExpressLRS/issues/2217

**Comment by jurgelenas** [comment]
Fixed in https://github.com/ExpressLRS/Backpack/releases/tag/1.3.0
