### ISSUE TITLE
Added RC1 to Flathub beta

### ISSUE THREAD

**Issue by razzeee** [ExpressLRS/ExpressLRS-Configurator#518]
Hey,

this is more of an FYI.

I've added the RC1 to the beta flathub remote

Add the beta remote, if you don't already have it:
```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
```

Then install via:
```
flatpak install flathub-beta org.expresslrs.ExpressLRSConfigurator
```

I've also successfully used this to update my radiomaster zorro and happymodel ep2, without problems.

**Comment by jurgelenas** [comment]
Awesome. Thanks for testing!

We are really close to releasing 3.3, new backpack 1.4 and new configurator.
