### ISSUE TITLE
Error without log when building

### ISSUE THREAD

**Issue by nablabla** [ExpressLRS/ExpressLRS-Configurator#522]
I have tried this several times, it worked some days ago, now it just won't no matter how often I hit the BUILD button

## Expected Behavior
build FW

## Current Behavior
I am sorry, but there is NO log
![image](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/5704918/ae40b618-b422-4cf2-8bc5-be83f4ac3463)

## Steps to Reproduce
configurator v1.5.10
trying to bulid ELRS 3.2.1
![image](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/5704918/858bef99-735b-42b2-b134-307f14c80077)
I only hit BUILD, not FLASH

```
-DRegulatory_Domain_EU_CE_2400
-DMY_BINDING_PHRASE="***"
-DLOCK_ON_FIRST_CONNECTION
-DAUTO_WIFI_ON_INTERVAL="40"
-DHOME_WIFI_SSID="'***"
-DHOME_WIFI_PASSWORD="***"
-DFAST_SYNC
```
## Context
It worked in the past, now it doesn't, I tried multiple times

## Your Environment
- Operating System and version: Windows 22H2

**Comment by justinlampley** [comment]
Please post the latest log file that contains the failed build attempt, it would be good if you tried to do the build again and then get the log file to make sure the failure is at the very end of the file.  The folder that contains the log files can be accessed from the Configurator by going to Logs -> Open Logs Folder.

**Comment by jurgelenas** [comment]
Closing due to the lack of activity.

**Comment by nablabla** [comment]
Where do I find the log file?
