### ISSUE TITLE
New release 1.6.0-RC.1 does not have correct flashing options for hardware

### ISSUE THREAD

**Issue by Rickyrivers72** [ExpressLRS/ExpressLRS-Configurator#525]
When choosing methods the "Bootloader" option is missing.

## Expected Behavior
Device Category: FrSky 900 MHz
Category: FrSky R9M 900MHz TX
Update via **1. Stock_BL** and 2. Wifi and 3. STLink
## Current Behavior
Only 1. STLink and 2. Wifi options available when using older stable release of ELRS (rc1 does work)

## Steps to Reproduce
Under Official Releases, Select a version previous to 3.3.0-RC1
Device Category: FrSky 900 MHz
Category: FrSky R9M 900MHz TX

## Context
Stock bootloader is useful for updating and alot easier than ST-Link 

## Your Environment
Windows11

![elrs config error](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/137076568/9419f2fd-f503-4538-b356-9ee0ad69f66a)

**Comment by jurgelenas** [comment]
This is fixed in ExpressLRS 3.3 RC1. Please see the relevant pull request: https://github.com/ExpressLRS/ExpressLRS/pull/2224

**Comment by Rickyrivers72** [comment]
Please excuse my ignorance, but can you please explain how your link fixes this bug in the configurator? 
As it still stands, I cannot use this 1.6.0-rc1 CONFIGURATOR to update versions of ELRS **BEFORE 3.3.0-RC1**.

**Comment by pkendall64** [comment]
> Please excuse my ignorance, but can you please explain how your link fixes this bug in the configurator? As it still stands, I cannot use this 1.6.0-rc1 CONFIGURATOR to update versions of ELRS **BEFORE 3.3.0-RC1**.

The bug is fixed, I need to retroactively put the flasher into each of the version artifacts.
