### ISSUE TITLE
Cannot flash with Stock Bootloader method for ELRS version BEFORE latest nightly build: 3.2.1 etc.

### ISSUE THREAD

**Issue by Rickyrivers72** [ExpressLRS/ExpressLRS-Configurator#535]
When choosing methods the "Bootloader" option is missing.

Expected Behavior
Device Category: FrSky 900 MHz
Category: FrSky R9M 900MHz TX
Update via 1. Stock_BL and 2. Wifi and 3. STLink

Current Behavior
Only 1. STLink and 2. Wifi options available when using older stable release of ELRS (rc1 does work)

Steps to Reproduce
Under Official Releases, Select a version **previous to 3.3.0-RC1**
Device Category: FrSky 900 MHz
Category: FrSky R9M 900MHz TX

Context
Stock bootloader is useful for updating and alot easier than ST-Link, and the latest 3.3.0-RC1 is the ONLY available version for stock bootloader

Your Environment
Windows11

![image](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/137076568/25832b55-500e-4d26-931e-e568acb5e20a)

**Comment by jurgelenas** [comment]
There is no fix for it at the moment. This is a firmware issue (flashing methods are stored in targets.json) and it is solved only in 3.3 which is going to be released soon.

If you really want to use this new configurator with ExpressLRS version prior to 3.3 just rename `firmware.bin` to `firmware.elrs`. This how "special" stock_bl firmware is built internally.
