### ISSUE TITLE
Could not build 2.5.2 since last week

### ISSUE THREAD

**Issue by lesharodin** [ExpressLRS/ExpressLRS-Configurator#540]
## Expected Behavior

Firmware builds

## Current Behavior

Configurator and platformio want some file that does not exist, I can download it from main repo and place it to desired path than it builds

`Error 1
*** [.pio\build\DIY_2400_TX_ESP32_SX1280_E28_via_UART\lib76c\NeoPixelBus\internal\HtmlColorShortNames.cpp.o] Error 1
cc1.exe: fatal error: C:/Users/lesha/.platformio/platforms/espressif32@3.3.2/builder/target/DIY_2400_TX_ESP32_SX1280_E28.h: No such file or directory
compilation terminated.`

`compilation terminated.
*** [.pio\build\HappyModel_EP_2400_RX_via_WIFI\libf58\ESP8266WiFi\BearSSLHelpers.cpp.o] Error 1
cc1.exe: fatal error: C:\Users\lesha\.platformio\platforms\espressif8266\builder\target\DIY_2400_RX_ESP8285_SX1280.h: No such file or directory`

## Steps to Reproduce

1. Try  to build any 2.5.2 target

## Possible Solution (Not obligatory)

no idea

## Context

We need 2.5.2 to flash 3.x later, or for some poor guys using betafpv literadio

## Your Environment

- Operating System and version: win 10, 1.5.10

**Comment by jurgelenas** [comment]
2.5.2 version is no longer actively supported.
