### ISSUE TITLE
Matek target names all changed from 1.5.9

### ISSUE THREAD

**Issue by ror1948** [ExpressLRS/ExpressLRS-Configurator#554]
## Expected Behavior

Same target names as 1.5.9 should be used

## Current Behavior

target names changed which caused me to brick Matek-R24-V Rx because I could not find the target name used in 2.5
In 2.5 target was DIY_2400_RX_ESP8285_SX1280
The world can not keep changing docs to match the new configurator.

## Steps to Reproduce

just try to create new firmware for Matek R24-V Rx

1.

2.

3.

4.

## Possible Solution (Not obligatory)

keep the same target names as 1.5.9 and add new ones

## Context

upgrade Matek R24-V from 2.5 to 3.3

## Your Environment

- Operating System and version: win10
- TX hardware: tx16s latest nightly build with BetaFPV micro 1W
- RX hardware: Matek R24-V with PWM adapter and Rx

**Comment by ror1948** [comment]
talking about configurator version 1.6.0

**Comment by jurgelenas** [comment]
This device is not officially supported by ExpressLRS. This is why you need to use "DIY" / "Generic" device target.

As a side note, it is impossible to brick these devices, so you are still good to go :) Just flash it via UART using TX + RX pins with FTDI dongle.

**Comment by ror1948** [comment]
yes i managed to recover using uart. thanks

but that is not the target name i used the last time.
How are we to find out what target to use or should I say how do we know what the current programmer of the configurator has used.
There are years of docs released for that Rx and you should stick to the naming convention that has been used in the past to make it simpler for us the end user.

If it is an ELRS device then you should support it.
Why would you not support it?
It was supported in configurator 1.5.9

thanks for all the work you guys do.



________________________________

**Comment by jurgelenas** [comment]
> but that is not the target name i used the last time.

We still have DIY targets for actually DIY hardware. You have used a target meant for manufacturers to make new product development easier :) These "generic" targets are simply not intended for regular usage.

> If it is an ELRS device then you should support it.
> Why would you not support it?
> It was supported in configurator 1.5.9

You can not slap "ExpressLRS" on the device and expect the ExpressLRS team to support it. We have a program for new devices where we test the hardware, make sure that it is designed & calibrated properly. Nobody from the ExpressLRS team has this device.

I am not saying it's faulty, just that it is not really supported. 

> thanks for all the work you guys do.

Happy Flying!
