### ISSUE TITLE
Cannot import 2.5.2 targets in Configurator v1.6.0

### ISSUE THREAD

**Issue by CCNUI** [ExpressLRS/ExpressLRS-Configurator#560]
## Expected Behavior

I just updated from ELRS Configurator v1.5.9 to v1.6.0. 
I'm trying to open local folder "ExpressLRS-2.5.2\src".

## Current Behavior

However, I cannot open old targets's source dirctory in v1.6.0.

## Possible Solution (Not obligatory)

Add support for old directory format in ExpressLRS Configurator v1.6.0.

## Your Environment

- Operating System and version: Windows 11

**Comment by jurgelenas** [comment]
Please upgrade to ExpressLRS 3.X.
