### ISSUE TITLE
Configurator can't build git branches, commits, pull requests

### ISSUE THREAD

**Issue by mha1** [ExpressLRS/ExpressLRS-Configurator#565]
## Expected Behavior

Configurator ia able to build git branches, commits, pull request

## Current Behavior

Configurator can't build git branches, commits, pull requests after PR#2400

## Steps to Reproduce

1. open Configurator 1.6.0 and select tab GIT BRANCH
2. pick any branch
3. observe error message 
4. 
![image](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/5615068/2b6f5037-ae4d-452f-b0ab-3384172e6e03)

## Possible Solution (Not obligatory)

add support for external hardware repo

## Context

https://github.com/ExpressLRS/ExpressLRS/pull/2400 moved hardware definitions to separate repo and states "For this to be useful, Configurator and the Web-flasher will require changes to use the hardware.zip from the artifact repository, so when new targets are added they automatically show up in the UIs."

## Your Environment

- W10, Configurator 1.6.0

**Comment by Meldinov** [comment]
git branch 3.x.x works, but i need 2.x.x and it doesn't

**Comment by mha1** [comment]
@jurgelenas can you please have a look at this issue

**Comment by x4code** [comment]
having same issue on configurator 1.6 since hardware folder has moved :\  im trying to Build "LOCAL" branch :\

Thanks

**Comment by jurgelenas** [comment]
Fixed in #566

**Comment by mha1** [comment]
Thanks
