### ISSUE TITLE
How to force internal module on Radiomaster pocket into bootloader?

### ISSUE THREAD

**Issue by Anton33455** [ExpressLRS/ExpressLRS-Configurator#568]
My Radiomaster Pocket with internal ELRS won't bind to anything.  So i decided to flash it. When you place firmware file in the radio and try to execute it, it tries to flash external RF not internal, which is odd.  I am able to run lua script and there is a LED when I turn on internal RF on.  When I activate WiFi I get a hotspot, can connect to it but configurator won't flash anything.  ip address in browser only opens MSN webpage.  Any ideas how to put this into bootloader and force flash it?  I was told that I should use Zoro target.  Any advice would be appreciated.ummary

**Comment by jurgelenas** [comment]
This repository is primarily dedicated to the development of the expresslrs configurator. It is unlikely that you will find the help you are looking for over here.

Our Discord server and/or Facebook group are better suited for these types of questions:

- [Discord Chat](https://discord.gg/dS6ReFY)
- [Facebook Group](https://www.facebook.com/groups/636441730280366)
