### ISSUE TITLE
Unified_ESP32_2400_TX_via_UART  FAILED

### ISSUE THREAD

**Issue by chendega** [ExpressLRS/ExpressLRS-Configurator#579]
## Current Behavior

I'm getting a build error no matter what I try. The only part that stands out is the "Unified_ESP32_2400_TX_via_UART  FAILED" part but I don't know what this means. This is my first time doing anything like this so I'm in a bit over my head right now.

## Steps to Reproduce

NamimnoRC Flash OLED 2.4GHz TX

Failed to find Platformio on your computer. Trying to install it automatically...
Installer version: 1.1.2

Platform: Windows-10
Python version: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Python path: C:\Users\Administrator\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python\python3.exe

Creating a virtual environment at C:\Users\Administrator\.platformio\penv

Updating Python package manager (PIP) in a virtual environment

PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core

Collecting platformio

  Downloading platformio-6.1.11-py3-none-any.whl.metadata (6.9 kB)

Collecting bottle==0.12.* (from platformio)

  Downloading bottle-0.12.25-py3-none-any.whl (90 kB)

     ----------------------------------------
 90.2/90.2 kB 1.3 MB/s eta 0:00:00

Collecting click<=8.2,>=8.0.4 (from platformio)

  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)

Collecting colorama (from platformio)

  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)

Collecting marshmallow==3.* (from platformio)

  Downloading marshmallow-3.20.1-py3-none-any.whl.metadata (7.8 kB)

Collecting pyelftools==0.29 (from platformio)

  Downloading pyelftools-0.29-py2.py3-none-any.whl (174 kB)

     -------------------------------------- 174.3/174.3 kB 3.5 MB/s eta 0:00:00

Collecting pyserial==3.5.* (from platformio)

  Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)

     ---------------------------------------- 90.6/90.6 kB 5.0 MB/s eta 0:00:00

Collecting requests==2.* (from platformio)

  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)

Collecting semantic-version==2.10.* (from platformio)

  Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)

Collecting tabulate==0.* (from platformio)

  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)

Collecting ajsonrpc==1.2.* (from platformio)

  Downloading ajsonrpc-1.2.0-py3-none-any.whl (22 kB)

Collecting starlette<0.32,>=0.19 (from platformio)

  Downloading starlette-0.31.1-py3-none-any.whl.metadata (5.8 kB)

Collecting uvicorn<0.24,>=0.16 (from platformio)

  Downloading uvicorn-0.23.2-py3-none-any.whl.metadata (6.2 kB)

Collecting wsproto==1.* (from platformio)

  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)

Collecting packaging>=17.0 (from marshmallow==3.*->platformio)

  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)

Collecting charset-normalizer<4,>=2 (from requests==2.*->platformio)

  Downloading charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl.metadata (34 kB)

Collecting idna<4,>=2.5 (from requests==2.*->platformio)

  Downloading idna-3.6-py3-none-any.whl.metadata (9.9 kB)

Collecting urllib3<3,>=1.21.1 (from requests==2.*->platformio)

  Downloading urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)

Collecting certifi>=2017.4.17 (from requests==2.*->platformio)

  Downloading certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)

Collecting h11<1,>=0.9.0 (from wsproto==1.*->platformio)

  Downloading h11-0.14.0-py3-none-any.whl (58 kB)

     ---------------------------------------- 58.3/58.3 kB 3.2 MB/s eta 0:00:00

Collecting anyio<5,>=3.4.0 (from starlette<0.32,>=0.19->platformio)

  Downloading anyio-4.2.0-py3-none-any.whl.metadata (4.6 kB)

Collecting typing-extensions>=4.0 (from uvicorn<0.24,>=0.16->platformio)

  Downloading typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)

Collecting sniffio>=1.1 (from anyio<5,>=3.4.0->starlette<0.32,>=0.19->platformio)

  Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)

Collecting exceptiongroup>=1.0.2 (from anyio<5,>=3.4.0->starlette<0.32,>=0.19->platformio)

  Downloading exceptiongroup-1.2.0-py3-none-any.whl.metadata (6.6 kB)

Downloading platformio-6.1.11-py3-none-any.whl (416 kB)

   ---------------------------------------- 416.9/416.9 kB 6.5 MB/s eta 0:00:00

Downloading marshmallow-3.20.1-py3-none-any.whl (49 kB)

   ---------------------------------------- 49.4/49.4 kB ? eta 0:00:00

Downloading requests-2.31.0-py3-none-any.whl (62 kB)

   ---------------------------------------- 62.6/62.6 kB 3.3 MB/s eta 
0:00:00

Downloading click-8.1.7-py3-none-any.whl (97 kB)

   ---------------------------------------- 97.9/97.9 kB 5.8 MB/s eta 0:00:00

Downloading starlette-0.31.1-py3-none-any.whl (69 kB)

   ---------------------------------------- 69.9/69.9 kB ? eta 
0:00:00

Downloading uvicorn-0.23.2-py3-none-any.whl (59 kB)

   ---------------------------------------- 59.5/59.5 kB 3.1 MB/s eta 0:00:00

Downloading anyio-4.2.0-py3-none-any.whl (85 kB)

   ---------------------------------------- 85.5/85.5 kB 5.0 MB/s eta 0:00:00

Downloading certifi-2023.11.17-py3-none-any.whl (162 kB)

   ---------------------------------------- 162.5/162.5 kB 4.8 MB/s eta 0:00:00

Downloading charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)

   ---------------------------------------- 100.3/100.3 kB 6.0 MB/s eta 0:00:00

Downloading idna-3.6-py3-none-any.whl (61 kB)

   ---------------------------------------- 61.6/61.6 kB 1.7 MB/s eta 0:00:00

Downloading packaging-23.2-py3-none-any.whl (53 kB)

   ---------------------------------------- 53.0/53.0 kB 2.7 MB/s eta 0:00:00

Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)

Downloading urllib3-2.1.0-py3-none-any.whl (104 kB)

   ---------------------------------------- 104.6/104.6 kB 5.9 MB/s eta 
0:00:00

Downloading exceptiongroup-1.2.0-py3-none-any.whl (16 kB)

Installing collected packages: pyserial, pyelftools, bottle, urllib3, typing-extensions, tabulate, sniffio, semantic-version, packaging, idna, h11, exceptiongroup, colorama, charset-normalizer, certifi, ajsonrpc, wsproto, requests, marshmallow, click, anyio, uvicorn, starlette, platformio

Successfully installed ajsonrpc-1.2.0 anyio-4.2.0 bottle-0.12.25 certifi-2023.11.17 charset-normalizer-3.3.2 click-8.1.7 colorama-0.4.6 exceptiongroup-1.2.0 h11-0.14.0 idna-3.6 marshmallow-3.20.1 packaging-23.2 platformio-6.1.11 pyelftools-0.29 pyserial-3.5 requests-2.31.0 semantic-version-2.10.0 sniffio-1.3.0 starlette-0.31.1 tabulate-0.9.0 typing-extensions-4.9.0 urllib3-2.1.0 uvicorn-0.23.2 wsproto-1.2.0

PlatformIO Core has been successfully installed into an isolated environment `C:\Users\Administrator\.platformio\penv`!

The full path to `platformio.exe` is `C:\Users\Administrator\.platformio\penv\Scripts\platformio.exe`

If you need an access to `platformio.exe` from other applications, please install Shell Commands
(add PlatformIO Core binary directory `C:\Users\Administrator\.platformio\penv\Scripts` to the system environment PATH variable):

See https://docs.platformio.org/page/installation.html#install-shell-commands

********************************************************************************
If you like PlatformIO, please:
- star it on GitHub > https://github.com/platformio/platformio-core
- follow us on LinkedIn to stay up-to-date on the latest project news > https://www.linkedin.com/company/platformio/
- try PlatformIO IDE for embedded development > https://platformio.org/platformio-ide
********************************************************************************

Processing Unified_ESP32_2400_TX_via_UART (platform: espressif32@5.2.0; board: esp32dev; framework: arduino)
--------------------------------------------------------------------------------

Platform Manager: Installing espressif32 @ 5.2.0

Downloading 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Unpacking 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Platform Manager: espressif32@5.2.0 has been installed!

Tool Manager: Installing espressif/toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3

Downloading 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Unpacking 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Tool Manager: toolchain-xtensa-esp32@8.4.0+2021r2-patch3 has been installed!

Tool Manager: Installing platformio/framework-arduinoespressif32 @ ~3.20005.0

Downloading 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Unpacking 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Tool Manager: framework-arduinoespressif32@3.20005.220925 has been installed!

Tool Manager: Installing platformio/tool-esptoolpy @ ~1.40201.0

Downloading 0%
 10%
 20%
 30%
 40%
 50% 60%
 70% 80%
 90%
 100%

Unpacking 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Tool Manager: tool-esptoolpy@1.40201.0 has been installed!

Tool Manager: Installing platformio/tool-scons @ ~4.40502.0

Downloading 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Unpacking 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Tool Manager: tool-scons@4.40502.0 has been installed!

Library Manager: Installing makuna/NeoPixelBus @ 2.7.0

Downloading 0%
 10%
 20%
 30%
 40% 50%
 60%
 70%
 80%
 90%
 100%

Unpacking 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Library Manager: NeoPixelBus@2.7.0 has been installed!

Library Manager: Resolving dependencies...

Library Manager: Installing ottowinter/ESPAsyncWebServer-esphome @ 3.0.0

Downloading 0% 10%
 20%
 30%
 40%
 50%
 60%
 70% 80%

Unpacking 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Library Manager: ESPAsyncWebServer-esphome@3.0.0 has been installed!

Library Manager: Resolving dependencies...

Library Manager: Installing esphome/AsyncTCP-esphome

Downloading 0%
 10% 20% 30%

Unpacking 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Library Manager: AsyncTCP-esphome@2.1.0 has been installed!

Library Manager: Installing lemmingdev/ESP32-BLE-Gamepad @ 0.5.2

Downloading 0% 10%
 20%
 30%

Unpacking 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Library Manager: ESP32-BLE-Gamepad@0.5.2 has been installed!

Library Manager: Resolving dependencies...

Library Manager: Installing NimBLE-Arduino

Downloading 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Unpacking 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Library Manager: NimBLE-Arduino@1.4.1 has been installed!

Library Manager: Installing bblanchon/ArduinoJson @ 6.19.4

Downloading 0%
 10%
 20%
 30%
 40%
 50%
 60% 70% 80% 90% 100%

Unpacking 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Library Manager: ArduinoJson@6.19.4 has been installed!

Library Manager: Installing moononournation/GFX Library for Arduino @ 1.2.8

Downloading 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Unpacking 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Library Manager: GFX Library for Arduino@1.2.8 has been installed!

Library Manager: Installing olikraus/U8g2 @ 2.34.4

Downloading 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Unpacking 0%
 10%
 20%
 30%
 40%
 50%
 60%
 70%
 80%
 90%
 100%

Library Manager: U8g2@2.34.4 has been installed!

Verbose mode can be enabled via `-v, --verbose` option

UID bytes: 53,100,1,33,160,4

fatal: not a git repository (or any of the parent directories): .git

***
Building for ESP32 Platform

CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (5.2.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20005.220925 (2.0.5) 

 - tool-esptoolpy @ 1.40201.0 (4.2.1) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3

LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft

Found 89 compatible libraries
Scanning dependencies...

Dependency Graph

|-- NeoPixelBus @ 2.7.0

|-- ESPAsyncWebServer-esphome @ 3.0.0

|-- ESP32-BLE-Gamepad @ 0.5.2

|-- NimBLE-Arduino @ 1.4.1

|-- ArduinoJson @ 6.19.4

|-- GFX Library for Arduino @ 1.2.8
|-- U8g2 @ 2.34.4

|-- SPIFFS @ 2.0.0

|-- OTA

|-- SX1280Driver
|-- LBT

|-- DEVICE

|-- CRSF

|-- Telemetry

|-- CRSF2MSP

|-- CONFIG
|-- Wire @ 2.0.0

|-- Backpack

|-- BLE

|-- BUTTON

|-- BUZZER
|-- GSENSOR

|-- LED

|-- LUA

|-- POWER_DETECT

|-- SCREEN

|-- THERMAL
|-- VTX

|-- WIFI

|-- MSP

|-- StubbornReceiver

|-- StubbornSender

|-- TelemetryProtocol
|-- logging

|-- MeanAccumulator

|-- POWERMGNT

|-- FIFO_GENERIC

|-- FIFO

|-- CRC
|-- FHSS

|-- helpers

|-- HWTIMER

|-- LQCALC

Building in release mode

PLATFORM : 'espressif32'
BUILD ENV: 'UNIFIED_ESP32_2400_TX_VIA_UART'
build version: ver.unknown (e051b8) None

Cloning into 'hardware'...

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\src\common.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\src\dynpower.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\src\hal\hal_stm32.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\src\rx-serial\SerialAirPort.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\src\rx-serial\SerialCRSF.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\src\rx-serial\SerialIO.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\src\rx-serial\SerialSBUS.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\src\rx-serial\SerialSUMD.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\src\rx-serial\devSerialIO.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\src\rxtx_common.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\src\tx_main.cpp.o

Building .pio\build\Unified_ESP32_2400_TX_via_UART\bootloader.bin

Generating partitions .pio\build\Unified_ESP32_2400_TX_via_UART\partitions.bin

esptool.py v4.2.1
Creating esp32 image...
Merged 1 ELF section
Successfully created esp32 image.

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib050\SPI\SPI.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\Esp32_i2s.c.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\HsbColor.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\HslColor.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\HtmlColor.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\HtmlColorNameStrings.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\HtmlColorNames.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\HtmlColorShortNames.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\NeoEsp32RmtMethod.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\NeoEsp8266I2sMethodCore.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\NeoEsp8266UartMethod.cpp.o

Archiving .pio\build\Unified_ESP32_2400_TX_via_UART\lib050\libSPI.a

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\NeoEspBitBangMethod.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\NeoGamma.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\NeoPixelAnimator.cpp.o

src/common.cpp: In function 'void initUID()':
src/common.cpp:175:19: warning: unused variable 'WiFiErr' [-Wunused-variable]
         esp_err_t WiFiErr = esp_read_mac(MasterUID, ESP_MAC_WIFI_STA);
                   ^~~~~~~

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\NeoPixelAvr.c.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\Rgb48Color.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\RgbColor.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\RgbColorBase.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\Rgbw64Color.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\RgbwColor.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\NeoPixelBus\internal\SegmentDigit.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libf44\AsyncTCP-esphome\AsyncTCP.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib33c\FS\FS.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\lib33c\FS\vfs_api.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libe4a\WiFi\WiFi.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libe4a\WiFi\WiFiAP.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libe4a\WiFi\WiFiClient.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libe4a\WiFi\WiFiGeneric.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libe4a\WiFi\WiFiMulti.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libe4a\WiFi\WiFiSTA.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libe4a\WiFi\WiFiScan.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libe4a\WiFi\WiFiServer.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libe4a\WiFi\WiFiUdp.cpp.o

.pio/libdeps/Unified_ESP32_2400_TX_via_UART/AsyncTCP-esphome/src/AsyncTCP.cpp:753:2: error: #else without #if
 #else
  ^~~~
.pio/libdeps/Unified_ESP32_2400_TX_via_UART/AsyncTCP-esphome/src/AsyncTCP.cpp:755:2: error: #endif without #if
 #endif
  ^~~~~

.pio/libdeps/Unified_ESP32_2400_TX_via_UART/AsyncTCP-esphome/src/AsyncTCP.cpp:1020: error: unterminated #if
 #if LWIP_IPV4 && LWIP_IPV6
 

Archiving .pio\build\Unified_ESP32_2400_TX_via_UART\lib9ea\libNeoPixelBus.a

.pio/libdeps/Unified_ESP32_2400_TX_via_UART/AsyncTCP-esphome/src/AsyncTCP.cpp: In member function 'bool AsyncClient::connect(const char*, uint16_t)':
.pio/libdeps/Unified_ESP32_2400_TX_via_UART/AsyncTCP-esphome/src/AsyncTCP.cpp:754:39: error: 'ip_addr_t' {aka 'struct ip_addr'} has no member named 'addr'; did you mean 'u_addr'?
         return connect(IPAddress(addr.addr), port);
                                       ^~~~
                                       u_addr

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libd44\ESPAsyncWebServer-esphome\AsyncEventSource.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libd44\ESPAsyncWebServer-esphome\AsyncWebSocket.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libd44\ESPAsyncWebServer-esphome\WebAuthentication.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libd44\ESPAsyncWebServer-esphome\WebHandlers.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libd44\ESPAsyncWebServer-esphome\WebRequest.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libd44\ESPAsyncWebServer-esphome\WebResponses.cpp.o

Compiling .pio\build\Unified_ESP32_2400_TX_via_UART\libd44\ESPAsyncWebServer-esphome\WebServer.cpp.o

*** [.pio\build\Unified_ESP32_2400_TX_via_UART\libf44\AsyncTCP-esphome\AsyncTCP.cpp.o] Error 1

========================= [FAILED] Took 465.62 seconds =========================

Environment                     Status    Duration
------------------------------  --------  ------------
Unified_ESP32_2400_TX_via_UART  FAILED    00:07:45.616
==================== 1 failed, 0 succeeded in 00:07:45.616 ====================

2.

3.

4.

## Your Environment

- Operating System and version:
- TX hardware:
- RX hardware:

**Comment by pkendall64** [comment]
We already have PR in place to fix this.It was caused by an upstream dependency publishing a tag for as completely broken library! The PR that fixes this issue is https://github.com/ExpressLRS/ExpressLRS/pull/2511
