### ISSUE TITLE
ELRS configurator 1.6.0+ firmwares are showing wrong version number in web interface

### ISSUE THREAD

**Issue by ech0-py** [ExpressLRS/ExpressLRS-Configurator#586]
## Expected Behavior

The "Firmware Rev." shows "3.2.0 (8d3388)" in web UI (see screenshot under the cut)

<details>
  <summary>Click me</summary>

![1_exp](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/415353/26638f68-0b4f-4cb6-8846-85499c219807)
</details>

## Current Behavior

The "Firmware Rev." shows "merge (481945)" in web UI (see screenshot under the cut)

<details>
  <summary>Click me</summary>

![1_act](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/415353/22a60919-2699-4bb1-a02c-e77d607d1b41)
</details>

## Steps to Reproduce

1. Install ELRS configurator 1.6.0 or 1.6.1

2. Build a new firmware with such options:
```
Release: 3.2.0
Device category: Happymodel 900 MHz
Device: HappyModel RX ES900RX
Flashing method: WIFI
Mode: Standard mode
Regulatory domain: FCC 915
AUTO_WIFI_ON_INTERVAL: 60
Deselect everything else
```

4. Upload the new firmware.bin.gz through 10.0.0.1 web UI

5. Re-connect to the UI and see the fw number

## Possible Solution (Not obligatory)

ELRS configurator 1.5.10 builds shows correct firmware version

## Context

This issue makes troubles to know the actual version of RX through web UI

## Your Environment

- Operating System and version:
- OS: Win11
- ELRS Configurator version: 1.6.0 and 1.6.1
- TX hardware: -
- RX hardware: HappyModel ES900RX

**Comment by ech0-py** [comment]
@pkendall64 sorry I'm new to the ExpressLRS, would you please clarify one more thing.
I supposed that if I'm building fw from official releases tab then I'll get version that corresponds to the tag, am I wrong?
Adding a full screenshot of app to avoid misunderstanding
![full](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/415353/5e597bbc-1f30-4c4f-ad82-8194465fa2b2)

**Comment by pkendall64** [comment]
Yes, that is correct. Using 1.6.1 of configurator should not need to build the firmware, it should use the pre-built binary assets from our artifact repository.
