### ISSUE TITLE
When installing .deb package on Ubuntu 23.10, it reports dependency problem due to missing dconf2

### ISSUE THREAD

**Issue by seriyps** [ExpressLRS/ExpressLRS-Configurator#591]
## Expected Behavior

When installing the app via .deb package, installation should be successful

## Current Behavior

While the app installs, it reports error and APT state becomes inconsistent:

```
$ sudo dpkg -i ~/Downloads/expresslrs-configurator_1.6.1_amd64.deb
Selecting previously unselected package expresslrs-configurator.
(Reading database ... 414030 files and directories currently installed.)
Preparing to unpack .../expresslrs-configurator_1.6.1_amd64.deb ...
Unpacking expresslrs-configurator (1.6.1) ...
dpkg: dependency problems prevent configuration of expresslrs-configurator:
 expresslrs-configurator depends on gconf2; however:
  Package gconf2 is not installed.

dpkg: error processing package expresslrs-configurator (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1.1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu5) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for bamfdaemon (0.5.6+22.04.20220217-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 expresslrs-configurator
```

## Steps to Reproduce

1. While on Ubuntu 23.10
2. Download .deb package form releases page
3. run `dpkg -i ~/Downloads/expresslrs-configurator_1.6.1_amd64.deb`

## Possible Solution (Not obligatory)

I believe it should be safe to just remove this line:

https://github.com/ExpressLRS/ExpressLRS-Configurator/blob/1531cd6cd0d467dc54263997875814bdeba7cf1f/package.json#L134

Because the app still launches after the installation error. The roblem is that it leaves API in inconsistent state and makes software updates impossible unless I remove elrs-configurator.

## Context

not relevant

## Your Environment

- elrs-configurator version: 1.6.1
- Operating System and version: Ubuntu 23.10
- TX hardware: not relevant
- RX hardware: not relevant

**Comment by woutervddn** [comment]
Can confirm, I also have this issue on Ubuntu 23.10

**Comment by woutervddn** [comment]
Can confirm that removing `gconf2, gconf-service,`  from the control file solves the issue.

I wanted to include the amended .deb file, but that is not allowed (probably for the best). 
So I'll give the recipe instead.

I ran the following to produce an installable .deb file:
```
mkdir expresslrs
cd expresslrs
wget https://github.com/ExpressLRS/ExpressLRS-Configurator/releases/download/v1.6.1/expresslrs-configurator_1.6.1_amd64.deb
dpkg-deb -x expresslrs-configurator_1.6.1_amd64.deb tmp
dpkg-deb --control expresslrs-configurator_1.6.1_amd64.deb
mv DEBIAN tmp/
gedit tmp/DEBIAN/control
```

Remove gconf and gconf-service, save the file and close

```
sudo apt-get install -f ./expresslrs-configurator_1.6.1_amd64_hotfix.deb
```

Without the -f (--fix-missing) it complained on my system that python3-distutils was not installed.

**Comment by amatsumara** [comment]
Yeah, I can confirm this issue on Ubuntu 23.10 as well

**Comment by amatsumara** [comment]
Same on the latest Ubuntu 24.04 LTS (Noble Numbat). Sure I can install gconf2 etc. packages from lunar repos but would be nice to have convenient way to install Configurator natively without workarounds.

**Comment by codebykyle** [comment]
Downloading the newest release and running the .deb file gave the same error. There is no install candidate for gconf or gconf-service in Ubuntu 23.10

**Comment by jurgelenas** [comment]
> Downloading the newest release and running the .deb file gave the same error. There is no install candidate for gconf or gconf-service in Ubuntu 23.10

Please use latest nightly.
