### ISSUE TITLE
libappindicator1 dependency on Debian Bullseye

### ISSUE THREAD

**Issue by JoeriCapens** [ExpressLRS/ExpressLRS-Configurator#6]
I'm running Debian 11 Bullseye and when installing the .deb package I got the following dependency messages:

$ sudo dpkg -i expresslrs-configurator_0.3.4_amd64.deb 
Selecting previously unselected package expresslrs-configurator.
(Reading database ... 296344 files and directories currently installed.)
Preparing to unpack expresslrs-configurator_0.3.4_amd64.deb ...
Unpacking expresslrs-configurator (0.3.4) ...
dpkg: dependency problems prevent configuration of expresslrs-configurator:
 expresslrs-configurator depends on gconf2; however:
  **Package gconf2 is not installed.**
 expresslrs-configurator depends on libappindicator1; however:
  **Package libappindicator1 is not installed.**

dpkg: error processing package expresslrs-configurator (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mailcap (3.68) ...
Processing triggers for gnome-menus (3.36.0-1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Errors were encountered while processing:
 expresslrs-configurator

I could simply install gconf2 with "sudo apt install gconf2" but the package for libappindicator1 doesn't exist for Bullseye, it has been deprecated.

I found a workaround by simply removing the dependency from the package as follows:

$ dpkg-deb -R expresslrs-configurator_0.3.4_amd64.deb expresslrs-configurator

Edit file expresslrs-configurator/DEBIAN/control and remove "libappindicator1, " from the "Depends:" line

$ dpkg-deb -b expresslrs-configurator expresslrs-configurator_0.3.4_amd64_nolibappindicator1.deb
$ sudo dpkg -i expresslrs-configurator_0.3.4_amd64_nolibappindicator1.deb

The configurator seems to work fine without the library, maybe it could/should be removed?

**Comment by jurgelenas** [comment]
Thank you @JoeriCapens for bug report, I have updated deb package dependencies list.

Fixed in [f1ce3ed](https://github.com/ExpressLRS/ExpressLRS-Configurator/commit/f1ce3edaf4037e8cc8f0fa50c525d76730f13be2).
