### ISSUE TITLE
Wi-Fi turns on with AUTO_WIFI_ON_INTERVAL disabled

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/ExpressLRS-Configurator#603]
See: https://github.com/ExpressLRS/ExpressLRS/issues/2699

It was reported by @JyeSmith that it works when using PIO directly, but not when flashed through the configurator.

**Comment by jurgelenas** [comment]
We need to pass `--no-auto-wifi` if `AUTO_WIFI_ON_INTERVAL` option is disabled in https://github.com/ExpressLRS/ExpressLRS-Configurator/blob/a7e58082d8c551d83f0a8efe175e46a95238362d/src/api/src/services/BinaryFlashingStrategy/BinaryConfigurator/index.ts#L143

**Comment by anti-vaxxer** [comment]
hey jurgelenas I just tried it with Configurator 1.7.0, flashed Happymodel EP1 TCXO and Wi-Fi still turns on with AUTO_WIFI_ON_INTERVAL disabled

**Comment by jurgelenas** [comment]
> hey jurgelenas I just tried it with Configurator 1.7.0, flashed Happymodel EP1 TCXO and Wi-Fi still turns on with AUTO_WIFI_ON_INTERVAL disabled

Can you post configurator logs?

**Comment by anti-vaxxer** [comment]
> Can you post configurator logs?

yes 
[ExpressLRSBuildLog_20240624084442991.txt](https://github.com/user-attachments/files/15952268/ExpressLRSBuildLog_20240624084442991.txt)

**Comment by jurgelenas** [comment]
> > Can you post configurator logs?
> 
> yes [ExpressLRSBuildLog_20240624084442991.txt](https://github.com/user-attachments/files/15952268/ExpressLRSBuildLog_20240624084442991.txt)

Sorry, not these. Can you go to sidebar menu -> logs -> open logs folder and post the file over here?

**Comment by anti-vaxxer** [comment]
> > > Can you post configurator logs?
> > 
> > 
> > yes [ExpressLRSBuildLog_20240624084442991.txt](https://github.com/user-attachments/files/15952268/ExpressLRSBuildLog_20240624084442991.txt)
> 
> Sorry, not these. Can you go to sidebar menu -> logs -> open logs folder and post the file over here?

oh yes here it is https://file.io/LUYvs1xM89e3

**Comment by jurgelenas** [comment]
> > > > Can you post configurator logs?
> > > 
> > > 
> > > yes [ExpressLRSBuildLog_20240624084442991.txt](https://github.com/user-attachments/files/15952268/ExpressLRSBuildLog_20240624084442991.txt)
> > 
> > 
> > Sorry, not these. Can you go to sidebar menu -> logs -> open logs folder and post the file over here?
> 
> oh yes here it is https://file.io/LUYvs1xM89e3

Thanks. I was able to find the root cause for this issue. Will fix this in the next ExpressLRS Configurator release.

**Comment by jurgelenas** [comment]
Fixed in #632
