### ISSUE TITLE
Sort languages list alphabetically in settings screen 

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/ExpressLRS-Configurator#604]

**Comment by kaestro** [comment]
Hi, @jurgelenas 

can I get more elaborate explanation on what does sort lanauage list alphabetically mean?

**Comment by atiehamidi** [comment]
Hi, @jurgelenas Do you mean in this file => dependencies/windows_amd64/python/Lib/site-packages/pip/_vendor/chardet/metadata/languages.py ?
If yes, can you assign it to me? thanks

**Comment by jurgelenas** [comment]
Fixed in #605
