### ISSUE TITLE
Broken dependency ubuntu 24.04

### ISSUE THREAD

**Issue by mituritsyn** [ExpressLRS/ExpressLRS-Configurator#606]
## Expected Behavior

ELRS configurator could be launched

## Current Behavior

Can't run elrs configurator on Ubuntu 24.04 due to broken dependency

```
dpkg: dependency problems prevent configuration of expresslrs-configurator:
 expresslrs-configurator depends on python3-distutils; however:
  Package python3-distutils is not installed.
```
  
python3-distutils was deprecated in Python 3.12

## Steps to Reproduce

1. install under system with python version >= 3.12

2. have fun

## Possible Solution (Not obligatory)

I believe python3-setuptools is the successor to distutils.

## Your Environment

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble

```
```
$ python3 --version
Python 3.12.3

```

**Comment by chaotixtech** [comment]
Same problem running exactly the same version but Kubuntu flavour, eagerly awaiting a fix ;)
