### ISSUE TITLE
Installation problem. error: target not found: electron20

### ISSUE THREAD

**Issue by dk0bzar** [ExpressLRS/ExpressLRS-Configurator#608]
## Expected Behavior
expresslrs-configurator should be installed

## Current Behavior
Can't install expresslrs-configurator on Arch Linux via AUR due to missing dependencies

## Steps to Reproduce
1. Clone the repository:
 `user@3456 ~/Downloads $ git clone https://aur.archlinux.org/expresslrs-configurator.git`
2. Change to the cloned directory:
`user@3456 ~/Downloads $ cd expresslrs-configurator/`
3. Run makepkg to build and install the package:
`user@3456 ~/Downloads/expresslrs-configurator [master] $ makepkg -sirc`
4. Encounter the following error:

       ==> Making package: expresslrs-configurator 1.6.1-1 (Sun 19 May 2024 10:18:34 PM EEST)
       ==> Checking runtime dependencies...
       ==> Installing missing dependencies...
       error: target not found: electron20
       ==> ERROR: 'pacman' failed to install missing dependencies.
       ==> Missing dependencies:
         -> electron20
         -> platformio-core-udev
       user@3456 ~/Downloads/expresslrs-configurator [master] $ sudo pacman -S electron20
       error: target not found: electron20
       user@3456 ~/Downloads/expresslrs-configurator [master] $

1. Clone the repository.
2. Change to the cloned directory.
3. Run makepkg -sirc.
4. Encounter the error: target not found: electron20.

## Possible Solution (Not obligatory)

The issue seems to be that electron20 is not available in the official repositories. It might need to be installed from an alternative source or the PKGBUILD file needs updating to a supported version of electron.

Updating the PKGBUILD to use a newer version of electron that's available in the official repositories, such as electron22, could be a potential fix.

## Context
This issue prevents me from installing and using the expresslrs-configurator on my Arch Linux system.

## Your Environment

- Operating System and version: Arch Linux
- Package Manager: pacman

**Comment by jurgelenas** [comment]
Can you test latest nightly release? https://github.com/ExpressLRS/ExpressLRS-Configurator-Nightlies/releases
