### ISSUE TITLE
Jumper T Pro V2 ELRS internal module

### ISSUE THREAD

**Issue by pagex** [ExpressLRS/ExpressLRS-Configurator#625]
## Summary

Is there target plans for Jumper T Pro V2 ELRS internal module, tried flashing with T Pro version - module not responding (ElrsV3.lua) hangs.

**Comment by jurgelenas** [comment]
This repository is primarily dedicated to the development of the expresslrs configurator. It is unlikely that you will find the help you are looking for over here.

Our Discord server and/or Facebook group are better suited for these types of questions:

- [Discord Chat](https://discord.gg/dS6ReFY)
- [Facebook Group](https://www.facebook.com/groups/636441730280366)
