### ISSUE TITLE
Fix serial monitor baud rate parsing

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/ExpressLRS-Configurator#626]
![image](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/1081265/e5be0cb5-98bf-4d6a-a95e-93941deff6ad)

**Comment by gbisaga** [comment]
I'm working on this now. Should have it done this weekend.

**Comment by jurgelenas** [comment]
Fixed in #634
