### ISSUE TITLE
ExpressLRS configurator error

### ISSUE THREAD

**Issue by tomcass240** [ExpressLRS/ExpressLRS-Configurator#628]
When trying to connect to the serial monitor with the configurator on my radiomaster rp2 I get the following error message:

Error occurred: TypeError: "baudRate" must be a number: 420000

There is already a number in there.

This is clearly a bug, please fix it.

**Comment by pkendall64** [comment]
See #626

**Comment by jurgelenas** [comment]
Closing in favor of #626
