### ISSUE TITLE
Unable to flash backpack to ESP32 over UART

### ISSUE THREAD

**Issue by i-am-grub** [ExpressLRS/ExpressLRS-Configurator#639]
Originally reported the bug in the backpack repo, but I think it's actually a configurator issue. 

TLDR: The configurator looks for `binary_configurator.py` when trying to flash the backpack over UART to an ESP32 target. This file doesn't exist in the backpack repo and isn't required for flashing the backpack's firmware.

https://github.com/ExpressLRS/Backpack/issues/136

**Comment by pkendall64** [comment]
This totally belongs in the Backpack repo. We just need to rename `binary_flash.py` to `binary_configurator.py`.
