### ISSUE TITLE
Target selectors disappeared in Expert mode on Ubuntu 24.04

### ISSUE THREAD

**Issue by knoppixmeister** [ExpressLRS/ExpressLRS-Configurator#640]
Target selectors disappeared on "Official releases" tab by clicking other tabs and returning back to first tab when Expert mode switched on.

## Steps to Reproduce

1. Set "Export mode" check box on in "Settings"

2. Go to "Configurator" tab on left side

3. Click on "Git branch" tab

4. Click back to "Official Releases" tab

5. Target selectors disappeared

![scr_1](https://github.com/user-attachments/assets/3071b5ac-6600-4352-b539-d51e020767cf)

## Your Environment

- ExpressLRS-Configurator: v1.7.2

- Operating System and version: Ubuntu 24.04

**Comment by jurgelenas** [comment]
Can confirm the issue exists. Thanks for the report @knoppixmeister!

**Comment by jurgelenas** [comment]
Fixed in #651
