### ISSUE TITLE
Unable to generate Backpack binary

### ISSUE THREAD

**Issue by christarento** [ExpressLRS/ExpressLRS-Configurator#643]
## Expected Behavior
Compilation and binary file generation shall be able to complete

## Steps to Reproduce
* Open ExpressLRS configurator1.7.2
* Select Backpack tab
* Select 1.4.1, Radiomaster Pocket, Wifi method (same issue with EdgeTX passthrough)
* Click Compile
* Its fails at the end of compilation unable to 

Environment               Status    Duration
------------------------  --------  ------------
ESP_TX_Backpack_via_UART  SUCCESS   00:00:03.933
========================= 1 succeeded in 00:00:03.933 =========================

C:\Users\XXX\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python\python3.exe: can't open file 'C:\\Users\\XXX\\AppData\\Roaming\\ExpressLRS Configurator\\firmwares\\binary\\Backpack\\python\\binary_configurator.py': [Errno 2] No such file or directory

## Possible Solution (Not obligatory)
None

## Your Environment

- Operating System and version: Windows 11
- TX hardware: N/A
- RX hardware: N/A

**Comment by jurgelenas** [comment]
Should be good now. Closing the issue.

If you are still facing any issues please reopen and post logs.
