### ISSUE TITLE
issues with building file 

### ISSUE THREAD

**Issue by cobyharmon** [ExpressLRS/ExpressLRS-Configurator#65]
hello, 
I am trying to update a new betafpv 2.4GH rx and a happy model 2.4GH tx. when I go to build files I get an error message saying request to https://raw.githubusercontent.com/ExpressLRS/ExpressLRS/1.0.1/src/user_defines.txt failed, reason: unable to get local issuer certificate. Any ideas on how to fix the issue?
- Operating System and version: 1.0.4

**Comment by jurgelenas** [comment]
Hey, this is an issue with your local environment. Please check if you are using any VPNs/Firewalls/proxy servers. If you are trying to use configurator app from China you are likely to experience even more issues. Try seeking helping for this issue on our discord server.
