### ISSUE TITLE
Dpkg installation fails if /opt is on a different device than /usr

### ISSUE THREAD

**Issue by a1j** [ExpressLRS/ExpressLRS-Configurator#654]
## Expected Behavior

Installation succeeds

## Current Behavior

installation fails with following error:
```
dpkg: error processing archive expresslrs-configurator_1.7.2_amd64.deb (--install):
 error creating hard link './usr/share/icons/hicolor/96x96/apps/expresslrs-configurator.png': Invalid cross-device link

```

## Steps to Reproduce

1. mount /opt filesystem on a separate block device

2. Attempt to install debian package

## Possible Solution (Not obligatory)

There should be no hardlinks between top level directories because noone guarantees they are on the same block device.
This is mentioned in [Debian policy](https://lists.debian.org/debian-devel/2013/11/msg00216.html), and probably would have been captured with lintian, if it was being used.

## Your Environment

- Operating System and version:  Debian bookworm, `expresslrs-configurator_1.7.2_amd64.deb`
- TX hardware: Irrelevant
- RX hardware: Irrelevant

**Comment by jurgelenas** [comment]
Closing in favor of #375
