### ISSUE TITLE
Cannot install across multiple partitions in Linux

### ISSUE THREAD

**Issue by Darkmann12** [ExpressLRS/ExpressLRS-Configurator#663]
## Expected Behavior

ExpressLRS configurator is able to install and function

## Current Behavior

ExpressLRS configurator fails to install

## Steps to Reproduce

1. Have your apps install to a different partition (i.e. /opt is its own partition)

2. Attempt to run the .deb

3. .deb fails to complete installation:

![image](https://github.com/user-attachments/assets/14c4463a-569a-4782-91c3-99f2f8108c04)

4. Big Sad

## Your Environment
 
Linux Mint 22 Cinnamon Edition, laptop, 1 boot drive and 1 bigger drive which is partitioned for apps, games and downloads

**Comment by jurgelenas** [comment]
Closing in favor of #375
