### ISSUE TITLE
Cannot flash GEPRC True Diversity 2.4GHx RX due to duplicated regulatory domain lines

### ISSUE THREAD

**Issue by johnmburt** [ExpressLRS/ExpressLRS-Configurator#671]
## Expected Behavior

Should have built binary for GEPRC True Diversity 2.4GHx RX 

Device category: GEPRC 2.4 GHz
Device: GEPRC True Diversity 2.4GHx RX 
Flashing method: wifi
Regulatory domain: REGULATORY_DOMAIN_ISM_2400

## Current Behavior

- The UI shows two selectable entries for "REGULATORY_DOMAIN_ISM_2400"
- It is not possible to check only one: checking/unchecking applies to both

- When I click Build, I get an error message:  "You must choose single regulatory domain for your device in 2.4 GHz band"
- It is impossible to meet this requirement due to the duplicated lines and UI behavior above.

## Steps to Reproduce

Choose configurator tab
Select Device category: GEPRC 2.4 GHz
Select Device: GEPRC True Diversity 2.4GHx RX 
Select Flashing method: wifi

Observe: Regulatory domain has duplicated entries: REGULATORY_DOMAIN_ISM_2400

## Possible Solution (Not obligatory)

Remove duplicate entry from whatever config file specifies Regulatory domain entries

## Context

I cannot flash my RX

## Your Environment

- Operating System and version:
Windows 10

- TX hardware:
N/A

- RX hardware:
N/A

**Comment by jurgelenas** [comment]
Fixed in #672
