### ISSUE TITLE
Unable to build Backpack firmware, popup occurs to select regulatory domain

### ISSUE THREAD

**Issue by SumolX** [ExpressLRS/ExpressLRS-Configurator#673]
## Expected Behavior

Creating flash binaries both HDZero VRX and RadioMaster Ranger 2.4Ghz TX.

Was able to successfully create them using the WiFi Method on version 1.6.1

## Current Behavior

On version 1.7.5 I am presented with the following notification and I'm unable to create the firmware:

"You must choose a regulatory domain for you device."

## Steps to Reproduce

1. Select Backpack
2. Select Device category: RadioMaster
3. Select Device: RadioMaster Ranger 2.4GHz TX
4. Select Flashing Method: WIFI
5. Click: BUILD

## Context

Unable to upgrade backpack firmware with latest version: 1.7.5 but with version 1.6.1 I am able to build the binaries.

## Your Environment

- Operating System and version: macOS Sonoma 14.6.1 M3
- TX hardware: RadioMaster Ranger 2.4GHz Tx
- RX hardware: HDZero Googles

**Comment by davetheghost** [comment]
Same — 

Debian 12 bookworm
RM Zorro TX

**Comment by molokaiboy** [comment]
Same- Radiomaster Ranger Micro 2.4. 
Was able to build the FW on 1.7.3

**Comment by jurgelenas** [comment]
Fixed in  #675
