### ISSUE TITLE
v1.7.6 not detecting home wifi

### ISSUE THREAD

**Issue by miggy1952** [ExpressLRS/ExpressLRS-Configurator#690]
Mac running Sequoia 15

Tried on several Rxs and the device doesn't show up at the bottom of the page

**Comment by miggy1952** [comment]
Same problem with v1.7.5 and that had been working fine, I think the problem started when I upgraded to Sequoia 15

**Comment by L1cardo** [comment]
I have this problem on Win11 as well

**Comment by miggy1952** [comment]
fixed with IOS 15.0.1
