### ISSUE TITLE
Target RXs with PWM

### ISSUE THREAD

**Issue by MartyHugh** [ExpressLRS/ExpressLRS-Configurator#7]
Are there any plans to target RXs which have physical PWM headers? 

All the ones in configurator seem to be SBUS based, I am interested in trying ELRS on a fixed wing,

Thanks

**Comment by jurgelenas** [comment]
My guess is that without a flight controller you will not be able to use ExpressLRS on a fixed wing.

Please try our [Discord Chat](https://discord.gg/dS6ReFY) and  [Facebook Group](https://www.facebook.com/groups/636441730280366) for additional help.

**Comment by MartyHugh** [comment]
Hi Jurgelenas, thank you for your reply.

I would be interested in why it would not be possible to use ExpressLRS on a fixed wing.  Many of the ExpressLRS supported RXs *do* support PWM outputs to pads, the only issue is that I would have to solder them to a servo header if I wanted to connect them to servo plugs. This is exactly what I do with Crossfire nano Rxs I use on my wings, by the way.

ExpressLRS is presumably a medium for connecting TX to and RX, what is it about it which precludes its use without a flight controller ?
