### ISSUE TITLE
R9mx Rev0.2 not supported

### ISSUE THREAD

**Issue by Lucasjuv** [ExpressLRS/ExpressLRS-Configurator#74]
Hi guys I get `WARN /Users/kuwatay/src/stlink-master/src/common.c: unknown chip id! 0x10016435` when trying to flash the R9mx with expressLRS. Here is the st-info:
 ```
st-info --probe --connect-under-reset
Found 1 stlink programmers
  version:    V2J37S7
  serial:     432F05002A135937334D4E00
  flash:      131072 (pagesize: 2048)
  sram:       49152
  chipid:     0x0435
  descr:      L43x/L44x
```

I believe this chip is not supported yet. If someone can help me make the support would be glad to do so. 

Thanks

**Comment by jurgelenas** [comment]
Try filing an issue on main firmware repository https://github.com/ExpressLRS/ExpressLRS. Closing as not related to the configurator app itself.
