### ISSUE TITLE
GHOST TX and GHOST TX LITE Flashing Method

### ISSUE THREAD

**Issue by brandonrc** [ExpressLRS/ExpressLRS-Configurator#76]
Both the GHOST TX full and lite can be flashed using opentx. 

Not sure if we have a wiki on this but basically put the `.elrs` file on the opentx sd card, go to the files and select flash external module.

**Comment by jurgelenas** [comment]
@brandonrc what do you suggest? Adding a help message on the configurator for targets that can be flashed through EdgeTX / OpenTX so users do not attempt to use stlink every time?

**Comment by jurgelenas** [comment]
@justinlampley what do you think about adding new target / UI hint for users to tell about flashing method where you flash directly from the radio?

**Comment by justinlampley** [comment]
We could create a new target in devices.json using the existing target name (GHOST_2400_TX_via_STLINK), but with a new flashing method.  We could call the new method "Controller", or something similar, and its tooltip could provide information about flashing via the controller.  When that flashing method is chosen, only the build button would be shown.  After a successful build, we could show a notification informing the user to copy the binary to their controller and then flash the TX.
