### ISSUE TITLE
How to calculate UID by using MD5

### ISSUE THREAD

**Issue by HWT662988** [ExpressLRS/ExpressLRS-Configurator#77]
## Summary

The result I calculated using MD5 is different from the value you calculated. How can I calculate this value?  I would be very grateful if you could tell me the detailed calculation procedure
![Snipaste_2021-10-07_18-41-16](https://user-images.githubusercontent.com/45007731/136369283-c063d463-7101-45d2-9447-c59fefbc993c.png)
!

**Comment by jurgelenas** [comment]
You can get your byte values in our docs: https://www.expresslrs.org/1.0/hardware/spi-receivers/#binding-phrase

You can check how it is calculated in this js file: https://github.com/ExpressLRS/Docs/commit/5742bf74afbe57448b18ab6b516f28793315c32e#diff-1360d8b8ba2929b2bcf5e89dfe0919fee8982e269e3cd6b9cf29d90adee59c4c
