### ISSUE TITLE
Build and flash via stlink reports success when it actually failed

### ISSUE THREAD

**Issue by timbod7** [ExpressLRS/ExpressLRS-Configurator#9]
## Expected Behavior

Without an st-link device connected the "build and flash" option should report failure, but instead show a green success notification.

## Current Behavior

See image:

![Screenshot from 2021-03-10 08-58-46](https://user-images.githubusercontent.com/1996446/110543805-e1dab000-817e-11eb-8613-ef3fa6caeb03.png)

## Steps to Reproduce

1. Disconnect st-link from usb
2. Select target Frsky_RX_R9MM_R9MINI_via_STLINK
3. Press "build & flash"

## Your Environment

 ubuntu 20.04

**Comment by jurgelenas** [comment]
@timbod7 thank you for your bug report! :) That was fixed in https://github.com/ExpressLRS/ExpressLRS/pull/490. Closing.
